const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const cfg=window.MUGHAL_CONFIG||{};
const cloud=Boolean(cfg.supabaseUrl&&cfg.supabasePublishableKey);
const state={token:null,userId:null,businessId:null,business:null,role:'owner',parties:[],projects:[],entries:[],invoices:[],detail:null};
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID();
const esc=(value='')=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const money=value=>`Rs. ${Number(value||0).toLocaleString('en-PK',{maximumFractionDigits:2})}`;
const date=value=>value?new Date(`${value}T00:00:00`).toLocaleDateString('en-PK',{day:'numeric',month:'short',year:'numeric'}):'Not set';
const daysBetween=(start,end)=>start&&end?Math.max(0,Math.round((new Date(`${end}T00:00:00`)-new Date(`${start}T00:00:00`))/86400000)):'';
const shortCode=(prefix,value)=>`${prefix}-${String(value||'NEW').replaceAll('-','').slice(0,8).toUpperCase()}`;
const safeName=value=>String(value||'document').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase();
const party=id=>state.parties.find(row=>row.id===id);
const project=id=>state.projects.find(row=>row.id===id);
const invoiceProject=row=>project(row.project_id);
const projectLabel=row=>`${row.name} - ${party(row.party_id)?.name||'Unknown party'}`;
const quotePrice=row=>row.pricing_mode==='both'?`${money(row.price_with_material)} / ${money(row.price_without_material)}`:money(row.pricing_mode==='without_material'?row.price_without_material:row.price_with_material);
const projectMetrics=row=>{const entries=state.entries.filter(item=>item.project_id===row.id),sum=type=>entries.filter(item=>item.entry_type===type).reduce((total,item)=>total+Number(item.amount||0),0),increase=sum('scope_increase'),decrease=sum('scope_decrease'),original=Number(row.original_contract_amount||0);return{entries,increase,decrease,original,revised:original+increase-decrease};};

class Store{
  constructor(){this.base=(cfg.supabaseUrl||'').replace(/\/$/,'');this.key=cfg.supabasePublishableKey||'';}
  headers(extra={}){return{apikey:this.key,Authorization:`Bearer ${state.token}`,'Content-Type':'application/json',...extra};}
  async request(path,options={}){const response=await fetch(`${this.base}${path}`,{...options,headers:this.headers(options.headers)});if(response.status===401){logout(false);throw new Error('Your session expired. Please sign in again.');}if(!response.ok){let message='The action could not be completed.';try{const data=await response.json();message=data.message||data.details||message;}catch{}throw new Error(message);}return response.status===204?null:response.json();}
  async signIn(email,password){const response=await fetch(`${this.base}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:this.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})}),data=await response.json();if(!response.ok)throw new Error(data.error_description||data.msg||'Email or password is incorrect.');state.token=data.access_token;state.userId=data.user.id;localStorage.setItem('mi_mobile_session',JSON.stringify({token:state.token,userId:state.userId}));}
  async load(){if(!cloud){const saved=JSON.parse(localStorage.getItem('mi_mobile_data')||'{}');state.businessId='demo';state.role='owner';state.business=saved.business||{name:'Mughal Interior'};state.parties=saved.parties||[];state.projects=saved.projects||[];state.entries=saved.entries||[];state.invoices=saved.invoices||[];return;}const memberships=await this.request(`/rest/v1/business_members?select=business_id,role&user_id=eq.${state.userId}&order=created_at.desc&limit=1`);if(!memberships.length)throw new Error('This account has not been added to a business.');state.businessId=memberships[0].business_id;state.role=memberships[0].role;[state.parties,state.projects,state.entries,state.invoices]=await Promise.all([this.request(`/rest/v1/parties?select=*&business_id=eq.${state.businessId}&order=name.asc`),this.request(`/rest/v1/projects?select=*&business_id=eq.${state.businessId}&order=created_at.desc`),this.request(`/rest/v1/project_entries?select=*&business_id=eq.${state.businessId}&order=entry_date.asc,created_at.asc`),this.request(`/rest/v1/invoices?select=*&business_id=eq.${state.businessId}&project_id=not.is.null&order=created_at.desc`)]);const businesses=await this.request(`/rest/v1/businesses?select=*&id=eq.${state.businessId}&limit=1`);state.business=businesses[0]||{name:'Mughal Interior'};}
  persist(){if(!cloud)localStorage.setItem('mi_mobile_data',JSON.stringify({business:state.business,parties:state.parties,projects:state.projects,entries:state.entries,invoices:state.invoices}));}
  async save(table,row,updating=false){if(!cloud){const saved={...row,business_id:state.businessId,updated_at:new Date().toISOString()};return saved;}const payload={...row,business_id:state.businessId},path=updating?`/rest/v1/${table}?id=eq.${row.id}`:`/rest/v1/${table}`,result=await this.request(path,{method:updating?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});return result[0];}
  async remove(table,id){if(!cloud)return;const removed=await this.request(`/rest/v1/${table}?id=eq.${id}`,{method:'DELETE',headers:{Prefer:'return=representation'}});if(!removed?.length)throw new Error('Only the business owner can delete this record.');}
}
const store=new Store();

function toast(message){const node=$('#toast');node.textContent=message;node.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.add('hidden'),3200);}
async function working(label,button,action){const overlay=$('#processing'),old=button?.textContent;if(button){button.disabled=true;button.classList.add('processing');button.textContent='Please wait…';}$('#processingText').textContent=label;overlay.classList.remove('hidden');try{return await action();}catch(error){toast(error.message);throw error;}finally{overlay.classList.add('hidden');if(button){button.disabled=false;button.classList.remove('processing');button.textContent=old;}}}
function openSheet(id){$('#backdrop').classList.remove('hidden');$(id).classList.remove('hidden');document.body.style.overflow='hidden';}
function closeSheets(){$('#backdrop').classList.add('hidden');$$('.sheet').forEach(node=>node.classList.add('hidden'));document.body.style.overflow='';}
function route(name){const map={projectsHub:'Projects',parties:'Parties',projectMaster:'Projects',quotes:'Quotes',invoices:'Invoices',orders:'Orders',suppliers:'Suppliers',banking:'Banking',reports:'Reports'};$$('.view').forEach(node=>node.classList.toggle('active',node.id===`${name}View`));$('#screenTitle').textContent=map[name]||'Projects';window.scrollTo({top:0,behavior:'instant'});render();}
function tab(name){$$('[data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tab===name));route(name);}
function empty(title,text){return`<div class="empty"><b>${esc(title)}</b><span>${esc(text)}</span></div>`;}
function upsert(list,row){const index=list.findIndex(item=>item.id===row.id);index>=0?list.splice(index,1,row):list.unshift(row);store.persist();}

function renderParties(){const query=$('#partySearch').value.toLowerCase(),rows=state.parties.filter(row=>[row.name,row.phone,row.address].join(' ').toLowerCase().includes(query));$('#partyList').innerHTML=rows.length?rows.map(row=>`<article class="record-card"><div class="record-top"><div><span class="record-id">${shortCode('PTY',row.id)}</span><h3>${esc(row.name)}</h3><div class="record-meta">${row.phone?`<span>${esc(row.phone)}</span>`:''}${row.address?`<span>${esc(row.address)}</span>`:''}</div></div><button class="view-button" data-view-party="${row.id}">View</button></div></article>`).join(''):empty('No parties found','Add your first customer.');}
function renderProjects(){const query=$('#projectSearch').value.toLowerCase(),rows=state.projects.filter(row=>[row.project_number,row.name,row.location,party(row.party_id)?.name].join(' ').toLowerCase().includes(query));$('#projectList').innerHTML=rows.length?rows.map(row=>`<article class="record-card"><div class="record-top"><div><span class="record-id">${esc(row.project_number||shortCode('PRJ',row.id))}</span><h3>${esc(row.name)}</h3><div class="record-meta"><span>${esc(party(row.party_id)?.name||'Unknown party')}</span>${row.location?`<span>${esc(row.location)}</span>`:''}${row.quote_created?'<span>Quote added</span>':'<span>No quote</span>'}</div></div><button class="view-button" data-view-project="${row.id}">View</button></div></article>`).join(''):empty('No projects found','Add a project record to begin.');}
function renderQuotes(){const query=$('#quoteSearch').value.toLowerCase(),rows=state.projects.filter(row=>row.quote_created&&[row.project_number,row.name,party(row.party_id)?.name].join(' ').toLowerCase().includes(query));$('#quoteList').innerHTML=rows.length?rows.map(row=>`<article class="record-card"><div class="record-top"><div><span class="record-id">${esc(row.project_number)}</span><h3>${esc(row.name)}</h3><div class="record-meta"><span>${esc(party(row.party_id)?.name||'Unknown party')}</span><span>${date(row.quote_date)}</span><span>${quotePrice(row)}</span></div></div><div class="record-side"><span class="status ${row.status==='Approved'?'approved':''}">${esc(row.status)}</span><button class="view-button" data-view-quote="${row.id}">View</button></div></div></article>`).join(''):empty('No quotes found','Add a quote for a saved project.');}
function renderInvoices(){const query=$('#invoiceSearch').value.toLowerCase(),rows=state.invoices.filter(row=>{const job=invoiceProject(row);return[row.invoice_number,job?.name,party(job?.party_id)?.name].join(' ').toLowerCase().includes(query);});$('#invoiceList').innerHTML=rows.length?rows.map(row=>{const job=invoiceProject(row),metric=job?projectMetrics(job):{revised:row.amount};return`<article class="record-card"><div class="record-top"><div><span class="record-id">${esc(row.invoice_number)}</span><h3>${esc(job?.name||'Project invoice')}</h3><div class="record-meta"><span>${esc(party(job?.party_id)?.name||'Unknown party')}</span><span>${date(row.invoice_date)}</span></div></div><div class="record-side"><strong>${money(metric.revised)}</strong><button class="view-button" data-view-invoice="${row.id}">View</button></div></div><div class="form-row card-actions"><button class="button secondary" data-download-invoice="${row.id}">Download PDF</button>${state.role==='owner'?`<button class="delete-button" data-delete-invoice="${row.id}">Delete</button>`:''}</div></article>`;}).join(''):empty('No invoices found','Approved quotes appear here automatically.');}
function render(){renderParties();renderProjects();renderQuotes();renderInvoices();$('#partyOptions').innerHTML=state.parties.map(row=>`<option value="${esc(row.name)}"></option>`).join('');$('#quoteProjectOptions').innerHTML=state.projects.map(row=>`<option value="${esc(projectLabel(row))}"></option>`).join('');}

function openParty(id=''){const row=state.parties.find(item=>item.id===id),next=id||uid();$('#partyForm').reset();$('#partyId').value=next;$('#partyCode').value=shortCode('PTY',next);$('#partyName').value=row?.name||'';$('#partyPhone').value=row?.phone||'';$('#partyAddress').value=row?.address||'';$('#partySheetTitle').textContent=row?'Edit party':'Add party';openSheet('#partySheet');}
function openProject(id=''){if(!state.parties.length){toast('Add a party before creating a project.');route('parties');return;}const row=project(id),next=id||uid();$('#projectForm').reset();$('#projectId').value=next;$('#projectCode').value=row?.project_number||shortCode('PRJ',next);$('#projectName').value=row?.name||'';$('#projectPartySearch').value=party(row?.party_id)?.name||'';$('#projectLocation').value=row?.location||'';$('#projectSheetTitle').textContent=row?'Edit project':'Add project';openSheet('#projectSheet');}
function resolveParty(name){return state.parties.find(row=>row.name.toLowerCase()===name.trim().toLowerCase());}
function resolveProject(label){return state.projects.find(row=>projectLabel(row).toLowerCase()===label.trim().toLowerCase());}
function setQuoteDays(){$('#quoteDays').value=daysBetween($('#quoteStart').value,$('#quoteEnd').value);}
function openQuote(id=''){if(!state.projects.length){toast('Add a project before creating a quote.');route('projectMaster');return;}const row=project(id);$('#quoteForm').reset();$('#quoteProjectId').value=id;$('#quoteProjectSearch').value=row?projectLabel(row):'';$('#quoteProjectSearch').readOnly=Boolean(row);$('#quoteDate').value=row?.quote_date||today();$('#quoteStart').value=row?.start_date||'';$('#quoteEnd').value=row?.expected_end_date||'';$('#quoteDays').value=row?.days_to_complete??'';$('#quoteDetails').value=row?.description||'';$('#quoteWithMaterial').value=row?.price_with_material??'';$('#quoteWithoutMaterial').value=row?.price_without_material??'';$('#quoteShowBoth').checked=row?.pricing_mode==='both';$('#quotePaymentTerms').value=row?.payment_terms||state.business?.default_payment_terms||'';$('#quoteNotes').value=row?.notes||'';$('#quoteSheetTitle').textContent=row?.quote_created?'Edit quote':'Add quote';openSheet('#quoteSheet');}

function detailRows(rows){return`<div class="detail-grid">${rows.map(([label,value])=>`<div class="detail-row"><span>${esc(label)}</span><b>${esc(value||'Not entered')}</b></div>`).join('')}</div>`;}
function setupDetail(type,row,{title,kicker,html,actions='',editable=true,deletable=true}){state.detail={type,id:row.id};$('#detailKicker').textContent=kicker;$('#detailTitle').textContent=title;$('#detailBody').innerHTML=html;$('#detailActions').innerHTML=actions;$('#detailEdit').classList.toggle('hidden',!editable);$('#dangerZone').classList.toggle('hidden',!deletable||state.role!=='owner');$('#detailDelete').textContent=`Delete ${type}`;closeSheets();openSheet('#detailSheet');}
function viewParty(id){const row=state.parties.find(item=>item.id===id);if(!row)return;setupDetail('party',row,{title:row.name,kicker:'PARTY DETAILS',html:`<div class="detail-card"><div class="detail-hero"><p>${shortCode('PTY',row.id)}</p><h3>${esc(row.name)}</h3></div>${detailRows([['Mobile number',row.phone],['Address',row.address]])}</div>`});}
function viewProject(id){const row=project(id);if(!row)return;setupDetail('project',row,{title:row.name,kicker:'PROJECT DETAILS',html:`<div class="detail-card"><div class="detail-hero"><p>${esc(row.project_number)}</p><h3>${esc(row.name)}</h3></div>${detailRows([['Party',party(row.party_id)?.name],['Location',row.location],['Quote',row.quote_created?'Created':'Not created'],['Status',row.status]])}</div>`});}
function quoteDocument(row){const prices=row.pricing_mode==='both'?[['Amount with material',money(row.price_with_material)],['Amount without material',money(row.price_without_material)]]:row.pricing_mode==='without_material'?[['Amount without material',money(row.price_without_material)]]:[['Amount with material',money(row.price_with_material)]];return`<article class="detail-card pdf-document"><div class="detail-hero"><p>PROJECT QUOTATION · ${esc(row.project_number)}</p><h3>${esc(row.name)}</h3><div class="detail-amount">${quotePrice(row)}</div></div>${detailRows([['Business',state.business?.name||'Mughal Interior'],['Party',party(row.party_id)?.name],['Location',row.location],['Quote date',date(row.quote_date)],['Project start',date(row.start_date)],['End date',date(row.expected_end_date)],['No. of days',String(row.days_to_complete??'Not set')],['Project details',row.description],...prices,['Payment terms',row.payment_terms],['Other details',row.notes],['Status',row.status]])}</article>`;}
function viewQuote(id){const row=project(id);if(!row)return;const approved=row.status==='Approved';setupDetail('quote',row,{title:row.name,kicker:'QUOTE DETAILS',html:quoteDocument(row),actions:`<button class="button secondary block" data-detail-download="quote">Download quote PDF</button>${approved?'':`<button class="button primary block" data-approve-quote="${row.id}">Approve quote</button>`}`,deletable:!approved});}
function invoiceDocument(row){const job=invoiceProject(row);if(!job)return'';const metric=projectMetrics(job),changes=metric.entries.filter(item=>['scope_increase','scope_decrease'].includes(item.entry_type));return`<article class="detail-card pdf-document"><div class="detail-hero"><p>PROJECT INVOICE · ${esc(row.invoice_number)}</p><h3>${esc(job.name)}</h3><div class="detail-amount">${money(metric.revised)}</div></div>${detailRows([['Business',state.business?.name||'Mughal Interior'],['Party',party(job.party_id)?.name],['Location',job.location],['Invoice date',date(row.invoice_date)],['Original project scope',job.description],['Original approved amount',money(metric.original)]])}${changes.length?`<div class="scope-list"><h4>Scope additions and deletions</h4>${changes.map(item=>`<div class="scope-item"><div><b>${esc(item.description)}</b><small>${date(item.entry_date)} · ${item.entry_type==='scope_increase'?'Scope increase':'Scope decrease'}</small></div><strong class="${item.entry_type==='scope_decrease'?'negative':''}">${item.entry_type==='scope_decrease'?'-':'+'}${money(item.amount)}</strong></div>`).join('')}</div>`:''}${detailRows([['Total increase',money(metric.increase)],['Total decrease',`− ${money(metric.decrease)}`],['Revised invoice amount',money(metric.revised)]])}</article>`;}
function viewInvoice(id){const row=state.invoices.find(item=>item.id===id);if(!row)return;setupDetail('invoice',row,{title:row.invoice_number,kicker:'INVOICE DETAILS',html:invoiceDocument(row),actions:'<button class="button primary block" data-detail-download="invoice">Download invoice PDF</button>',editable:false});}

async function downloadCurrent(type,button){const node=$('#detailBody .pdf-document');if(!node)return;if(typeof html2pdf==='undefined')throw new Error('PDF download is unavailable. Refresh with an internet connection.');const row=type==='quote'?project(state.detail.id):state.invoices.find(item=>item.id===state.detail.id),number=type==='quote'?row.project_number:row.invoice_number;await working('Preparing your PDF…',button,()=>html2pdf().set({margin:[8,8,8,8],filename:`${type}-${safeName(number)}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#ffffff'},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy']}}).from(node).save());toast('PDF downloaded.');}
function openApproval(id){const row=project(id),choices=[];if(Number(row.price_with_material)>0)choices.push(['with_material','With material',row.price_with_material]);if(Number(row.price_without_material)>0)choices.push(['without_material','Without material',row.price_without_material]);if(!choices.length){toast('Add a quotation amount before approval.');return;}state.detail={type:'quote',id};$('#approvalChoices').innerHTML=choices.map((choice,index)=>`<label class="approve-choice"><input type="radio" name="approvalType" value="${choice[0]}" ${index===0?'checked':''}><span><b>${choice[1]}</b><small>${money(choice[2])}</small></span></label>`).join('');closeSheets();openSheet('#approvalSheet');}
function openScope(){const approved=state.projects.filter(row=>row.status==='Approved'&&state.invoices.some(invoice=>invoice.project_id===row.id));if(!approved.length){toast('No approved project invoice is available.');return;}$('#scopeForm').reset();$('#scopeProject').innerHTML=approved.map(row=>`<option value="${row.id}">${esc(projectLabel(row))}</option>`).join('');$('#scopeDate').value=today();openSheet('#scopeSheet');}

$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const error=$('#loginError');error.classList.add('hidden');try{await working('Signing you in…',event.submitter,async()=>{await store.signIn($('#loginEmail').value,$('#loginPassword').value);await boot();});}catch(err){error.textContent=err.message;error.classList.remove('hidden');}});
$('#partyForm').addEventListener('submit',async event=>{event.preventDefault();const existing=state.parties.find(row=>row.id===$('#partyId').value),row={id:existing?.id||$('#partyId').value,name:$('#partyName').value.trim(),phone:$('#partyPhone').value.trim()||null,party_type:existing?.party_type||'Individual',address:$('#partyAddress').value.trim()||null,notes:existing?.notes||null,created_at:existing?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};try{await working(existing?'Updating party…':'Saving party…',event.submitter,async()=>{const saved=await store.save('parties',row,Boolean(existing));upsert(state.parties,saved);closeSheets();render();toast(existing?'Party updated.':'Party added.');});}catch{}});
$('#projectForm').addEventListener('submit',async event=>{event.preventDefault();const selectedParty=resolveParty($('#projectPartySearch').value);if(!selectedParty){toast('Select a party from the search suggestions.');return;}const existing=project($('#projectId').value),row=existing?{id:existing.id,name:$('#projectName').value.trim(),party_id:selectedParty.id,location:$('#projectLocation').value.trim()||null,updated_at:new Date().toISOString()}:{id:$('#projectId').value,party_id:selectedParty.id,project_number:`MIP-${new Date().getFullYear()}-${String($('#projectId').value).replaceAll('-','').slice(0,8).toUpperCase()}`,name:$('#projectName').value.trim(),location:$('#projectLocation').value.trim()||null,description:null,contract_type:'with_material',original_contract_amount:0,status:'Pending',quote_date:today(),pricing_mode:'with_material',payment_terms:null,notes:null,quote_created:false,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};try{await working(existing?'Updating project…':'Saving project…',event.submitter,async()=>{const saved=await store.save('projects',row,Boolean(existing));upsert(state.projects,saved);closeSheets();render();toast(existing?'Project updated.':'Project added.');});}catch{}});
$('#quoteForm').addEventListener('submit',async event=>{event.preventDefault();const selected=project($('#quoteProjectId').value)||resolveProject($('#quoteProjectSearch').value);if(!selected){toast('Select a project from the search suggestions.');return;}const withMaterial=$('#quoteWithMaterial').value===''?null:Number($('#quoteWithMaterial').value),withoutMaterial=$('#quoteWithoutMaterial').value===''?null:Number($('#quoteWithoutMaterial').value);if(!(withMaterial>0)&&!(withoutMaterial>0)){toast('Enter at least one quotation amount.');return;}const mode=$('#quoteShowBoth').checked?'both':withMaterial>0?'with_material':'without_material',row={id:selected.id,description:$('#quoteDetails').value.trim(),quote_date:$('#quoteDate').value,start_date:$('#quoteStart').value||null,expected_end_date:$('#quoteEnd').value||null,days_to_complete:$('#quoteDays').value===''?null:Number($('#quoteDays').value),pricing_mode:mode,price_with_material:withMaterial,price_without_material:withoutMaterial,payment_terms:$('#quotePaymentTerms').value.trim()||null,notes:$('#quoteNotes').value.trim()||null,status:selected.status==='Approved'?'Approved':'Pending',quote_created:true,updated_at:new Date().toISOString()};const modeAfter=event.submitter?.dataset.submitMode;try{await working(modeAfter==='download'?'Saving quote and preparing PDF…':'Saving quote…',event.submitter,async()=>{const saved=await store.save('projects',row,true);upsert(state.projects,saved);closeSheets();render();viewQuote(saved.id);toast('Quote saved.');if(modeAfter==='download')await downloadCurrent('quote',$('[data-detail-download="quote"]'));});}catch{}});
$('#approvalForm').addEventListener('submit',async event=>{event.preventDefault();const row=project(state.detail?.id),type=$('input[name="approvalType"]:checked')?.value;if(!row||!type)return;const amount=Number(type==='with_material'?row.price_with_material:row.price_without_material);try{await working('Approving quote and creating invoice…',event.submitter,async()=>{const saved=await store.save('projects',{id:row.id,status:'Approved',contract_type:type,original_contract_amount:amount,updated_at:new Date().toISOString()},true);upsert(state.projects,saved);let invoice=state.invoices.find(item=>item.project_id===row.id);if(!invoice){invoice=await store.save('invoices',{id:uid(),project_id:row.id,walk_in_order_id:null,invoice_number:`MII-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,invoice_date:today(),due_date:null,amount,notes:null,status:'Draft',created_at:new Date().toISOString(),updated_at:new Date().toISOString()},false);upsert(state.invoices,invoice);}closeSheets();render();viewQuote(row.id);toast('Quote approved and invoice created.');});}catch{}});
$('#scopeForm').addEventListener('submit',async event=>{event.preventDefault();const row={id:uid(),project_id:$('#scopeProject').value,entry_type:$('#scopeType').value,entry_date:$('#scopeDate').value,description:$('#scopeDescription').value.trim(),amount:Number($('#scopeAmount').value),notes:null,created_at:new Date().toISOString()};try{await working('Updating invoice scope…',event.submitter,async()=>{const saved=await store.save('project_entries',row,false);upsert(state.entries,saved);closeSheets();render();const invoice=state.invoices.find(item=>item.project_id===row.project_id);if(invoice)viewInvoice(invoice.id);toast('Scope change saved. Invoice total updated.');});}catch{}});

async function deleteDetail(button){const {type,id}=state.detail||{};if(!type)return;const messages={party:'Delete this party? This cannot be undone.',project:'Delete this project? This cannot be undone.',quote:'Delete this quote? The project record will remain.',invoice:'Delete this invoice? The quote will return to Pending.'};if(!confirm(messages[type]))return;try{await working(`Deleting ${type}…`,button,async()=>{if(type==='party'){await store.remove('parties',id);state.parties=state.parties.filter(row=>row.id!==id);}if(type==='project'){const row=project(id);if(row.quote_created||state.entries.some(entry=>entry.project_id===id)||state.invoices.some(invoice=>invoice.project_id===id))throw new Error('Delete its quote, invoice and project activity before deleting this project.');await store.remove('projects',id);state.projects=state.projects.filter(row=>row.id!==id);}if(type==='quote'){const row=project(id);if(row.status==='Approved')throw new Error('Delete the invoice first before deleting an approved quote.');const saved=await store.save('projects',{id,description:null,start_date:null,expected_end_date:null,days_to_complete:null,price_with_material:null,price_without_material:null,payment_terms:null,notes:null,pricing_mode:'with_material',quote_created:false,status:'Pending',updated_at:new Date().toISOString()},true);upsert(state.projects,saved);}if(type==='invoice'){const invoice=state.invoices.find(row=>row.id===id);await store.remove('invoices',id);state.invoices=state.invoices.filter(row=>row.id!==id);const job=project(invoice.project_id);if(job){const saved=await store.save('projects',{id:job.id,status:'Pending',original_contract_amount:0,updated_at:new Date().toISOString()},true);upsert(state.projects,saved);}}store.persist();closeSheets();render();toast(`${type[0].toUpperCase()+type.slice(1)} deleted.`);});}catch{}}

document.addEventListener('click',async event=>{const routeButton=event.target.closest('[data-route]');if(routeButton)route(routeButton.dataset.route);const tabButton=event.target.closest('[data-tab]');if(tabButton)tab(tabButton.dataset.tab);if(event.target.closest('[data-close]')||event.target.id==='backdrop')closeSheets();const action=event.target.closest('[data-action]')?.dataset.action;if(action==='add-party')openParty();if(action==='add-project')openProject();if(action==='add-quote')openQuote();if(action==='scope-change')openScope();const projectAction=event.target.closest('[data-project-action]');if(projectAction){const names={receipt:'Receive Payment',labour:'Assign Labour',material:'Assign Material',expense:'Charge Expenses'};$('#comingTitle').textContent=names[projectAction.dataset.projectAction];openSheet('#comingSheet');}const viewPartyButton=event.target.closest('[data-view-party]');if(viewPartyButton)viewParty(viewPartyButton.dataset.viewParty);const viewProjectButton=event.target.closest('[data-view-project]');if(viewProjectButton)viewProject(viewProjectButton.dataset.viewProject);const viewQuoteButton=event.target.closest('[data-view-quote]');if(viewQuoteButton)viewQuote(viewQuoteButton.dataset.viewQuote);const viewInvoiceButton=event.target.closest('[data-view-invoice]');if(viewInvoiceButton)viewInvoice(viewInvoiceButton.dataset.viewInvoice);const approve=event.target.closest('[data-approve-quote]');if(approve)openApproval(approve.dataset.approveQuote);const download=event.target.closest('[data-detail-download]');if(download)try{await downloadCurrent(download.dataset.detailDownload,download);}catch{}const listDownload=event.target.closest('[data-download-invoice]');if(listDownload){viewInvoice(listDownload.dataset.downloadInvoice);try{await downloadCurrent('invoice',$('[data-detail-download="invoice"]'));}catch{}}const listDelete=event.target.closest('[data-delete-invoice]');if(listDelete){state.detail={type:'invoice',id:listDelete.dataset.deleteInvoice};await deleteDetail(listDelete);}if(event.target.id==='detailDelete')await deleteDetail(event.target);if(event.target.id==='detailEdit'){const detail=state.detail;closeSheets();if(detail.type==='party')openParty(detail.id);if(detail.type==='project')openProject(detail.id);if(detail.type==='quote')openQuote(detail.id);}});
$('#partySearch').addEventListener('input',renderParties);$('#projectSearch').addEventListener('input',renderProjects);$('#quoteSearch').addEventListener('input',renderQuotes);$('#invoiceSearch').addEventListener('input',renderInvoices);$('#quoteStart').addEventListener('change',setQuoteDays);$('#quoteEnd').addEventListener('change',setQuoteDays);$('#logoutBtn').addEventListener('click',()=>{if(confirm('Sign out of Mughal Interior Accounts?'))logout();});
function logout(show=true){localStorage.removeItem('mi_mobile_session');state.token=null;state.userId=null;$('#app').classList.add('hidden');$('#loginScreen').classList.remove('hidden');if(show)toast('Signed out.');}
async function boot(){if(cloud&&!state.token){const saved=JSON.parse(localStorage.getItem('mi_mobile_session')||'null');if(!saved){$('#loginScreen').classList.remove('hidden');return;}state.token=saved.token;state.userId=saved.userId;}try{await store.load();$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');render();tab('projectsHub');}catch(error){if(cloud){logout(false);$('#loginError').textContent=error.message;$('#loginError').classList.remove('hidden');}else toast(error.message);}}
boot();
