const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const cfg = window.MUGHAL_CONFIG || {};
const isCloud = Boolean(cfg.supabaseUrl && cfg.supabasePublishableKey);
const state = { parties: [], quotes: [], projects: [], projectEntries: [], businessId: null, userId: null, token: null, step: 1, activeQuote: null, activeProject: null };
const today = () => new Date().toISOString().slice(0, 10);
const plusDays = n => { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().slice(0, 10); };
const money = n => `Rs. ${Number(n || 0).toLocaleString('en-PK')}`;
const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const prettyDate = v => v ? new Date(`${v}T00:00:00`).toLocaleDateString('en-PK',{day:'numeric',month:'short',year:'numeric'}) : 'Not set';
const durationDays = (start,end) => start && end ? Math.max(0,Math.round((new Date(`${end}T00:00:00`)-new Date(`${start}T00:00:00`))/86400000)) : null;
const datePlus = (start,days) => { if(!start || days==='' || days===null) return ''; const d=new Date(`${start}T00:00:00`); d.setDate(d.getDate()+Number(days)); return d.toISOString().slice(0,10); };
const id = prefix => crypto.randomUUID?.() || `${prefix}${Date.now()}`;

const demo = {
  parties:[{id:'p1',name:'Ali Residence',phone:'0300 1234567',party_type:'Individual',address:'DHA Phase 6, Lahore',notes:''}],
  quotes:[{id:'q1',quote_number:'MIQ-2026-0001',party_id:'p1',project_title:'Complete residence woodwork',project_details:'Kitchen cabinets, wardrobes, TV wall and entrance console.',quote_date:today(),valid_until:plusDays(15),start_date:plusDays(20),end_date:plusDays(65),days_to_complete:45,pricing_mode:'with_material',price_with_material:1250000,price_without_material:null,payment_terms:'40% advance, 40% during work and 20% on completion.',notes:'Hardware by approved brands.',status:'Approved',created_at:new Date().toISOString()}],
  projects:[], entries:[]
};

class Store {
  constructor(){ this.base=(cfg.supabaseUrl||'').replace(/\/$/,''); this.key=cfg.supabasePublishableKey||''; }
  headers(extra={}){ return {'apikey':this.key,'Authorization':`Bearer ${state.token}`,'Content-Type':'application/json',...extra}; }
  async request(path,options={}){ const r=await fetch(`${this.base}${path}`,{...options,headers:this.headers(options.headers)}); if(r.status===401){logout(false);throw new Error('Your session expired. Please sign in again.')} if(!r.ok){const e=await r.text();throw new Error(e||'Could not save the record.')} return r.status===204?null:r.json(); }
  async signIn(email,password){ const r=await fetch(`${this.base}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:this.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error_description||data.msg||'Email or password is incorrect.');state.token=data.access_token;state.userId=data.user.id;localStorage.setItem('mi_session',JSON.stringify({token:state.token,userId:state.userId})); }
  async load(){
    if(!isCloud){state.parties=JSON.parse(localStorage.getItem('mi_parties')||'null')||demo.parties;state.quotes=JSON.parse(localStorage.getItem('mi_quotes')||'null')||demo.quotes;state.projects=JSON.parse(localStorage.getItem('mi_projects')||'null')||demo.projects;state.projectEntries=JSON.parse(localStorage.getItem('mi_project_entries')||'null')||demo.entries;return;}
    const membership=await this.request(`/rest/v1/business_members?select=business_id&user_id=eq.${state.userId}&limit=1`);if(!membership.length)throw new Error('This account has not been added to a business yet.');state.businessId=membership[0].business_id;
    [state.parties,state.quotes,state.projects,state.projectEntries]=await Promise.all([
      this.request(`/rest/v1/parties?select=*&business_id=eq.${state.businessId}&order=name.asc`),
      this.request(`/rest/v1/quotations?select=*&business_id=eq.${state.businessId}&order=created_at.desc`),
      this.request(`/rest/v1/projects?select=*&business_id=eq.${state.businessId}&order=created_at.desc`),
      this.request(`/rest/v1/project_entries?select=*&business_id=eq.${state.businessId}&order=entry_date.desc,created_at.desc`)
    ]);
  }
  async save(table,row,updating){
    if(!isCloud)return row;
    row.business_id=state.businessId;const path=updating?`/rest/v1/${table}?id=eq.${row.id}`:`/rest/v1/${table}`;const data=await this.request(path,{method:updating?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return data[0];
  }
}
const store=new Store();

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),2800)}
function openSheet(sel){$('#sheetBackdrop').classList.remove('hidden');$(sel).classList.remove('hidden');document.body.style.overflow='hidden'}
function closeSheets(){$('#sheetBackdrop').classList.add('hidden');$$('.sheet').forEach(x=>x.classList.add('hidden'));document.body.style.overflow=''}
function partyName(pid){return state.parties.find(p=>p.id===pid)?.name||'Unknown party'}
function quoteAmount(q){return q.pricing_mode==='without_material'?q.price_without_material:q.price_with_material}
function statusClass(s){return String(s||'draft').toLowerCase().replaceAll(' ','-')}
function bindDuration(startSel,endSel,daysSel){
  const calc=()=>{const n=durationDays($(startSel).value,$(endSel).value);$(daysSel).value=n===null?'':n};
  $(startSel).addEventListener('change',()=>{$(endSel).value?calc():($(daysSel).value!==''&&($(endSel).value=datePlus($(startSel).value,$(daysSel).value)))});
  $(endSel).addEventListener('change',calc);
  $(daysSel).addEventListener('input',()=>{if($(startSel).value&&$(daysSel).value!=='')$(endSel).value=datePlus($(startSel).value,$(daysSel).value)});
}

function projectMetrics(project){
  const rows=state.projectEntries.filter(e=>e.project_id===project.id);const sum=t=>rows.filter(e=>e.entry_type===t).reduce((a,e)=>a+Number(e.amount||0),0);
  const increase=sum('scope_increase'),decrease=sum('scope_decrease'),receipts=sum('receipt'),labour=sum('labour'),materials=sum('material'),expenses=sum('expense');
  const revised=Number(project.original_contract_amount||0)+increase-decrease,costs=labour+materials+expenses;
  return {rows,increase,decrease,receipts,labour,materials,expenses,revised,costs,balance:revised-receipts,profit:revised-costs};
}
function projectCard(p){const m=projectMetrics(p);return `<article class="item-card"><div><h3>${esc(p.name)}</h3><div class="meta"><span>${esc(p.project_number)}</span><span>${esc(partyName(p.party_id))}</span><span>${prettyDate(p.start_date)}</span></div></div><div class="item-actions"><div><div class="amount">${money(m.revised)}</div><span class="status ${statusClass(p.status)}">${esc(p.status)}</span></div><button class="mini-btn" data-view-project="${p.id}">View</button></div></article>`}
function quoteCard(q){const linked=state.projects.some(p=>p.source_quotation_id===q.id);return `<article class="item-card"><div><h3>${esc(q.project_title)}</h3><div class="meta"><span>${esc(q.quote_number)}</span><span>${esc(partyName(q.party_id))}</span><span>${prettyDate(q.quote_date)}</span>${linked?'<span>Project created</span>':''}</div></div><div class="item-actions"><div><div class="amount">${money(quoteAmount(q))}</div><span class="status ${statusClass(q.status)}">${esc(q.status)}</span></div><button class="mini-btn" data-view-quote="${q.id}">View</button></div></article>`}
function render(){
  if(!isCloud){localStorage.setItem('mi_parties',JSON.stringify(state.parties));localStorage.setItem('mi_quotes',JSON.stringify(state.quotes));localStorage.setItem('mi_projects',JSON.stringify(state.projects));localStorage.setItem('mi_project_entries',JSON.stringify(state.projectEntries));}
  $('#partyCount').textContent=state.parties.length;$('#openCount').textContent=state.quotes.filter(q=>['Draft','Sent'].includes(q.status)).length;$('#activeProjectCount').textContent=state.projects.filter(p=>['Planning','Active','On Hold'].includes(p.status)).length;$('#projectValue').textContent=money(state.projects.reduce((a,p)=>a+projectMetrics(p).revised,0));
  const recent=[...state.quotes].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,3);$('#recentQuotes').innerHTML=recent.length?recent.map(quoteCard).join(''):`<div class="empty"><b>No quotations yet</b><span>Create the first contract quotation.</span></div>`;
  renderParties();renderQuotes();renderProjects();fillPartySelects();
}
function renderParties(){const q=$('#partySearch').value.toLowerCase();const rows=state.parties.filter(p=>[p.name,p.phone,p.address].join(' ').toLowerCase().includes(q));$('#partyList').innerHTML=rows.length?rows.map(p=>`<article class="item-card"><div><h3>${esc(p.name)}</h3><div class="meta"><span>${esc(p.party_type)}</span>${p.phone?`<span>${esc(p.phone)}</span>`:''}${p.address?`<span>${esc(p.address)}</span>`:''}</div></div><div class="item-actions"><button class="mini-btn" data-edit-party="${p.id}">Edit</button><button class="btn soft" data-party-quote="${p.id}">New quote</button></div></article>`).join(''):`<div class="empty"><b>No parties found</b><span>Add a customer to begin.</span></div>`}
function renderQuotes(){const text=$('#quoteSearch').value.toLowerCase(),status=$('#statusFilter').value;const rows=state.quotes.filter(q=>(status==='all'||q.status===status)&&[q.quote_number,q.project_title,partyName(q.party_id)].join(' ').toLowerCase().includes(text));$('#quoteList').innerHTML=rows.length?rows.map(quoteCard).join(''):`<div class="empty"><b>No matching quotations</b><span>Change the filter or create a quotation.</span></div>`}
function renderProjects(){const text=$('#projectSearch').value.toLowerCase(),status=$('#projectStatusFilter').value;const rows=state.projects.filter(p=>(status==='all'||p.status===status)&&[p.project_number,p.name,partyName(p.party_id)].join(' ').toLowerCase().includes(text));$('#projectList').innerHTML=rows.length?rows.map(projectCard).join(''):`<div class="empty"><b>No matching projects</b><span>Create one manually or convert an approved quotation.</span></div>`}
function fillPartySelects(selectedQuote='',selectedProject=''){const opts=`<option value="">Select a party</option>`+state.parties.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#quoteParty').innerHTML=opts;$('#projectParty').innerHTML=opts;if(selectedQuote)$('#quoteParty').value=selectedQuote;if(selectedProject)$('#projectParty').value=selectedProject}
function navigate(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$$('.bottom-nav [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));scrollTo(0,0)}

function openParty(pid=''){const p=state.parties.find(x=>x.id===pid);$('#partyForm').reset();$('#partyId').value=p?.id||'';$('#partyName').value=p?.name||'';$('#partyPhone').value=p?.phone||'';$('#partyType').value=p?.party_type||'Individual';$('#partyAddress').value=p?.address||'';$('#partyNotes').value=p?.notes||'';$('#partySheetTitle').textContent=p?'Edit party':'Add party';openSheet('#partySheet')}
function setStep(n){state.step=n;$$('.step-panel').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===n));$$('#quoteSteps button').forEach((b,i)=>b.classList.toggle('active',i+1<=n));$('#quoteBack').classList.toggle('hidden',n===1);$('#quoteNext').classList.toggle('hidden',n===3);$('#quoteSave').classList.toggle('hidden',n!==3);if(n===3)renderReview()}
function updatePriceVisibility(){const mode=$('input[name="pricingMode"]:checked').value;$('#withMaterialWrap').classList.toggle('hidden',mode==='without_material');$('#withoutMaterialWrap').classList.toggle('hidden',mode==='with_material');$$('.choice').forEach(c=>c.classList.toggle('selected',$('input',c).checked))}
function openQuote(qid='',partyId=''){if(!state.parties.length){toast('Add a party before creating a quotation.');openParty();return}const q=state.quotes.find(x=>x.id===qid);$('#quoteForm').reset();$('#quoteId').value=q?.id||'';fillPartySelects(q?.party_id||partyId);$('#projectTitle').value=q?.project_title||'';$('#projectDetails').value=q?.project_details||'';$('#quoteDate').value=q?.quote_date||today();$('#validUntil').value=q?.valid_until||plusDays(15);$('#startDate').value=q?.start_date||'';$('#endDate').value=q?.end_date||'';$('#daysToComplete').value=q?.days_to_complete??durationDays(q?.start_date,q?.end_date)??'';const mode=q?.pricing_mode||'with_material';$(`input[name="pricingMode"][value="${mode}"]`).checked=true;$('#priceWithMaterial').value=q?.price_with_material||'';$('#priceWithoutMaterial').value=q?.price_without_material||'';$('#paymentTerms').value=q?.payment_terms||'';$('#quoteNotes').value=q?.notes||'';$('#quoteSheetTitle').textContent=q?'Edit quotation':'New quotation';updatePriceVisibility();setStep(1);closeSheets();openSheet('#quoteSheet')}
function quoteFromForm(){const existing=state.quotes.find(x=>x.id===$('#quoteId').value),mode=$('input[name="pricingMode"]:checked').value;return {id:existing?.id||id('q'),quote_number:existing?.quote_number||`MIQ-${new Date().getFullYear()}-${String(state.quotes.length+1).padStart(4,'0')}`,party_id:$('#quoteParty').value,project_title:$('#projectTitle').value.trim(),project_details:$('#projectDetails').value.trim(),quote_date:$('#quoteDate').value,valid_until:$('#validUntil').value||null,start_date:$('#startDate').value||null,end_date:$('#endDate').value||null,days_to_complete:$('#daysToComplete').value===''?null:Number($('#daysToComplete').value),pricing_mode:mode,price_with_material:mode==='without_material'?null:Number($('#priceWithMaterial').value||0),price_without_material:mode==='with_material'?null:Number($('#priceWithoutMaterial').value||0),payment_terms:$('#paymentTerms').value.trim(),notes:$('#quoteNotes').value.trim(),status:existing?.status||'Draft',created_at:existing?.created_at||new Date().toISOString()}}
function validStep(){if(state.step===1){for(const field of ['quoteParty','projectTitle','projectDetails','quoteDate'])if(!$(`#${field}`).value){$(`#${field}`).reportValidity();return false}}if(state.step===2){const mode=$('input[name="pricingMode"]:checked').value;if((mode==='with_material'||mode==='both')&&!Number($('#priceWithMaterial').value)){toast('Enter the price with material.');return false}if((mode==='without_material'||mode==='both')&&!Number($('#priceWithoutMaterial').value)){toast('Enter the price without material.');return false}}return true}
function renderReview(){const q=quoteFromForm(),days=q.days_to_complete??durationDays(q.start_date,q.end_date);const prices=q.pricing_mode==='both'?`${money(q.price_with_material)} with material<br>${money(q.price_without_material)} labour only`:money(quoteAmount(q));$('#quoteReview').innerHTML=`<div class="review-row"><span>Party</span><b>${esc(partyName(q.party_id))}</b></div><div class="review-row"><span>Work title</span><b>${esc(q.project_title)}</b></div><div class="review-row"><span>Project start</span><b>${prettyDate(q.start_date)}</b></div><div class="review-row"><span>Project completion</span><b>${prettyDate(q.end_date)}</b></div><div class="review-row"><span>Days to complete</span><b>${days??'Not set'}</b></div><div class="review-row"><span>Quoted price</span><b>${prices}</b></div>`}
function quotationDocument(q){const p=state.parties.find(x=>x.id===q.party_id)||{},days=q.days_to_complete??durationDays(q.start_date,q.end_date);const price=q.pricing_mode==='both'?`<div><small>WITH MATERIAL</small><b>${money(q.price_with_material)}</b></div><div><small>LABOUR ONLY</small><b>${money(q.price_without_material)}</b></div>`:`<div><small>${q.pricing_mode==='with_material'?'WITH MATERIAL':'LABOUR ONLY'}</small><b>${money(quoteAmount(q))}</b></div>`;return `<div class="doc-head"><div class="doc-brand"><img class="doc-logo" src="assets/mughal-logo.png?v=2" alt="Mughal Interior"><p>Crafted woodwork for homes and businesses</p></div><div class="doc-meta"><b>${esc(q.quote_number)}</b><p>Date: ${prettyDate(q.quote_date)}</p><p>Valid until: ${prettyDate(q.valid_until)}</p></div></div><div class="doc-title"><p class="eyebrow">CONTRACT QUOTATION</p><h1>${esc(q.project_title)}</h1></div><div class="doc-grid"><div class="doc-box"><small>PREPARED FOR</small><b>${esc(p.name||'')}</b><div>${esc(p.phone||'')}</div><div>${esc(p.address||'')}</div></div></div><div class="doc-grid schedule-grid"><div class="doc-box"><small>PROJECT START DATE</small><b>${prettyDate(q.start_date)}</b></div><div class="doc-box"><small>PROJECT COMPLETION DATE</small><b>${prettyDate(q.end_date)}</b></div><div class="doc-box"><small>DAYS TO COMPLETE</small><b>${days??'Not set'}</b></div></div><h3>Proposed scope of work</h3><div class="doc-details">${esc(q.project_details)}</div><div class="price-box">${price}</div><div class="doc-terms"><h3>Payment terms</h3><p>${esc(q.payment_terms||'Not specified')}</p>${q.notes?`<h3>Terms and notes</h3><p>${esc(q.notes)}</p>`:''}</div>`}
function viewQuote(qid){const q=state.quotes.find(x=>x.id===qid);if(!q)return;state.activeQuote=q;$('#quoteDocument').innerHTML=quotationDocument(q);$('#statusQuoteBtn').textContent=q.status==='Draft'?'Mark as sent':q.status==='Sent'?'Approve quotation':q.status==='Approved'?'Approved':'Return to draft';const converted=state.projects.some(p=>p.source_quotation_id===q.id);$('#convertProjectBtn').classList.toggle('hidden',q.status!=='Approved');$('#convertProjectBtn').disabled=converted;$('#convertProjectBtn').textContent=converted?'Project already created':'Convert to project';openSheet('#detailSheet')}

function openProject(projectId='',sourceQuoteId=''){if(!state.parties.length){toast('Add a party before creating a project.');return}const p=state.projects.find(x=>x.id===projectId),q=state.quotes.find(x=>x.id===sourceQuoteId);$('#projectForm').reset();$('#projectId').value=p?.id||'';$('#projectSourceQuote').value=p?.source_quotation_id||q?.id||'';fillPartySelects('',p?.party_id||q?.party_id||'');$('#projectName').value=p?.name||q?.project_title||'';$('#projectDescription').value=p?.description||q?.project_details||'';$('#projectStatus').value=p?.status||'Planning';$('#projectSheetTitle').textContent=p?'Edit project':q?'Create project from quotation':'New project';closeSheets();openSheet('#projectSheet')}
function projectFromForm(){const existing=state.projects.find(x=>x.id===$('#projectId').value),quote=state.quotes.find(x=>x.id===$('#projectSourceQuote').value),type=existing?.contract_type||(quote?.pricing_mode==='without_material'?'without_material':'with_material'),amount=existing?.original_contract_amount??(type==='without_material'?quote?.price_without_material:quote?.price_with_material)??0;return {id:existing?.id||id('pr'),project_number:existing?.project_number||`MIP-${new Date().getFullYear()}-${String(state.projects.length+1).padStart(4,'0')}`,party_id:$('#projectParty').value,source_quotation_id:quote?.id||null,name:$('#projectName').value.trim(),description:$('#projectDescription').value.trim(),contract_type:type,original_contract_amount:Number(amount),start_date:existing?.start_date||quote?.start_date||null,expected_end_date:existing?.expected_end_date||quote?.end_date||null,days_to_complete:existing?.days_to_complete??quote?.days_to_complete??durationDays(quote?.start_date,quote?.end_date),status:$('#projectStatus').value,created_at:existing?.created_at||new Date().toISOString()}}
function entryLabel(t){return {scope_increase:'Scope increase',scope_decrease:'Scope decrease',receipt:'Customer receipt',labour:'Labour cost',material:'Material cost',expense:'Other expense'}[t]||t}
function entryIcon(t){return {scope_increase:'+',scope_decrease:'−',receipt:'R',labour:'L',material:'M',expense:'E'}[t]||'•'}
function projectDocumentHtml(p){const m=projectMetrics(p),entries=[...m.rows].sort((a,b)=>String(b.entry_date).localeCompare(String(a.entry_date)));return `<div class="doc-head"><div class="doc-brand"><img class="doc-logo" src="assets/mughal-logo.png?v=2" alt="Mughal Interior"><p>Project financial and execution report</p></div><div class="doc-meta"><b>${esc(p.project_number)}</b><p>${esc(p.status)}</p></div></div><div class="doc-title"><p class="eyebrow">PROJECT REPORT</p><h1>${esc(p.name)}</h1><p>${esc(partyName(p.party_id))}</p></div><div class="doc-grid schedule-grid"><div class="doc-box"><small>PROJECT START DATE</small><b>${prettyDate(p.start_date)}</b></div><div class="doc-box"><small>PROJECT COMPLETION DATE</small><b>${prettyDate(p.expected_end_date)}</b></div><div class="doc-box"><small>DAYS TO COMPLETE</small><b>${p.days_to_complete??'Not set'}</b></div></div><div class="project-metrics"><div class="metric"><span>Original contract</span><b>${money(p.original_contract_amount)}</b></div><div class="metric"><span>Revised contract</span><b>${money(m.revised)}</b></div><div class="metric"><span>Receipts</span><b>${money(m.receipts)}</b></div><div class="metric warn"><span>Customer balance</span><b>${money(m.balance)}</b></div><div class="metric"><span>Labour</span><b>${money(m.labour)}</b></div><div class="metric"><span>Materials</span><b>${money(m.materials)}</b></div><div class="metric"><span>Other expenses</span><b>${money(m.expenses)}</b></div><div class="metric good"><span>Estimated profit</span><b>${money(m.profit)}</b></div></div>${p.description?`<h3>Confirmed scope</h3><div class="doc-details">${esc(p.description)}</div>`:''}<h3>Project activity</h3>${entries.length?`<table class="project-report-table"><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Amount</th></tr></thead><tbody>${entries.map(e=>`<tr><td>${prettyDate(e.entry_date)}</td><td>${esc(entryLabel(e.entry_type))}</td><td>${esc(e.description)}</td><td>${money(e.amount)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty"><b>No project activity yet</b></div>'}`}
function viewProject(projectId){const p=state.projects.find(x=>x.id===projectId);if(!p)return;state.activeProject=p;$('#projectDocument').innerHTML=projectDocumentHtml(p);openSheet('#projectDetailSheet')}
function openEntry(){if(!state.activeProject)return;$('#entryForm').reset();$('#entryProjectId').value=state.activeProject.id;$('#entryDate').value=today();closeSheets();openSheet('#entrySheet')}

async function boot(){if(isCloud){const session=JSON.parse(localStorage.getItem('mi_session')||'null');if(!session){$('#loginScreen').classList.remove('hidden');return}state.token=session.token;state.userId=session.userId}try{await store.load();$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');render();if(!isCloud)toast('Demo mode — connect Supabase to save online.')}catch(e){$('#loginScreen').classList.remove('hidden');$('#loginError').textContent=e.message;$('#loginError').classList.remove('hidden')}}
function logout(show=true){localStorage.removeItem('mi_session');state.token=null;state.userId=null;$('#app').classList.add('hidden');$('#loginScreen').classList.remove('hidden');if(show)toast('Signed out.')}

document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)navigate(nav.dataset.nav);const action=e.target.closest('[data-action]')?.dataset.action;if(action==='new-party')openParty();if(action==='new-quote')openQuote();if(action==='new-project')openProject();if(e.target.closest('[data-close]')||e.target.id==='sheetBackdrop')closeSheets();const ep=e.target.closest('[data-edit-party]');if(ep)openParty(ep.dataset.editParty);const pq=e.target.closest('[data-party-quote]');if(pq)openQuote('',pq.dataset.partyQuote);const vq=e.target.closest('[data-view-quote]');if(vq)viewQuote(vq.dataset.viewQuote);const vp=e.target.closest('[data-view-project]');if(vp)viewProject(vp.dataset.viewProject)});
$('#partySearch').addEventListener('input',renderParties);$('#quoteSearch').addEventListener('input',renderQuotes);$('#statusFilter').addEventListener('change',renderQuotes);$('#projectSearch').addEventListener('input',renderProjects);$('#projectStatusFilter').addEventListener('change',renderProjects);$$('input[name="pricingMode"]').forEach(x=>x.addEventListener('change',updatePriceVisibility));
bindDuration('#startDate','#endDate','#daysToComplete');
$('#partyForm').addEventListener('submit',async e=>{e.preventDefault();const existing=state.parties.find(x=>x.id===$('#partyId').value);const row={id:existing?.id||id('p'),name:$('#partyName').value.trim(),phone:$('#partyPhone').value.trim(),party_type:$('#partyType').value,address:$('#partyAddress').value.trim(),notes:$('#partyNotes').value.trim()};try{const saved=await store.save('parties',row,Boolean(existing));const i=state.parties.findIndex(x=>x.id===saved.id);i>=0?state.parties[i]=saved:state.parties.push(saved);closeSheets();render();toast(existing?'Party updated.':'Party added.')}catch(err){toast(err.message)}});
$('#quoteNext').addEventListener('click',()=>{if(validStep())setStep(state.step+1)});$('#quoteBack').addEventListener('click',()=>setStep(state.step-1));
$('#quoteForm').addEventListener('submit',async e=>{e.preventDefault();const row=quoteFromForm(),existing=state.quotes.some(x=>x.id===row.id);try{const saved=await store.save('quotations',row,existing);const i=state.quotes.findIndex(x=>x.id===saved.id);i>=0?state.quotes[i]=saved:state.quotes.unshift(saved);closeSheets();render();toast(existing?'Quotation updated.':'Quotation saved as draft.');viewQuote(saved.id)}catch(err){toast(err.message)}});
$('#editQuoteBtn').addEventListener('click',()=>openQuote(state.activeQuote?.id));
$('#statusQuoteBtn').addEventListener('click',async()=>{if(!state.activeQuote)return;const next=state.activeQuote.status==='Draft'?'Sent':state.activeQuote.status==='Sent'?'Approved':state.activeQuote.status==='Approved'?'Approved':'Draft';if(next===state.activeQuote.status){toast('This quotation is already approved.');return}const row={...state.activeQuote,status:next};try{const saved=await store.save('quotations',row,true);state.quotes[state.quotes.findIndex(x=>x.id===saved.id)]=saved;state.activeQuote=saved;render();viewQuote(saved.id);toast(`Quotation marked ${next.toLowerCase()}.`)}catch(err){toast(err.message)}});
$('#convertProjectBtn').addEventListener('click',()=>{if(state.activeQuote&&!state.projects.some(p=>p.source_quotation_id===state.activeQuote.id))openProject('',state.activeQuote.id)});
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();const row=projectFromForm(),existing=state.projects.some(x=>x.id===row.id);try{const saved=await store.save('projects',row,existing);const i=state.projects.findIndex(x=>x.id===saved.id);i>=0?state.projects[i]=saved:state.projects.unshift(saved);closeSheets();render();toast(existing?'Project updated.':'Project created.');viewProject(saved.id)}catch(err){toast(err.message)}});
$('#editProjectBtn').addEventListener('click',()=>openProject(state.activeProject?.id));$('#addProjectEntryBtn').addEventListener('click',openEntry);
$('#entryForm').addEventListener('submit',async e=>{e.preventDefault();const row={id:id('pe'),project_id:$('#entryProjectId').value,entry_type:$('#entryType').value,entry_date:$('#entryDate').value,description:$('#entryDescription').value.trim(),amount:Number($('#entryAmount').value),notes:$('#entryNotes').value.trim(),created_at:new Date().toISOString()};try{const saved=await store.save('project_entries',row,false);state.projectEntries.unshift(saved);closeSheets();render();toast('Project activity saved.');viewProject(row.project_id)}catch(err){toast(err.message)}});
function printSheet(sel){const sheet=$(sel);sheet.classList.add('printing');window.print();setTimeout(()=>sheet.classList.remove('printing'),400)}
$('#printQuoteBtn').addEventListener('click',()=>printSheet('#detailSheet'));$('#printProjectBtn').addEventListener('click',()=>printSheet('#projectDetailSheet'));
$('#profileBtn').addEventListener('click',()=>{if(isCloud&&confirm('Sign out of Mughal Interior Accounts?'))logout();else toast('Demo user · Supabase not connected')});
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').classList.add('hidden');try{await store.signIn($('#loginEmail').value,$('#loginPassword').value);await boot()}catch(err){$('#loginError').textContent=err.message;$('#loginError').classList.remove('hidden')}});
boot();
