// V10 information architecture: Quotes, Invoices, Purchases, Labour, Materials,
// Banking, Reports and a dedicated Settings master-data hub.
let quoteHubType='project',masterEditHandler=null;

function quoteHubProjectCard(project){
  const metric=projectMetrics(project),invoiced=state.invoices.some(i=>i.project_id===project.id);
  return `<article class="item-card project-card"><div><div class="project-card-number">${esc(project.project_number)}</div><h3>${esc(project.name)}</h3><div class="meta"><span>${esc(partyName(project.party_id))}</span><span>${prettyDate(project.quote_date)}</span><span>${projectPriceText(project)}</span></div></div><div class="item-actions"><span class="status ${statusClass(project.status)}">${esc(project.status)}</span><button class="mini-btn" data-view-project="${project.id}">View</button><button class="mini-btn" data-edit-project-card="${project.id}">Edit</button>${project.status==='Approved'&&!invoiced?`<button class="btn soft" data-convert-project-invoice="${project.id}">Convert to invoice</button>`:''}</div></article>`;
}

function quoteHubOrderCard(order){
  const invoiced=state.invoices.some(i=>i.walk_in_order_id===order.id),accepted=order.status!=='Pending'&&order.status!=='Cancelled';
  return `<article class="item-card project-card"><div><div class="project-card-number">${esc(order.order_number)}</div><h3>${esc(order.title)}</h3><div class="meta"><span>${esc(order.customer_name)}</span><span>${prettyDate(order.order_date)}</span><span>${money(order.amount)}</span></div></div><div class="item-actions"><span class="status ${statusClass(order.status)}">${esc(order.status)}</span><button class="mini-btn" data-view-walk-in="${order.id}">View</button><button class="mini-btn" data-edit-order-card="${order.id}">Edit</button>${order.status==='Pending'?`<button class="btn soft" data-approve-order-quote="${order.id}">Approve quote</button>`:accepted&&!invoiced?`<button class="btn soft" data-convert-order-invoice="${order.id}">Convert to invoice</button>`:''}</div></article>`;
}

function renderQuoteHub(){
  const list=$('#quoteHubList');if(!list)return;const search=$('#quoteHubSearch').value.toLowerCase(),status=$('#quoteHubStatus').value;
  $$('[data-quote-type]').forEach(button=>button.classList.toggle('active',button.dataset.quoteType===quoteHubType));
  if(quoteHubType==='project'){
    const rows=state.projects.filter(p=>(status==='all'||p.status===status)&&[p.project_number,p.name,partyName(p.party_id)].join(' ').toLowerCase().includes(search));
    list.innerHTML=rows.length?rows.map(quoteHubProjectCard).join(''):reportEmpty('No project quotes found','Add a project quote to begin.');
  }else{
    const rows=state.walkInOrders.filter(o=>(status==='all'||o.status===status)&&[o.order_number,o.title,o.customer_name,o.customer_phone].join(' ').toLowerCase().includes(search));
    list.innerHTML=rows.length?rows.map(quoteHubOrderCard).join(''):reportEmpty('No order quotes found','Add an order quote to begin.');
  }
}

function labourFinance(labourerId){
  const accrued=state.labourAssignments.filter(a=>a.labourer_id===labourerId).reduce((sum,a)=>sum+Number(a.amount??Number(a.days)*Number(a.daily_rate)),0),paid=state.payments.filter(p=>p.labourer_id===labourerId&&p.payment_type==='labour_payment').reduce((sum,p)=>sum+Number(p.amount||0),0),advance=state.payments.filter(p=>p.labourer_id===labourerId&&p.payment_type==='labour_advance').reduce((sum,p)=>sum+Number(p.amount||0),0);
  return {accrued,paid,advance,due:accrued-paid-advance};
}

function renderLabourFinance(){
  if(!$('#labourFinanceSummary'))return;const totals=state.labourers.reduce((t,l)=>{const f=labourFinance(l.id);t.accrued+=f.accrued;t.paid+=f.paid+f.advance;t.due+=f.due;return t},{accrued:0,paid:0,due:0});
  $('#labourFinanceSummary').innerHTML=`<article><span>Wages accrued</span><b>${money(totals.accrued)}</b></article><article><span>Paid + advances</span><b>${money(totals.paid)}</b></article><article><span>Net payable</span><b>${money(totals.due)}</b></article>`;
  $('#labourerList').innerHTML=state.labourers.length?state.labourers.map(l=>{const f=labourFinance(l.id);return `<article class="labourer-card"><div><b>${esc(l.name)}</b><small>${esc(l.mobile||'No mobile')}</small><div class="labour-balance"><em>Accrued ${money(f.accrued)}</em><em>Paid ${money(f.paid+f.advance)}</em><em class="due">Due ${money(f.due)}</em></div></div><div><strong>${money(l.daily_wage_rate)}/day</strong><button class="mini-btn" data-view-labourer="${l.id}">View</button></div></article>`}).join(''):reportEmpty('No labour persons','Add labour persons from Settings first.');
  const activity=[...state.labourAssignments.map(a=>({date:a.assignment_date,created_at:a.created_at,type:'accrual',labourer_id:a.labourer_id,text:`${qty(a.days)} days × ${money(a.daily_rate)}`,amount:Number(a.amount??Number(a.days)*Number(a.daily_rate))})),...state.payments.filter(p=>['labour_payment','labour_advance'].includes(p.payment_type)).map(p=>({date:p.payment_date,created_at:p.created_at,type:p.payment_type,labourer_id:p.labourer_id,text:paymentTypeLabel(p.payment_type),amount:Number(p.amount)}))].sort((a,b)=>String(b.date||b.created_at).localeCompare(String(a.date||a.created_at))).slice(0,50);
  $('#labourAssignmentList').innerHTML=activity.length?activity.map(a=>`<article class="operation-row"><span class="operation-icon labour">${a.type==='accrual'?'L':a.type==='labour_advance'?'A':'₨'}</span><div><b>${esc(labourerName(a.labourer_id))}</b><small>${esc(a.text)} · ${prettyDate(a.date)}</small></div><strong class="${a.type==='accrual'?'':'negative'}">${money(a.amount)}</strong></article>`).join(''):reportEmpty('No wage activity','Assign wages, record a payment or give an advance.');
}

function renderMasterLists(){
  if($('#settingsSupplierList'))$('#settingsSupplierList').innerHTML=state.suppliers.length?state.suppliers.map(s=>`<article class="item-card"><div><h3>${esc(s.name)}</h3><div class="meta">${s.contact_name?`<span>${esc(s.contact_name)}</span>`:''}${s.phone?`<span>${esc(s.phone)}</span>`:''}${s.address?`<span>${esc(s.address)}</span>`:''}</div></div><div class="item-actions"><button class="mini-btn" data-view-supplier="${s.id}">View</button><button class="mini-btn" data-edit-supplier="${s.id}">Edit</button></div></article>`).join(''):reportEmpty('No suppliers','Add the shops and vendors you purchase from.');
  if($('#expenseCategoryList'))$('#expenseCategoryList').innerHTML=state.expenseCategories.length?state.expenseCategories.map(row=>`<article class="item-card"><div><h3>${esc(row.name)}</h3><div class="meta"><span>${esc(row.description||'No description')}</span></div></div><div class="item-actions"><button class="mini-btn" data-view-expense-category="${row.id}">View</button><button class="mini-btn" data-edit-expense-category="${row.id}">Edit</button></div></article>`).join(''):reportEmpty('No expense categories','Add your first reusable expense category.');
  if($('#serviceList'))$('#serviceList').innerHTML=state.services.length?state.services.map(row=>`<article class="item-card"><div><h3>${esc(row.name)}</h3><div class="meta"><span>${money(row.default_rate)}${row.unit?` / ${esc(row.unit)}`:''}</span><span>${esc(row.description||'No description')}</span></div></div><div class="item-actions"><button class="mini-btn" data-view-service="${row.id}">View</button><button class="mini-btn" data-edit-service="${row.id}">Edit</button></div></article>`).join(''):reportEmpty('No services','Add your first service.');
  if($('#settingsLabourList'))$('#settingsLabourList').innerHTML=state.labourers.length?state.labourers.map(l=>`<article class="item-card"><div><h3>${esc(l.name)}</h3><div class="meta"><span>${esc(l.cnic||'No CNIC')}</span><span>${esc(l.mobile||'No mobile')}</span><span>${money(l.daily_wage_rate)}/day</span></div></div><div class="item-actions"><button class="mini-btn" data-view-labourer="${l.id}">View</button><button class="mini-btn" data-edit-labourer="${l.id}">Edit</button></div></article>`).join(''):reportEmpty('No labour persons','Add a labour person and daily wage rate.');
  if($('#settingsBankAccountList'))$('#settingsBankAccountList').innerHTML=state.paymentAccounts.length?state.paymentAccounts.map(a=>`<article class="item-card"><div><h3>${esc(a.name)}</h3><div class="meta"><span>${esc(a.account_type)}</span>${a.bank_name?`<span>${esc(a.bank_name)}</span>`:''}${a.account_number?`<span>${esc(a.account_number)}</span>`:''}</div></div><div class="item-actions"><div class="amount">${money(paymentAccountBalance(a))}</div><button class="mini-btn" data-view-payment-account="${a.id}">View</button><button class="mini-btn" data-edit-payment-account="${a.id}">Edit</button></div></article>`).join(''):reportEmpty('No bank accounts','Add cash, bank or mobile-wallet accounts.');
}

function renderNewModules(){renderQuoteHub();renderLabourFinance();renderMasterLists()}

function showMasterDetail(title,rows,editHandler){$('#masterDetailTitle').textContent=title;$('#masterDetailBody').innerHTML=rows.map(([label,value])=>`<div class="review-row"><span>${esc(label)}</span><b>${esc(value||'Not entered')}</b></div>`).join('');masterEditHandler=editHandler;closeSheets();openSheet('#masterDetailSheet')}

function openExpenseCategory(rowId=''){const row=state.expenseCategories.find(x=>x.id===rowId);$('#expenseCategoryForm').reset();$('#expenseCategoryId').value=row?.id||'';$('#expenseCategoryName').value=row?.name||'';$('#expenseCategoryDescription').value=row?.description||'';$('#expenseCategorySheetTitle').textContent=row?'Edit expense':'Add expense';closeSheets();openSheet('#expenseCategorySheet')}
function openService(rowId=''){const row=state.services.find(x=>x.id===rowId);$('#serviceForm').reset();$('#serviceId').value=row?.id||'';$('#serviceName').value=row?.name||'';$('#serviceRate').value=row?.default_rate??0;$('#serviceUnit').value=row?.unit||'';$('#serviceDescription').value=row?.description||'';$('#serviceSheetTitle').textContent=row?'Edit service':'Add service';closeSheets();openSheet('#serviceSheet')}

function openScopePicker(type){const rows=state.projects.filter(p=>p.status==='Approved');if(!rows.length){toast('No approved project is available.');return}$('#scopePickerType').value=type;$('#scopePickerTitle').textContent=type==='scope_increase'?'Increase scope':'Decrease scope';$('#scopePickerProject').innerHTML=rows.map(p=>`<option value="${p.id}">${esc(p.name)} — ${esc(partyName(p.party_id))}</option>`).join('');closeSheets();openSheet('#scopePickerSheet')}

function openLabourPayment(type){if(!state.labourers.length){toast('Add a labour person in Settings first.');return}if(!state.paymentAccounts.some(a=>a.active)){toast('Add an active cash or bank account first.');return}$('#labourPaymentForm').reset();$('#labourPaymentType').value=type;$('#labourPaymentTitle').textContent=type==='labour_advance'?'Give labour advance':'Pay labour wages';$('#labourPaymentPerson').innerHTML=state.labourers.map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('');$('#labourPaymentAccount').innerHTML=state.paymentAccounts.filter(a=>a.active).map(a=>`<option value="${a.id}">${esc(a.name)} — ${money(paymentAccountBalance(a))}</option>`).join('');$('#labourPaymentDate').value=today();updateLabourPaymentBalance();closeSheets();openSheet('#labourPaymentSheet')}
function updateLabourPaymentBalance(){const f=labourFinance($('#labourPaymentPerson').value);$('#labourBalanceText').textContent=`Accrued: ${money(f.accrued)} · Paid/advance: ${money(f.paid+f.advance)} · Net payable: ${money(f.due)}`}

document.addEventListener('click',async event=>{
  const quoteType=event.target.closest('[data-quote-type]');if(quoteType){quoteHubType=quoteType.dataset.quoteType;renderQuoteHub()}
  const route=event.target.closest('[data-settings-route]')?.dataset.settingsRoute;if(route)navigate(route);
  const action=event.target.closest('[data-action]')?.dataset.action;if(action==='new-expense-category')openExpenseCategory();if(action==='new-service')openService();if(action==='scope-increase-from-list')openScopePicker('scope_increase');if(action==='scope-decrease-from-list')openScopePicker('scope_decrease');if(action==='labour-payment')openLabourPayment('labour_payment');if(action==='labour-advance')openLabourPayment('labour_advance');if(action==='bank-transfer')openPayment('transfer');
  const projectInvoice=event.target.closest('[data-convert-project-invoice]');if(projectInvoice)openInvoice('',projectInvoice.dataset.convertProjectInvoice);
  const orderInvoice=event.target.closest('[data-convert-order-invoice]');if(orderInvoice)openInvoice('','',orderInvoice.dataset.convertOrderInvoice);
  const approveOrder=event.target.closest('[data-approve-order-quote]');if(approveOrder){state.activeWalkInOrder=state.walkInOrders.find(o=>o.id===approveOrder.dataset.approveOrderQuote);if(state.activeWalkInOrder)await setWalkInOrderStatus('In Progress')}
  const editCategory=event.target.closest('[data-edit-expense-category]');if(editCategory)openExpenseCategory(editCategory.dataset.editExpenseCategory);const editService=event.target.closest('[data-edit-service]');if(editService)openService(editService.dataset.editService);const editAccount=event.target.closest('[data-edit-payment-account]');if(editAccount)openPaymentAccount(editAccount.dataset.editPaymentAccount);
  const viewParty=event.target.closest('[data-view-party]');if(viewParty){const p=state.parties.find(x=>x.id===viewParty.dataset.viewParty);showMasterDetail(p.name,[['Type',p.party_type],['Phone',p.phone],['Address',p.address],['Notes',p.notes]],()=>openParty(p.id))}
  const viewSupplier=event.target.closest('[data-view-supplier]');if(viewSupplier){const s=state.suppliers.find(x=>x.id===viewSupplier.dataset.viewSupplier);showMasterDetail(s.name,[['Contact',s.contact_name],['Phone',s.phone],['Address',s.address],['Notes',s.notes]],()=>openSupplier(s.id))}
  const viewCategory=event.target.closest('[data-view-expense-category]');if(viewCategory){const r=state.expenseCategories.find(x=>x.id===viewCategory.dataset.viewExpenseCategory);showMasterDetail(r.name,[['Description',r.description]],()=>openExpenseCategory(r.id))}
  const viewService=event.target.closest('[data-view-service]');if(viewService){const r=state.services.find(x=>x.id===viewService.dataset.viewService);showMasterDetail(r.name,[['Default rate',money(r.default_rate)],['Unit',r.unit],['Description',r.description]],()=>openService(r.id))}
  const viewLabour=event.target.closest('[data-view-labourer]');if(viewLabour){const l=state.labourers.find(x=>x.id===viewLabour.dataset.viewLabourer),f=labourFinance(l.id);showMasterDetail(l.name,[['CNIC',l.cnic],['Mobile',l.mobile],['Home address',l.home_address],['Daily wage',`${money(l.daily_wage_rate)}/day`],['Wages accrued',money(f.accrued)],['Paid + advances',money(f.paid+f.advance)],['Net payable',money(f.due)]],()=>openLabourer(l.id))}
});

$('#quoteHubSearch').addEventListener('input',renderQuoteHub);$('#quoteHubStatus').addEventListener('change',renderQuoteHub);$('#masterDetailEdit').addEventListener('click',()=>masterEditHandler?.());$('#labourPaymentPerson').addEventListener('change',updateLabourPaymentBalance);

$('#scopePickerForm').addEventListener('submit',event=>{event.preventDefault();state.activeProject=state.projects.find(p=>p.id===$('#scopePickerProject').value);const type=$('#scopePickerType').value;closeSheets();openEntry(type)});

$('#expenseCategoryForm').addEventListener('submit',async event=>{event.preventDefault();const existing=state.expenseCategories.find(x=>x.id===$('#expenseCategoryId').value),row={id:existing?.id||id('ec'),name:$('#expenseCategoryName').value.trim(),description:$('#expenseCategoryDescription').value.trim()||null,active:true,created_at:existing?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};try{const saved=await store.save('expense_categories',row,Boolean(existing)),index=state.expenseCategories.findIndex(x=>x.id===saved.id);index>=0?state.expenseCategories[index]=saved:state.expenseCategories.push(saved);closeSheets();render();navigate('expenseCategories');toast(existing?'Expense updated.':'Expense added.')}catch(error){toast(error.message)}});

$('#serviceForm').addEventListener('submit',async event=>{event.preventDefault();const existing=state.services.find(x=>x.id===$('#serviceId').value),row={id:existing?.id||id('sv'),name:$('#serviceName').value.trim(),description:$('#serviceDescription').value.trim()||null,default_rate:Number($('#serviceRate').value||0),unit:$('#serviceUnit').value.trim()||null,active:true,created_at:existing?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};try{const saved=await store.save('services',row,Boolean(existing)),index=state.services.findIndex(x=>x.id===saved.id);index>=0?state.services[index]=saved:state.services.push(saved);closeSheets();render();navigate('services');toast(existing?'Service updated.':'Service added.')}catch(error){toast(error.message)}});

$('#labourPaymentForm').addEventListener('submit',async event=>{event.preventDefault();const type=$('#labourPaymentType').value,labourer=state.labourers.find(l=>l.id===$('#labourPaymentPerson').value),row={id:id('pay'),payment_number:`MIT-${new Date().getFullYear()}-${String(state.payments.length+1).padStart(4,'0')}`,payment_type:type,payment_date:$('#labourPaymentDate').value,from_account_id:$('#labourPaymentAccount').value,to_account_id:null,party_id:null,supplier_id:null,project_id:null,walk_in_order_id:null,purchase_bill_id:null,invoice_id:null,labourer_id:labourer.id,description:type==='labour_advance'?`Advance to ${labourer.name}`:`Wage payment to ${labourer.name}`,amount:Number($('#labourPaymentAmount').value),reference:$('#labourPaymentReference').value.trim()||null,notes:$('#labourPaymentNotes').value.trim()||null,created_by:state.userId||'demo-user',created_at:new Date().toISOString()};try{const saved=await store.save('payments',row,false);state.payments.unshift(saved);if(isCloud)await store.load();closeSheets();render();navigate('labour');toast(type==='labour_advance'?'Labour advance recorded.':'Labour payment recorded.')}catch(error){toast(error.message)}});

renderNewModules();
