const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const cfg = window.MUGHAL_CONFIG || {};
const isCloud = Boolean(cfg.supabaseUrl && cfg.supabasePublishableKey);
const state = { parties: [], projects: [], projectEntries: [], invoices: [], businessId: null, userId: null, token: null, projectStep: 1, activeProject: null, activeInvoice: null };
const today = () => new Date().toISOString().slice(0, 10);
const plusDays = n => { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().slice(0, 10); };
const money = n => `Rs. ${Number(n || 0).toLocaleString('en-PK')}`;
const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const prettyDate = v => v ? new Date(`${v}T00:00:00`).toLocaleDateString('en-PK',{day:'numeric',month:'short',year:'numeric'}) : 'Not set';
const durationDays = (start,end) => start && end ? Math.max(0,Math.round((new Date(`${end}T00:00:00`)-new Date(`${start}T00:00:00`))/86400000)) : null;
const datePlus = (start,days) => { if(!start || days==='' || days===null) return ''; const d=new Date(`${start}T00:00:00`); d.setDate(d.getDate()+Number(days)); return d.toISOString().slice(0,10); };
const id = prefix => crypto.randomUUID?.() || `${prefix}${Date.now()}`;

const demo = {
  parties:[{id:'p1',name:'XYZ Traders',phone:'0300 1234567',party_type:'Business',address:'Lahore',notes:''}],
  projects:[{id:'pr1',project_number:'MIP-2026-0001',party_id:'p1',name:'Project A',description:'Kitchen cabinets, wardrobes and TV wall.',quote_date:today(),valid_until:plusDays(15),start_date:plusDays(20),expected_end_date:plusDays(65),days_to_complete:45,pricing_mode:'both',price_with_material:1250000,price_without_material:450000,contract_type:'with_material',original_contract_amount:1250000,payment_terms:'40% advance, 40% during work and 20% on completion.',notes:'Hardware by approved brands.',status:'Approved',created_at:new Date().toISOString()}],
  entries:[], invoices:[]
};

class Store {
  constructor(){this.base=(cfg.supabaseUrl||'').replace(/\/$/,'');this.key=cfg.supabasePublishableKey||''}
  headers(extra={}){return {'apikey':this.key,'Authorization':`Bearer ${state.token}`,'Content-Type':'application/json',...extra}}
  async request(path,options={}){const r=await fetch(`${this.base}${path}`,{...options,headers:this.headers(options.headers)});if(r.status===401){logout(false);throw new Error('Your session expired. Please sign in again.')}if(!r.ok){const e=await r.text();throw new Error(e||'Could not save the record.')}return r.status===204?null:r.json()}
  async signIn(email,password){const r=await fetch(`${this.base}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:this.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error_description||data.msg||'Email or password is incorrect.');state.token=data.access_token;state.userId=data.user.id;localStorage.setItem('mi_session',JSON.stringify({token:state.token,userId:state.userId}))}
  async load(){
    if(!isCloud){state.parties=JSON.parse(localStorage.getItem('mi_parties')||'null')||demo.parties;state.projects=JSON.parse(localStorage.getItem('mi_projects')||'null')||demo.projects;state.projectEntries=JSON.parse(localStorage.getItem('mi_project_entries')||'null')||demo.entries;state.invoices=JSON.parse(localStorage.getItem('mi_invoices')||'null')||demo.invoices;return}
    const membership=await this.request(`/rest/v1/business_members?select=business_id&user_id=eq.${state.userId}&limit=1`);if(!membership.length)throw new Error('This account has not been added to a business yet.');state.businessId=membership[0].business_id;
    [state.parties,state.projects,state.projectEntries,state.invoices]=await Promise.all([
      this.request(`/rest/v1/parties?select=*&business_id=eq.${state.businessId}&order=name.asc`),
      this.request(`/rest/v1/projects?select=*&business_id=eq.${state.businessId}&order=created_at.desc`),
      this.request(`/rest/v1/project_entries?select=*&business_id=eq.${state.businessId}&order=entry_date.desc,created_at.desc`),
      this.request(`/rest/v1/invoices?select=*&business_id=eq.${state.businessId}&order=created_at.desc`)
    ])
  }
  async save(table,row,updating){if(!isCloud)return row;row.business_id=state.businessId;const path=updating?`/rest/v1/${table}?id=eq.${row.id}`:`/rest/v1/${table}`;const data=await this.request(path,{method:updating?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return data[0]}
}
const store=new Store();

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),3000)}
function openSheet(sel){$('#sheetBackdrop').classList.remove('hidden');$(sel).classList.remove('hidden');document.body.style.overflow='hidden'}
function closeSheets(){$('#sheetBackdrop').classList.add('hidden');$$('.sheet').forEach(x=>x.classList.add('hidden'));document.body.style.overflow=''}
function partyName(pid){return state.parties.find(p=>p.id===pid)?.name||'Unknown party'}
function statusClass(s){return String(s||'pending').toLowerCase().replaceAll(' ','-')}
function selectedProjectAmount(p){return Number(p.contract_type==='without_material'?p.price_without_material:p.price_with_material)||Number(p.original_contract_amount||0)}
function projectMetrics(project){const rows=state.projectEntries.filter(e=>e.project_id===project.id),sum=t=>rows.filter(e=>e.entry_type===t).reduce((a,e)=>a+Number(e.amount||0),0);const increase=sum('scope_increase'),decrease=sum('scope_decrease'),receipts=sum('receipt'),labour=sum('labour'),materials=sum('material'),expenses=sum('expense'),original=selectedProjectAmount(project),revised=original+increase-decrease,costs=labour+materials+expenses;return {rows,increase,decrease,receipts,labour,materials,expenses,original,revised,costs,balance:revised-receipts,profit:revised-costs}}
function projectPriceText(p){if(p.pricing_mode==='both')return `${money(p.price_with_material)} / ${money(p.price_without_material)}`;return money(p.pricing_mode==='without_material'?p.price_without_material:p.price_with_material)}
function projectCard(p){const m=projectMetrics(p);return `<article class="item-card"><div><h3>${esc(p.name)}</h3><div class="meta"><span>${esc(p.project_number)}</span><span>${esc(partyName(p.party_id))}</span><span>${prettyDate(p.quote_date)}</span></div></div><div class="item-actions"><div><div class="amount">${p.status==='Approved'?money(m.revised):projectPriceText(p)}</div><span class="status ${statusClass(p.status)}">${esc(p.status)}</span></div><button class="mini-btn" data-view-project="${p.id}">View</button></div></article>`}
function invoiceCard(i){const p=state.projects.find(x=>x.id===i.project_id);return `<article class="item-card"><div><h3>${esc(i.invoice_number)}</h3><div class="meta"><span>${esc(p?.name||'Unknown project')}</span><span>${esc(partyName(p?.party_id))}</span><span>${prettyDate(i.invoice_date)}</span></div></div><div class="item-actions"><div><div class="amount">${money(i.amount)}</div><span class="status ${statusClass(i.status)}">${esc(i.status)}</span></div><button class="mini-btn" data-view-invoice="${i.id}">View</button></div></article>`}

function persistLocal(){if(isCloud)return;localStorage.setItem('mi_parties',JSON.stringify(state.parties));localStorage.setItem('mi_projects',JSON.stringify(state.projects));localStorage.setItem('mi_project_entries',JSON.stringify(state.projectEntries));localStorage.setItem('mi_invoices',JSON.stringify(state.invoices))}
function render(){persistLocal();$('#partyCount').textContent=state.parties.length;$('#pendingProjectCount').textContent=state.projects.filter(p=>p.status==='Pending').length;$('#invoiceCount').textContent=state.invoices.length;$('#projectValue').textContent=money(state.projects.filter(p=>p.status==='Approved').reduce((a,p)=>a+projectMetrics(p).revised,0));const recent=[...state.projects].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,3);$('#recentProjects').innerHTML=recent.length?recent.map(projectCard).join(''):`<div class="empty"><b>No projects yet</b><span>Create a project quotation to begin.</span></div>`;renderParties();renderProjects();renderInvoices();fillPartySelect()}
function renderParties(){const q=$('#partySearch').value.toLowerCase(),rows=state.parties.filter(p=>[p.name,p.phone,p.address].join(' ').toLowerCase().includes(q));$('#partyList').innerHTML=rows.length?rows.map(p=>`<article class="item-card"><div><h3>${esc(p.name)}</h3><div class="meta"><span>${esc(p.party_type)}</span>${p.phone?`<span>${esc(p.phone)}</span>`:''}${p.address?`<span>${esc(p.address)}</span>`:''}</div></div><div class="item-actions"><button class="mini-btn" data-edit-party="${p.id}">Edit</button><button class="btn soft" data-party-project="${p.id}">New project</button></div></article>`).join(''):`<div class="empty"><b>No parties found</b><span>Add a customer to begin.</span></div>`}
function renderProjects(){const text=$('#projectSearch').value.toLowerCase(),status=$('#projectStatusFilter').value,rows=state.projects.filter(p=>(status==='all'||p.status===status)&&[p.project_number,p.name,partyName(p.party_id)].join(' ').toLowerCase().includes(text));$('#projectList').innerHTML=rows.length?rows.map(projectCard).join(''):`<div class="empty"><b>No matching projects</b><span>Change the filter or add a project.</span></div>`}
function renderInvoices(){const text=$('#invoiceSearch').value.toLowerCase(),status=$('#invoiceStatusFilter').value,rows=state.invoices.filter(i=>{const p=state.projects.find(x=>x.id===i.project_id);return(status==='all'||i.status===status)&&[i.invoice_number,p?.name,partyName(p?.party_id)].join(' ').toLowerCase().includes(text)});$('#invoiceList').innerHTML=rows.length?rows.map(invoiceCard).join(''):`<div class="empty"><b>No matching invoices</b><span>Approve a project, then generate its invoice.</span></div>`}
function fillPartySelect(selected=''){const opts=`<option value="">Select a party</option>`+state.parties.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#projectParty').innerHTML=opts;if(selected)$('#projectParty').value=selected}
function navigate(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$$('.bottom-nav [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));scrollTo(0,0)}

function bindDuration(startSel,endSel,daysSel){const calc=()=>{const n=durationDays($(startSel).value,$(endSel).value);$(daysSel).value=n===null?'':n};$(startSel).addEventListener('change',()=>{$(endSel).value?calc():($(daysSel).value!==''&&($(endSel).value=datePlus($(startSel).value,$(daysSel).value)))});$(endSel).addEventListener('change',calc);$(daysSel).addEventListener('input',()=>{if($(startSel).value&&$(daysSel).value!=='')$(endSel).value=datePlus($(startSel).value,$(daysSel).value)})}
function openParty(pid=''){const p=state.parties.find(x=>x.id===pid);$('#partyForm').reset();$('#partyId').value=p?.id||'';$('#partyName').value=p?.name||'';$('#partyPhone').value=p?.phone||'';$('#partyType').value=p?.party_type||'Individual';$('#partyAddress').value=p?.address||'';$('#partyNotes').value=p?.notes||'';$('#partySheetTitle').textContent=p?'Edit party':'Add party';closeSheets();openSheet('#partySheet')}

function setProjectStep(n){state.projectStep=n;$$('[data-project-step]').forEach(x=>x.classList.toggle('active',Number(x.dataset.projectStep)===n));$$('#projectSteps button').forEach((b,i)=>b.classList.toggle('active',i+1<=n));$('#projectBack').classList.toggle('hidden',n===1);$('#projectNext').classList.toggle('hidden',n===3);$('#projectSave').classList.toggle('hidden',n!==3);if(n===3)renderProjectReview()}
function updateProjectPricing(){const mode=$('input[name="projectPricingMode"]:checked').value;$('#projectWithMaterialWrap').classList.toggle('hidden',mode==='without_material');$('#projectWithoutMaterialWrap').classList.toggle('hidden',mode==='with_material');$('#approvedOptionWrap').classList.toggle('hidden',mode!=='both');$$('#projectSheet .choice').forEach(c=>c.classList.toggle('selected',$('input',c).checked));if(mode!=='both')$('#projectContractType').value=mode}
function openProject(projectId='',partyId=''){if(!state.parties.length){toast('Add a party before creating a project.');openParty();return}const p=state.projects.find(x=>x.id===projectId),hasInvoice=p&&state.invoices.some(i=>i.project_id===p.id);$('#projectForm').reset();$('#projectId').value=p?.id||'';fillPartySelect(p?.party_id||partyId);$('#projectStatus').value=p?.status||'Pending';$('#projectStatus').disabled=Boolean(hasInvoice);$('#projectName').value=p?.name||'';$('#projectDescription').value=p?.description||'';$('#projectQuoteDate').value=p?.quote_date||today();$('#projectValidUntil').value=p?.valid_until||plusDays(15);$('#projectStart').value=p?.start_date||'';$('#projectEnd').value=p?.expected_end_date||'';$('#projectDays').value=p?.days_to_complete??durationDays(p?.start_date,p?.expected_end_date)??'';const mode=p?.pricing_mode||'with_material';$(`input[name="projectPricingMode"][value="${mode}"]`).checked=true;$('#projectPriceWithMaterial').value=p?.price_with_material??(p?.contract_type==='with_material'?p?.original_contract_amount:'')??'';$('#projectPriceWithoutMaterial').value=p?.price_without_material??(p?.contract_type==='without_material'?p?.original_contract_amount:'')??'';$('#projectContractType').value=p?.contract_type||'with_material';$('#projectPaymentTerms').value=p?.payment_terms||'';$('#projectNotes').value=p?.notes||'';$('#projectSheetTitle').textContent=p?'Edit project':'New project';updateProjectPricing();setProjectStep(1);closeSheets();openSheet('#projectSheet')}
function projectFromForm(){const existing=state.projects.find(x=>x.id===$('#projectId').value),mode=$('input[name="projectPricingMode"]:checked').value,type=mode==='both'?$('#projectContractType').value:mode,withPrice=mode==='without_material'?null:Number($('#projectPriceWithMaterial').value||0),withoutPrice=mode==='with_material'?null:Number($('#projectPriceWithoutMaterial').value||0),amount=type==='without_material'?withoutPrice:withPrice;return {id:existing?.id||id('pr'),project_number:existing?.project_number||`MIP-${new Date().getFullYear()}-${String(state.projects.length+1).padStart(4,'0')}`,party_id:$('#projectParty').value,source_quotation_id:existing?.source_quotation_id||null,name:$('#projectName').value.trim(),description:$('#projectDescription').value.trim(),quote_date:$('#projectQuoteDate').value,valid_until:$('#projectValidUntil').value||null,start_date:$('#projectStart').value||null,expected_end_date:$('#projectEnd').value||null,days_to_complete:$('#projectDays').value===''?null:Number($('#projectDays').value),pricing_mode:mode,price_with_material:withPrice,price_without_material:withoutPrice,contract_type:type,original_contract_amount:Number(amount||0),payment_terms:$('#projectPaymentTerms').value.trim(),notes:$('#projectNotes').value.trim(),status:$('#projectStatus').value,created_at:existing?.created_at||new Date().toISOString()}}
function validProjectStep(){if(state.projectStep===1){for(const field of ['projectParty','projectName','projectDescription','projectQuoteDate'])if(!$(`#${field}`).value){$(`#${field}`).reportValidity();return false}}if(state.projectStep===2){const mode=$('input[name="projectPricingMode"]:checked').value;if((mode==='with_material'||mode==='both')&&!Number($('#projectPriceWithMaterial').value)){toast('Enter the amount with material.');return false}if((mode==='without_material'||mode==='both')&&!Number($('#projectPriceWithoutMaterial').value)){toast('Enter the amount without material.');return false}}return true}
function renderProjectReview(){const p=projectFromForm(),days=p.days_to_complete??durationDays(p.start_date,p.expected_end_date);$('#projectReview').innerHTML=`<div class="review-row"><span>Party</span><b>${esc(partyName(p.party_id))}</b></div><div class="review-row"><span>Project</span><b>${esc(p.name)}</b></div><div class="review-row"><span>Status</span><b>${esc(p.status)}</b></div><div class="review-row"><span>Start date</span><b>${prettyDate(p.start_date)}</b></div><div class="review-row"><span>Completion date</span><b>${prettyDate(p.expected_end_date)}</b></div><div class="review-row"><span>Days to complete</span><b>${days??'Not set'}</b></div><div class="review-row"><span>Quotation</span><b>${projectPriceText(p)}</b></div>`}
function priceBoxes(p){if(p.pricing_mode==='both')return `<div><small>WITH MATERIAL</small><b>${money(p.price_with_material)}</b></div><div><small>LABOUR ONLY</small><b>${money(p.price_without_material)}</b></div>`;return `<div><small>${p.pricing_mode==='with_material'?'WITH MATERIAL':'LABOUR ONLY'}</small><b>${money(p.pricing_mode==='with_material'?p.price_with_material:p.price_without_material)}</b></div>`}
function entryLabel(t){return {scope_increase:'Scope increase',scope_decrease:'Scope decrease',receipt:'Customer receipt',labour:'Labour cost',material:'Material cost',expense:'Other expense'}[t]||t}
function projectDocumentHtml(p){const party=state.parties.find(x=>x.id===p.party_id)||{},m=projectMetrics(p),days=p.days_to_complete??durationDays(p.start_date,p.expected_end_date),changes=m.rows.filter(e=>['scope_increase','scope_decrease'].includes(e.entry_type)).sort((a,b)=>String(a.entry_date).localeCompare(String(b.entry_date)));return `<div class="doc-head"><div class="doc-brand"><img class="doc-logo" src="assets/mughal-logo.png" alt="Mughal Interior"><p>Crafted woodwork for homes and businesses</p></div><div class="doc-meta"><b>${esc(p.project_number)}</b><p>Quotation date: ${prettyDate(p.quote_date)}</p><p>Valid until: ${prettyDate(p.valid_until)}</p></div></div><div class="doc-title"><p class="eyebrow">PROJECT QUOTATION</p><h1>${esc(p.name)}</h1></div><div class="project-status-strip"><span>PROJECT STATUS</span><b class="status ${statusClass(p.status)}">${esc(p.status)}</b></div><div class="doc-grid"><div class="doc-box"><small>PREPARED FOR</small><b>${esc(party.name||'')}</b><div>${esc(party.phone||'')}</div><div>${esc(party.address||'')}</div></div></div><div class="doc-grid schedule-grid"><div class="doc-box"><small>PROJECT START DATE</small><b>${prettyDate(p.start_date)}</b></div><div class="doc-box"><small>PROJECT COMPLETION DATE</small><b>${prettyDate(p.expected_end_date)}</b></div><div class="doc-box"><small>DAYS TO COMPLETE</small><b>${days??'Not set'}</b></div></div><h3>Proposed scope of work</h3><div class="doc-details">${esc(p.description)}</div><div class="price-box">${priceBoxes(p)}</div>${p.status==='Approved'?`<div class="scope-summary"><div class="metric"><span>Approved amount</span><b>${money(m.original)}</b></div><div class="metric good"><span>Scope added</span><b>${money(m.increase)}</b></div><div class="metric warn"><span>Scope removed</span><b>${money(m.decrease)}</b></div></div>${changes.length?`<h3>Approved scope changes</h3><table class="project-report-table"><thead><tr><th>Date</th><th>Change</th><th>Description</th><th>Amount</th></tr></thead><tbody>${changes.map(e=>`<tr><td>${prettyDate(e.entry_date)}</td><td>${esc(entryLabel(e.entry_type))}</td><td>${esc(e.description)}</td><td>${money(e.amount)}</td></tr>`).join('')}</tbody></table>`:''}<div class="invoice-total"><span>Revised project amount</span><b>${money(m.revised)}</b></div>`:''}<div class="doc-terms"><h3>Payment terms</h3><p>${esc(p.payment_terms||'Not specified')}</p>${p.notes?`<h3>Terms and notes</h3><p>${esc(p.notes)}</p>`:''}</div>`}
function viewProject(projectId){const p=state.projects.find(x=>x.id===projectId);if(!p)return;state.activeProject=p;$('#projectDocument').innerHTML=projectDocumentHtml(p);const approved=p.status==='Approved',pending=p.status==='Pending',hasInvoice=state.invoices.some(i=>i.project_id===p.id);$('#approveProjectBtn').classList.toggle('hidden',!pending);$('#cancelProjectBtn').classList.toggle('hidden',p.status==='Cancelled'||hasInvoice);$('#scopeIncreaseBtn').classList.toggle('hidden',!approved);$('#scopeDecreaseBtn').classList.toggle('hidden',!approved);$('#addProjectEntryBtn').classList.toggle('hidden',!approved);$('#generateProjectInvoiceBtn').classList.toggle('hidden',!approved||hasInvoice);$('#generateProjectInvoiceBtn').textContent=hasInvoice?'Invoice generated':'Generate invoice';closeSheets();openSheet('#projectDetailSheet')}
async function setProjectStatus(status){if(!state.activeProject)return;const row={...state.activeProject,status};try{const saved=await store.save('projects',row,true);state.projects[state.projects.findIndex(x=>x.id===saved.id)]=saved;state.activeProject=saved;render();viewProject(saved.id);toast(`Project marked ${status.toLowerCase()}.`)}catch(err){toast(err.message)}}

function openEntry(type=''){const p=state.activeProject;if(!p||p.status!=='Approved'){toast('Approve the project before recording changes or costs.');return}$('#entryForm').reset();$('#entryProjectId').value=p.id;$('#entryDate').value=today();const fixed=['scope_increase','scope_decrease'].includes(type);$('#entryTypeWrap').classList.toggle('hidden',fixed);$('#entryType').value=fixed?type:'receipt';$('#entrySheetTitle').textContent=type==='scope_increase'?'Increase project scope':type==='scope_decrease'?'Decrease project scope':'Add cost or receipt';closeSheets();openSheet('#entrySheet')}

function approvedInvoiceProjects(editingInvoiceId=''){return state.projects.filter(p=>p.status==='Approved'&&!state.invoices.some(i=>i.project_id===p.id&&i.id!==editingInvoiceId))}
function fillInvoiceProjects(selected='',editingInvoiceId=''){const rows=approvedInvoiceProjects(editingInvoiceId);$('#invoiceProject').innerHTML=`<option value="">Select an approved project</option>`+rows.map(p=>`<option value="${p.id}">${esc(p.name)} - ${esc(partyName(p.party_id))}</option>`).join('');if(selected)$('#invoiceProject').value=selected;return rows}
function setInvoiceAmount(){const p=state.projects.find(x=>x.id===$('#invoiceProject').value);$('#invoiceAmount').value=p?projectMetrics(p).revised:''}
function openInvoice(invoiceId='',projectId=''){const invoice=state.invoices.find(x=>x.id===invoiceId),rows=fillInvoiceProjects(invoice?.project_id||projectId,invoice?.id||'');if(!invoice&&!rows.length){toast('No approved project is available for invoicing.');return}$('#invoiceForm').reset();$('#invoiceId').value=invoice?.id||'';fillInvoiceProjects(invoice?.project_id||projectId,invoice?.id||'');$('#invoiceProject').disabled=Boolean(invoice);$('#invoiceDate').value=invoice?.invoice_date||today();$('#invoiceDueDate').value=invoice?.due_date||plusDays(7);$('#invoiceAmount').value=invoice?.amount??'';$('#invoiceStatus').value=invoice?.status||'Draft';$('#invoiceNotes').value=invoice?.notes||'';$('#invoiceSheetTitle').textContent=invoice?'Edit invoice':'Generate invoice';if(!invoice)setInvoiceAmount();closeSheets();openSheet('#invoiceSheet')}
function invoiceFromForm(){const existing=state.invoices.find(x=>x.id===$('#invoiceId').value);return {id:existing?.id||id('inv'),project_id:existing?.project_id||$('#invoiceProject').value,invoice_number:existing?.invoice_number||`MII-${new Date().getFullYear()}-${String(state.invoices.length+1).padStart(4,'0')}`,invoice_date:$('#invoiceDate').value,due_date:$('#invoiceDueDate').value||null,amount:Number($('#invoiceAmount').value||0),notes:$('#invoiceNotes').value.trim(),status:$('#invoiceStatus').value,created_at:existing?.created_at||new Date().toISOString()}}
function invoiceDocumentHtml(i){const p=state.projects.find(x=>x.id===i.project_id)||{},party=state.parties.find(x=>x.id===p.party_id)||{};return `<div class="doc-head"><div class="doc-brand"><img class="doc-logo" src="assets/mughal-logo.png" alt="Mughal Interior"><p>Crafted woodwork for homes and businesses</p></div><div class="doc-meta"><b>${esc(i.invoice_number)}</b><p>Invoice date: ${prettyDate(i.invoice_date)}</p><p>Due date: ${prettyDate(i.due_date)}</p></div></div><div class="doc-title"><p class="eyebrow">INVOICE</p><h1>${esc(p.name||'Project invoice')}</h1></div><div class="project-status-strip"><span>INVOICE STATUS</span><b class="status ${statusClass(i.status)}">${esc(i.status)}</b></div><div class="doc-grid"><div class="doc-box"><small>BILL TO</small><b>${esc(party.name||'')}</b><div>${esc(party.phone||'')}</div><div>${esc(party.address||'')}</div></div><div class="doc-box"><small>PROJECT</small><b>${esc(p.name||'')}</b><div>${esc(p.project_number||'')}</div><div>${p.contract_type==='without_material'?'Labour only':'With material'}</div></div></div><table class="invoice-line"><thead><tr><th>Description</th><th>Amount</th></tr></thead><tbody><tr><td>Approved project contract and scope changes</td><td>${money(i.amount)}</td></tr></tbody></table><div class="invoice-total"><span>Total invoice</span><b>${money(i.amount)}</b></div>${i.notes?`<div class="doc-terms"><h3>Notes</h3><p>${esc(i.notes)}</p></div>`:''}`}
function viewInvoice(invoiceId){const i=state.invoices.find(x=>x.id===invoiceId);if(!i)return;state.activeInvoice=i;$('#invoiceDocument').innerHTML=invoiceDocumentHtml(i);closeSheets();openSheet('#invoiceDetailSheet')}

async function boot(){if(isCloud){const session=JSON.parse(localStorage.getItem('mi_session')||'null');if(!session){$('#loginScreen').classList.remove('hidden');return}state.token=session.token;state.userId=session.userId}try{await store.load();$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');render();if(!isCloud)toast('Demo mode — connect Supabase to save online.')}catch(e){$('#loginScreen').classList.remove('hidden');$('#loginError').textContent=e.message;$('#loginError').classList.remove('hidden')}}
function logout(show=true){localStorage.removeItem('mi_session');state.token=null;state.userId=null;$('#app').classList.add('hidden');$('#loginScreen').classList.remove('hidden');if(show)toast('Signed out.')}
function printSheet(sel){const sheet=$(sel);sheet.classList.add('printing');window.print();setTimeout(()=>sheet.classList.remove('printing'),400)}

document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)navigate(nav.dataset.nav);const action=e.target.closest('[data-action]')?.dataset.action;if(action==='new-party')openParty();if(action==='new-project')openProject();if(action==='new-invoice')openInvoice();if(e.target.closest('[data-close]')||e.target.id==='sheetBackdrop')closeSheets();const ep=e.target.closest('[data-edit-party]');if(ep)openParty(ep.dataset.editParty);const pp=e.target.closest('[data-party-project]');if(pp)openProject('',pp.dataset.partyProject);const vp=e.target.closest('[data-view-project]');if(vp)viewProject(vp.dataset.viewProject);const vi=e.target.closest('[data-view-invoice]');if(vi)viewInvoice(vi.dataset.viewInvoice)});
$('#partySearch').addEventListener('input',renderParties);$('#projectSearch').addEventListener('input',renderProjects);$('#projectStatusFilter').addEventListener('change',renderProjects);$('#invoiceSearch').addEventListener('input',renderInvoices);$('#invoiceStatusFilter').addEventListener('change',renderInvoices);
$$('input[name="projectPricingMode"]').forEach(x=>x.addEventListener('change',updateProjectPricing));bindDuration('#projectStart','#projectEnd','#projectDays');
$('#partyForm').addEventListener('submit',async e=>{e.preventDefault();const existing=state.parties.find(x=>x.id===$('#partyId').value),row={id:existing?.id||id('p'),name:$('#partyName').value.trim(),phone:$('#partyPhone').value.trim(),party_type:$('#partyType').value,address:$('#partyAddress').value.trim(),notes:$('#partyNotes').value.trim()};try{const saved=await store.save('parties',row,Boolean(existing)),i=state.parties.findIndex(x=>x.id===saved.id);i>=0?state.parties[i]=saved:state.parties.push(saved);closeSheets();render();toast(existing?'Party updated.':'Party added.')}catch(err){toast(err.message)}});
$('#projectNext').addEventListener('click',()=>{if(validProjectStep())setProjectStep(state.projectStep+1)});$('#projectBack').addEventListener('click',()=>setProjectStep(state.projectStep-1));
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();const row=projectFromForm(),existing=state.projects.some(x=>x.id===row.id);try{const saved=await store.save('projects',row,existing),i=state.projects.findIndex(x=>x.id===saved.id);i>=0?state.projects[i]=saved:state.projects.unshift(saved);closeSheets();render();toast(existing?'Project updated.':'Project created as a quotation.');viewProject(saved.id)}catch(err){toast(err.message)}});
$('#editProjectBtn').addEventListener('click',()=>openProject(state.activeProject?.id));$('#approveProjectBtn').addEventListener('click',()=>setProjectStatus('Approved'));$('#cancelProjectBtn').addEventListener('click',()=>setProjectStatus('Cancelled'));$('#scopeIncreaseBtn').addEventListener('click',()=>openEntry('scope_increase'));$('#scopeDecreaseBtn').addEventListener('click',()=>openEntry('scope_decrease'));$('#addProjectEntryBtn').addEventListener('click',()=>openEntry());$('#generateProjectInvoiceBtn').addEventListener('click',()=>openInvoice('',state.activeProject?.id));$('#printProjectBtn').addEventListener('click',()=>printSheet('#projectDetailSheet'));
$('#entryForm').addEventListener('submit',async e=>{e.preventDefault();const row={id:id('pe'),project_id:$('#entryProjectId').value,entry_type:$('#entryType').value,entry_date:$('#entryDate').value,description:$('#entryDescription').value.trim(),amount:Number($('#entryAmount').value),notes:$('#entryNotes').value.trim(),created_at:new Date().toISOString()};try{const saved=await store.save('project_entries',row,false);state.projectEntries.unshift(saved);closeSheets();render();toast(`${entryLabel(saved.entry_type)} saved.`);viewProject(row.project_id)}catch(err){toast(err.message)}});
$('#invoiceProject').addEventListener('change',setInvoiceAmount);$('#invoiceForm').addEventListener('submit',async e=>{e.preventDefault();const row=invoiceFromForm(),existing=state.invoices.some(x=>x.id===row.id),project=state.projects.find(x=>x.id===row.project_id);if(project?.status!=='Approved'){toast('Only approved projects can be invoiced.');return}try{const saved=await store.save('invoices',row,existing),i=state.invoices.findIndex(x=>x.id===saved.id);i>=0?state.invoices[i]=saved:state.invoices.unshift(saved);closeSheets();render();toast(existing?'Invoice updated.':'Invoice generated.');viewInvoice(saved.id)}catch(err){toast(err.message)}});$('#editInvoiceBtn').addEventListener('click',()=>openInvoice(state.activeInvoice?.id));$('#printInvoiceBtn').addEventListener('click',()=>printSheet('#invoiceDetailSheet'));
$('#profileBtn').addEventListener('click',()=>{if(isCloud&&confirm('Sign out of Mughal Interior Accounts?'))logout();else toast('Demo user · Supabase not connected')});$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').classList.add('hidden');try{await store.signIn($('#loginEmail').value,$('#loginPassword').value);await boot()}catch(err){$('#loginError').textContent=err.message;$('#loginError').classList.remove('hidden')}});
boot();
