const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const cfg = window.MUGHAL_CONFIG || {};
const isCloud = Boolean(cfg.supabaseUrl && cfg.supabasePublishableKey);
const state = { parties: [], projects: [], projectEntries: [], invoices: [], materials: [], materialMovements: [], suppliers: [], purchaseBills: [], purchaseBillItems: [], walkInOrders: [], walkInOrderEntries: [], businessId: null, userId: null, token: null, projectStep: 1, activeProject: null, activeInvoice: null, activeMaterial: null, activePurchaseBill: null, activeWalkInOrder: null };
const today = () => new Date().toISOString().slice(0, 10);
const plusDays = n => { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().slice(0, 10); };
const money = n => `Rs. ${Number(n || 0).toLocaleString('en-PK')}`;
const qty = n => Number(n || 0).toLocaleString('en-PK',{maximumFractionDigits:3});
const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const prettyDate = v => v ? new Date(`${v}T00:00:00`).toLocaleDateString('en-PK',{day:'numeric',month:'short',year:'numeric'}) : 'Not set';
const durationDays = (start,end) => start && end ? Math.max(0,Math.round((new Date(`${end}T00:00:00`)-new Date(`${start}T00:00:00`))/86400000)) : null;
const datePlus = (start,days) => { if(!start || days==='' || days===null) return ''; const d=new Date(`${start}T00:00:00`); d.setDate(d.getDate()+Number(days)); return d.toISOString().slice(0,10); };
const id = prefix => crypto.randomUUID?.() || `${prefix}${Date.now()}`;

const demo = {
  parties:[{id:'p1',name:'XYZ Traders',phone:'0300 1234567',party_type:'Business',address:'Lahore',notes:''}],
  projects:[{id:'pr1',project_number:'MIP-2026-0001',party_id:'p1',name:'Project A',description:'Kitchen cabinets, wardrobes and TV wall.',quote_date:today(),valid_until:plusDays(15),start_date:plusDays(20),expected_end_date:plusDays(65),days_to_complete:45,pricing_mode:'both',price_with_material:1250000,price_without_material:450000,contract_type:'with_material',original_contract_amount:1250000,payment_terms:'40% advance, 40% during work and 20% on completion.',notes:'Hardware by approved brands.',status:'Approved',created_at:new Date().toISOString()}],
  entries:[], invoices:[],
  materials:[{id:'m1',name:'MDF sheet 18mm',category:'Boards',sku:'MDF-18',unit:'sheet',reorder_level:5,default_unit_cost:8500,active:true,created_at:new Date().toISOString()},{id:'m2',name:'Concealed hinges',category:'Hardware',sku:'HINGE-01',unit:'piece',reorder_level:20,default_unit_cost:450,active:true,created_at:new Date().toISOString()}],
  materialMovements:[{id:'mm1',material_id:'m1',project_id:null,movement_type:'purchase',movement_date:today(),quantity:20,unit_cost:8500,supplier_name:'Demo Supplier',reference:'Opening stock',notes:'',created_at:new Date().toISOString()},{id:'mm2',material_id:'m2',project_id:null,movement_type:'purchase',movement_date:today(),quantity:100,unit_cost:450,supplier_name:'Demo Supplier',reference:'Opening stock',notes:'',created_at:new Date().toISOString()}],
  suppliers:[{id:'s1',name:'Demo Supplier',contact_name:'',phone:'0300 0000000',address:'Lahore',notes:'',active:true,created_at:new Date().toISOString()}],
  purchaseBills:[], purchaseBillItems:[], walkInOrders:[], walkInOrderEntries:[]
};

class Store {
  constructor(){this.base=(cfg.supabaseUrl||'').replace(/\/$/,'');this.key=cfg.supabasePublishableKey||''}
  headers(extra={}){return {'apikey':this.key,'Authorization':`Bearer ${state.token}`,'Content-Type':'application/json',...extra}}
  async request(path,options={}){const r=await fetch(`${this.base}${path}`,{...options,headers:this.headers(options.headers)});if(r.status===401){logout(false);throw new Error('Your session expired. Please sign in again.')}if(!r.ok){const e=await r.text();throw new Error(e||'Could not save the record.')}return r.status===204?null:r.json()}
  async signIn(email,password){const r=await fetch(`${this.base}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:this.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error_description||data.msg||'Email or password is incorrect.');state.token=data.access_token;state.userId=data.user.id;localStorage.setItem('mi_session',JSON.stringify({token:state.token,userId:state.userId}))}
  async load(){
    if(!isCloud){state.parties=JSON.parse(localStorage.getItem('mi_parties')||'null')||demo.parties;state.projects=JSON.parse(localStorage.getItem('mi_projects')||'null')||demo.projects;state.projectEntries=JSON.parse(localStorage.getItem('mi_project_entries')||'null')||demo.entries;state.invoices=JSON.parse(localStorage.getItem('mi_invoices')||'null')||demo.invoices;state.materials=JSON.parse(localStorage.getItem('mi_materials')||'null')||demo.materials;state.materialMovements=JSON.parse(localStorage.getItem('mi_material_movements')||'null')||demo.materialMovements;state.suppliers=JSON.parse(localStorage.getItem('mi_suppliers')||'null')||demo.suppliers;state.purchaseBills=JSON.parse(localStorage.getItem('mi_purchase_bills')||'null')||demo.purchaseBills;state.purchaseBillItems=JSON.parse(localStorage.getItem('mi_purchase_bill_items')||'null')||demo.purchaseBillItems;state.walkInOrders=JSON.parse(localStorage.getItem('mi_walk_in_orders')||'null')||demo.walkInOrders;state.walkInOrderEntries=JSON.parse(localStorage.getItem('mi_walk_in_order_entries')||'null')||demo.walkInOrderEntries;return}
    const membership=await this.request(`/rest/v1/business_members?select=business_id&user_id=eq.${state.userId}&limit=1`);if(!membership.length)throw new Error('This account has not been added to a business yet.');state.businessId=membership[0].business_id;
    [state.parties,state.projects,state.projectEntries,state.invoices,state.materials,state.materialMovements,state.suppliers,state.purchaseBills,state.purchaseBillItems,state.walkInOrders,state.walkInOrderEntries]=await Promise.all([
      this.request(`/rest/v1/parties?select=*&business_id=eq.${state.businessId}&order=name.asc`),
      this.request(`/rest/v1/projects?select=*&business_id=eq.${state.businessId}&order=created_at.desc`),
      this.request(`/rest/v1/project_entries?select=*&business_id=eq.${state.businessId}&order=entry_date.desc,created_at.desc`),
      this.request(`/rest/v1/invoices?select=*&business_id=eq.${state.businessId}&order=created_at.desc`),
      this.request(`/rest/v1/materials?select=*&business_id=eq.${state.businessId}&active=eq.true&order=name.asc`),
      this.request(`/rest/v1/material_movements?select=*&business_id=eq.${state.businessId}&order=movement_date.desc,created_at.desc`),
      this.request(`/rest/v1/suppliers?select=*&business_id=eq.${state.businessId}&active=eq.true&order=name.asc`),
      this.request(`/rest/v1/purchase_bills?select=*&business_id=eq.${state.businessId}&order=bill_date.desc,created_at.desc`),
      this.request(`/rest/v1/purchase_bill_items?select=*&business_id=eq.${state.businessId}&order=created_at.asc`),
      this.request(`/rest/v1/walk_in_orders?select=*&business_id=eq.${state.businessId}&order=order_date.desc,created_at.desc`),
      this.request(`/rest/v1/walk_in_order_entries?select=*&business_id=eq.${state.businessId}&order=entry_date.desc,created_at.desc`)
    ])
  }
  async save(table,row,updating){if(!isCloud)return row;row.business_id=state.businessId;const path=updating?`/rest/v1/${table}?id=eq.${row.id}`:`/rest/v1/${table}`;const data=await this.request(path,{method:updating?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});return data[0]}
}
const store=new Store();

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),3000)}
function openSheet(sel){$('#sheetBackdrop').classList.remove('hidden');$(sel).classList.remove('hidden');document.body.style.overflow='hidden'}
function closeSheets(){$('#sheetBackdrop').classList.add('hidden');$$('.sheet').forEach(x=>x.classList.add('hidden'));document.body.style.overflow=''}
function partyName(pid){return state.parties.find(p=>p.id===pid)?.name||'Unknown party'}
function statusClass(s){return String(s||'pending').toLowerCase().replaceAll(' ','-')}
function selectedProjectAmount(p){return Number(p.contract_type==='without_material'?p.price_without_material:p.price_with_material)||Number(p.original_contract_amount||0)}
function projectMetrics(project){const rows=state.projectEntries.filter(e=>e.project_id===project.id),sum=t=>rows.filter(e=>e.entry_type===t).reduce((a,e)=>a+Number(e.amount||0),0);const increase=sum('scope_increase'),decrease=sum('scope_decrease'),receipts=sum('receipt'),labour=sum('labour'),materials=sum('material'),expenses=sum('expense'),original=selectedProjectAmount(project),revised=original+increase-decrease,costs=labour+materials+expenses;return {rows,increase,decrease,receipts,labour,materials,expenses,original,revised,costs,balance:revised-receipts,profit:revised-costs}}
function projectPriceText(p){if(p.pricing_mode==='both')return `${money(p.price_with_material)} / ${money(p.price_without_material)}`;return money(p.pricing_mode==='without_material'?p.price_without_material:p.price_with_material)}
function projectCard(p){const m=projectMetrics(p),approved=p.status==='Approved',schedule=p.start_date||p.expected_end_date?`${prettyDate(p.start_date)} – ${prettyDate(p.expected_end_date)}`:'Not scheduled';return `<article class="item-card project-card"><div class="project-card-head"><div><div class="project-card-number">${esc(p.project_number)}</div><h3>${esc(p.name)}</h3></div><span class="status ${statusClass(p.status)}">${esc(p.status)}</span></div><div class="project-card-info"><div><span>Party</span><b>${esc(partyName(p.party_id))}</b></div><div><span>Schedule</span><b>${schedule}</b></div><div><span>${approved?'Revised amount':'Quoted amount'}</span><b>${approved?money(m.revised):projectPriceText(p)}</b></div><div><span>Days</span><b>${p.days_to_complete??'Not set'}</b></div></div><div class="project-card-actions"><button class="quick-btn view" data-view-project="${p.id}">View</button>${approved?`<button class="quick-btn receipt" data-project-id="${p.id}" data-card-entry="receipt">Add receipt</button><button class="quick-btn" data-project-id="${p.id}" data-card-material>Assign material</button><button class="quick-btn" data-project-id="${p.id}" data-card-entry="labour">Assign labour</button><button class="quick-btn" data-project-id="${p.id}" data-card-entry="expense">Record expense</button>`:''}</div></article>`}
function invoiceCard(i){const p=state.projects.find(x=>x.id===i.project_id);return `<article class="item-card"><div><h3>${esc(i.invoice_number)}</h3><div class="meta"><span>${esc(p?.name||'Unknown project')}</span><span>${esc(partyName(p?.party_id))}</span><span>${prettyDate(i.invoice_date)}</span></div></div><div class="item-actions"><div><div class="amount">${money(i.amount)}</div><span class="status ${statusClass(i.status)}">${esc(i.status)}</span></div><button class="mini-btn" data-view-invoice="${i.id}">View</button></div></article>`}

function persistLocal(){if(isCloud)return;localStorage.setItem('mi_parties',JSON.stringify(state.parties));localStorage.setItem('mi_projects',JSON.stringify(state.projects));localStorage.setItem('mi_project_entries',JSON.stringify(state.projectEntries));localStorage.setItem('mi_invoices',JSON.stringify(state.invoices));localStorage.setItem('mi_materials',JSON.stringify(state.materials));localStorage.setItem('mi_material_movements',JSON.stringify(state.materialMovements));localStorage.setItem('mi_suppliers',JSON.stringify(state.suppliers));localStorage.setItem('mi_purchase_bills',JSON.stringify(state.purchaseBills));localStorage.setItem('mi_purchase_bill_items',JSON.stringify(state.purchaseBillItems));localStorage.setItem('mi_walk_in_orders',JSON.stringify(state.walkInOrders));localStorage.setItem('mi_walk_in_order_entries',JSON.stringify(state.walkInOrderEntries))}
function render(){persistLocal();$('#partyCount').textContent=state.parties.length;$('#pendingProjectCount').textContent=state.projects.filter(p=>p.status==='Pending').length;$('#invoiceCount').textContent=state.invoices.length;$('#projectValue').textContent=money(state.projects.filter(p=>p.status==='Approved').reduce((a,p)=>a+projectMetrics(p).revised,0));const recent=[...state.projects].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,3);$('#recentProjects').innerHTML=recent.length?recent.map(projectCard).join(''):`<div class="empty"><b>No projects yet</b><span>Create a project quotation to begin.</span></div>`;renderParties();renderProjects();renderInvoices();renderInventory();renderPurchasing();renderWalkInOrders();fillPartySelect()}
function renderParties(){const q=$('#partySearch').value.toLowerCase(),rows=state.parties.filter(p=>[p.name,p.phone,p.address].join(' ').toLowerCase().includes(q));$('#partyList').innerHTML=rows.length?rows.map(p=>`<article class="item-card"><div><h3>${esc(p.name)}</h3><div class="meta"><span>${esc(p.party_type)}</span>${p.phone?`<span>${esc(p.phone)}</span>`:''}${p.address?`<span>${esc(p.address)}</span>`:''}</div></div><div class="item-actions"><button class="mini-btn" data-edit-party="${p.id}">Edit</button><button class="btn soft" data-party-project="${p.id}">New project</button></div></article>`).join(''):`<div class="empty"><b>No parties found</b><span>Add a customer to begin.</span></div>`}
function renderProjects(){const text=$('#projectSearch').value.toLowerCase(),status=$('#projectStatusFilter').value,rows=state.projects.filter(p=>(status==='all'||p.status===status)&&[p.project_number,p.name,partyName(p.party_id)].join(' ').toLowerCase().includes(text));$('#projectList').innerHTML=rows.length?rows.map(projectCard).join(''):`<div class="empty"><b>No matching projects</b><span>Change the filter or add a project.</span></div>`}
function renderInvoices(){const text=$('#invoiceSearch').value.toLowerCase(),status=$('#invoiceStatusFilter').value,rows=state.invoices.filter(i=>{const p=state.projects.find(x=>x.id===i.project_id);return(status==='all'||i.status===status)&&[i.invoice_number,p?.name,partyName(p?.party_id)].join(' ').toLowerCase().includes(text)});$('#invoiceList').innerHTML=rows.length?rows.map(invoiceCard).join(''):`<div class="empty"><b>No matching invoices</b><span>Approve a project, then generate its invoice.</span></div>`}
function materialMetrics(material){const rows=state.materialMovements.filter(m=>m.material_id===material.id),incoming=rows.filter(m=>['purchase','adjustment_in'].includes(m.movement_type)),inQty=incoming.reduce((a,m)=>a+Number(m.quantity||0),0),inValue=incoming.reduce((a,m)=>a+Number(m.quantity||0)*Number(m.unit_cost||0),0),outQty=rows.filter(m=>['project_issue','walk_in_issue','adjustment_out'].includes(m.movement_type)).reduce((a,m)=>a+Number(m.quantity||0),0),stock=inQty-outQty,average=inQty?inValue/inQty:Number(material.default_unit_cost||0);return {rows,stock,average,value:stock*average,low:stock<=Number(material.reorder_level||0)}}
function materialCard(material){const m=materialMetrics(material);return `<article class="material-card ${m.low?'low':''}"><div class="material-head"><div><h3>${esc(material.name)}</h3><small>${esc(material.category||'Uncategorized')}${material.sku?` · ${esc(material.sku)}`:''}</small></div><span class="stock-pill">${m.low?'Low stock':'In stock'}</span></div><div class="material-stats"><div><span>Available</span><b>${qty(m.stock)} ${esc(material.unit)}</b></div><div><span>Avg. cost</span><b>${money(m.average)}</b></div><div><span>Stock value</span><b>${money(m.value)}</b></div></div><div class="material-actions"><button class="quick-btn view" data-view-material="${material.id}">View ledger</button><button class="quick-btn receipt" data-purchase-material="${material.id}">+ Purchase</button><button class="quick-btn" data-issue-material="${material.id}">Assign to project</button></div></article>`}
function renderInventory(){const text=$('#materialSearch').value.toLowerCase(),rows=state.materials.filter(m=>[m.name,m.category,m.sku].join(' ').toLowerCase().includes(text)),metrics=state.materials.map(materialMetrics);$('#materialCount').textContent=state.materials.length;$('#lowStockCount').textContent=metrics.filter(m=>m.low).length;$('#inventoryValue').textContent=money(metrics.reduce((a,m)=>a+m.value,0));$('#materialList').innerHTML=rows.length?rows.map(materialCard).join(''):`<div class="empty"><b>No materials found</b><span>Add a material, then record its first purchase.</span></div>`}
function fillMovementMaterials(selected=''){const opts=`<option value="">Select material</option>`+state.materials.map(m=>`<option value="${m.id}">${esc(m.name)} (${qty(materialMetrics(m).stock)} ${esc(m.unit)})</option>`).join('');$('#movementMaterial').innerHTML=opts;if(selected)$('#movementMaterial').value=selected}
function fillMovementProjects(selected=''){const rows=state.projects.filter(p=>p.status==='Approved'),opts=`<option value="">Select approved project</option>`+rows.map(p=>`<option value="${p.id}">${esc(p.name)} - ${esc(partyName(p.party_id))}</option>`).join('');$('#movementProject').innerHTML=opts;if(selected)$('#movementProject').value=selected;return rows}
function updateMovementMaterial(){const material=state.materials.find(m=>m.id===$('#movementMaterial').value);if(!material){$('#availableStockText').textContent='Available stock: 0';return}const m=materialMetrics(material);$('#availableStockText').textContent=`Available stock: ${qty(m.stock)} ${material.unit}`;if(!$('#movementUnitCost').value)$('#movementUnitCost').value=(m.average||material.default_unit_cost||0).toFixed(2)}
function openMaterial(materialId=''){const material=state.materials.find(m=>m.id===materialId);$('#materialForm').reset();$('#materialId').value=material?.id||'';$('#materialName').value=material?.name||'';$('#materialCategory').value=material?.category||'';$('#materialSku').value=material?.sku||'';$('#materialUnit').value=material?.unit||'piece';$('#materialReorder').value=material?.reorder_level??0;$('#materialDefaultCost').value=material?.default_unit_cost??0;$('#materialSheetTitle').textContent=material?'Edit material':'Add material';closeSheets();openSheet('#materialSheet')}
function openMovement(type='purchase',materialId='',projectId=''){if(!state.materials.length){toast('Add a material before recording stock.');openMaterial();return}if(type==='project_issue'&&!fillMovementProjects(projectId).length){toast('Approve a project before assigning material.');return}$('#movementForm').reset();$('#movementType').value=type;fillMovementMaterials(materialId);fillMovementProjects(projectId);$('#movementProjectWrap').classList.toggle('hidden',type!=='project_issue');$('#movementProject').required=type==='project_issue';$('#movementSupplierWrap').classList.toggle('hidden',type==='project_issue');$('#movementDate').value=today();$('#movementSheetTitle').textContent=type==='project_issue'?'Assign material to project':'Record material purchase';if(materialId)updateMovementMaterial();closeSheets();openSheet('#movementSheet')}
function movementLabel(type){return {purchase:'Purchase',project_issue:'Project issue',walk_in_issue:'Walk-in order issue',adjustment_in:'Stock added',adjustment_out:'Stock removed'}[type]||type}
function viewMaterial(materialId){const material=state.materials.find(m=>m.id===materialId);if(!material)return;state.activeMaterial=material;const m=materialMetrics(material),rows=[...m.rows].sort((a,b)=>`${b.movement_date}${b.created_at}`.localeCompare(`${a.movement_date}${a.created_at}`));$('#materialDetailTitle').textContent=material.name;$('#materialDetail').innerHTML=`<div class="stock-ledger-head"><div class="metric"><span>Available</span><b>${qty(m.stock)} ${esc(material.unit)}</b></div><div class="metric"><span>Average cost</span><b>${money(m.average)}</b></div><div class="metric"><span>Stock value</span><b>${money(m.value)}</b></div><div class="metric ${m.low?'warn':''}"><span>Reorder level</span><b>${qty(material.reorder_level)}</b></div></div><h3>Stock movements</h3><div class="stock-ledger-list">${rows.length?rows.map(row=>{const incoming=['purchase','adjustment_in'].includes(row.movement_type),project=state.projects.find(p=>p.id===row.project_id),order=state.walkInOrders.find(w=>w.id===row.walk_in_order_id);return `<div class="stock-movement"><span class="movement-sign ${incoming?'in':'out'}">${incoming?'+':'−'}</span><div class="movement-copy"><b>${esc(movementLabel(row.movement_type))}${project?` · ${esc(project.name)}`:''}${order?` · ${esc(order.title)}`:''}</b><small>${prettyDate(row.movement_date)}${row.supplier_name?` · ${esc(row.supplier_name)}`:''}${row.reference?` · ${esc(row.reference)}`:''}</small></div><div class="movement-qty ${incoming?'':'out'}">${incoming?'+':'−'} ${qty(row.quantity)} ${esc(material.unit)}<small>@ ${money(row.unit_cost)}</small></div></div>`}).join(''):'<div class="empty"><b>No stock movements yet</b></div>'}</div>`;closeSheets();openSheet('#materialDetailSheet')}
function fillPartySelect(selected=''){const opts=`<option value="">Select a party</option>`+state.parties.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#projectParty').innerHTML=opts;if(selected)$('#projectParty').value=selected}
function navigate(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$$('.bottom-nav [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));scrollTo(0,0)}

function bindDuration(startSel,endSel,daysSel){const calc=()=>{const n=durationDays($(startSel).value,$(endSel).value);$(daysSel).value=n===null?'':n};$(startSel).addEventListener('change',()=>{$(endSel).value?calc():($(daysSel).value!==''&&($(endSel).value=datePlus($(startSel).value,$(daysSel).value)))});$(endSel).addEventListener('change',calc);$(daysSel).addEventListener('input',()=>{if($(startSel).value&&$(daysSel).value!=='')$(endSel).value=datePlus($(startSel).value,$(daysSel).value)})}
function openParty(pid=''){const p=state.parties.find(x=>x.id===pid);$('#partyForm').reset();$('#partyId').value=p?.id||'';$('#partyName').value=p?.name||'';$('#partyPhone').value=p?.phone||'';$('#partyType').value=p?.party_type||'Individual';$('#partyAddress').value=p?.address||'';$('#partyNotes').value=p?.notes||'';$('#partySheetTitle').textContent=p?'Edit party':'Add party';closeSheets();openSheet('#partySheet')}

function setProjectStep(n){state.projectStep=n;$$('[data-project-step]').forEach(x=>x.classList.toggle('active',Number(x.dataset.projectStep)===n));$$('#projectSteps button').forEach((b,i)=>b.classList.toggle('active',i+1<=n));$('#projectBack').classList.toggle('hidden',n===1);$('#projectNext').classList.toggle('hidden',n===3);$('#projectSave').classList.toggle('hidden',n!==3);if(n===3)renderProjectReview()}
function updateProjectPricing(){const mode=$('input[name="projectPricingMode"]:checked').value;$('#projectWithMaterialWrap').classList.toggle('hidden',mode==='without_material');$('#projectWithoutMaterialWrap').classList.toggle('hidden',mode==='with_material');$('#approvedOptionWrap').classList.toggle('hidden',mode!=='both');$$('#projectSheet .choice').forEach(c=>c.classList.toggle('selected',$('input',c).checked));if(mode!=='both')$('#projectContractType').value=mode}
function openProject(projectId='',partyId=''){if(!state.parties.length){toast('Add a party before creating a project.');openParty();return}const p=state.projects.find(x=>x.id===projectId),hasInvoice=p&&state.invoices.some(i=>i.project_id===p.id);$('#projectForm').reset();$('#projectId').value=p?.id||'';fillPartySelect(p?.party_id||partyId);$('#projectStatus').value=p?.status||'Pending';$('#projectStatus').disabled=Boolean(hasInvoice);$('#projectName').value=p?.name||'';$('#projectDescription').value=p?.description||'';$('#projectQuoteDate').value=p?.quote_date||today();$('#projectValidUntil').value=p?.valid_until||plusDays(15);$('#projectStart').value=p?.start_date||'';$('#projectEnd').value=p?.expected_end_date||'';$('#projectDays').value=p?.days_to_complete??durationDays(p?.start_date,p?.expected_end_date)??'';const mode=p?.pricing_mode||'with_material';$(`input[name="projectPricingMode"][value="${mode}"]`).checked=true;$('#projectPriceWithMaterial').value=p?.price_with_material??(p?.contract_type==='with_material'?p?.original_contract_amount:'')??'';$('#projectPriceWithoutMaterial').value=p?.price_without_material??(p?.contract_type==='without_material'?p?.original_contract_amount:'')??'';$('#projectContractType').value=p?.contract_type||'with_material';$('#projectPaymentTerms').value=p?.payment_terms||'';$('#projectNotes').value=p?.notes||'';$('#projectSheetTitle').textContent=p?'Edit project':'New project';updateProjectPricing();setProjectStep(1);closeSheets();openSheet('#projectSheet')}
function projectFromForm(){const existing=state.projects.find(x=>x.id===$('#projectId').value),mode=$('input[name="projectPricingMode"]:checked').value,type=mode==='both'?$('#projectContractType').value:mode,withPrice=mode==='without_material'?null:Number($('#projectPriceWithMaterial').value||0),withoutPrice=mode==='with_material'?null:Number($('#projectPriceWithoutMaterial').value||0),amount=type==='without_material'?withoutPrice:withPrice;return {id:existing?.id||id('pr'),project_number:existing?.project_number||`MIP-${new Date().getFullYear()}-${String(state.projects.length+1).padStart(4,'0')}`,party_id:$('#projectParty').value,source_quotation_id:existing?.source_quotation_id||null,name:$('#projectName').value.trim(),description:$('#projectDescription').value.trim(),quote_date:$('#projectQuoteDate').value,valid_until:$('#projectValidUntil').value||null,start_date:$('#projectStart').value||null,expected_end_date:$('#projectEnd').value||null,days_to_complete:$('#projectDays').value===''?null:Number($('#projectDays').value),pricing_mode:mode,price_with_material:withPrice,price_without_material:withoutPrice,contract_type:type,original_contract_amount:Number(amount||0),payment_terms:$('#projectPaymentTerms').value.trim(),notes:$('#projectNotes').value.trim(),status:$('#projectStatus').value,created_at:existing?.created_at||new Date().toISOString()}}
function validProjectStep(){if(state.projectStep===1){for(const field of ['projectParty','projectName','projectDescription','projectQuoteDate'])if(!$(`#${field}`).value){$(`#${field}`).reportValidity();return false}}if(state.projectStep===2){const mode=$('input[name="projectPricingMode"]:checked').value;if((mode==='with_material'||mode==='both')&&!Number($('#projectPriceWithMaterial').value)){toast('Enter the amount with material.');return false}if((mode==='without_material'||mode==='both')&&!Number($('#projectPriceWithoutMaterial').value)){toast('Enter the amount without material.');return false}}return true}
function renderProjectReview(){const p=projectFromForm(),days=p.days_to_complete??durationDays(p.start_date,p.expected_end_date);$('#projectReview').innerHTML=`<div class="review-row"><span>Party</span><b>${esc(partyName(p.party_id))}</b></div><div class="review-row"><span>Project</span><b>${esc(p.name)}</b></div><div class="review-row"><span>Status</span><b>${esc(p.status)}</b></div><div class="review-row"><span>Start date</span><b>${prettyDate(p.start_date)}</b></div><div class="review-row"><span>Completion date</span><b>${prettyDate(p.expected_end_date)}</b></div><div class="review-row"><span>Days to complete</span><b>${days??'Not set'}</b></div><div class="review-row"><span>Quotation</span><b>${projectPriceText(p)}</b></div>`}
function priceBoxes(p){if(p.pricing_mode==='both')return `<div><small>WITH MATERIAL</small><b>${money(p.price_with_material)}</b></div><div><small>LABOUR ONLY</small><b>${money(p.price_without_material)}</b></div>`;return `<div><small>${p.pricing_mode==='with_material'?'WITH MATERIAL':'LABOUR ONLY'}</small><b>${money(p.pricing_mode==='with_material'?p.price_with_material:p.price_without_material)}</b></div>`}
function entryLabel(t){return {scope_increase:'Scope increase',scope_decrease:'Scope decrease',receipt:'Customer receipt',labour:'Labour cost',material:'Material cost',expense:'Other expense'}[t]||t}
function projectDocumentHtml(p){const party=state.parties.find(x=>x.id===p.party_id)||{},m=projectMetrics(p),days=p.days_to_complete??durationDays(p.start_date,p.expected_end_date),changes=m.rows.filter(e=>['scope_increase','scope_decrease'].includes(e.entry_type)).sort((a,b)=>String(a.entry_date).localeCompare(String(b.entry_date)));return `<div class="doc-head"><div class="doc-brand"><img class="doc-logo" src="assets/mughal-logo.png?v=2" alt="Mughal Interior"><p>Crafted woodwork for homes and businesses</p></div><div class="doc-meta"><b>${esc(p.project_number)}</b><p>Quotation date: ${prettyDate(p.quote_date)}</p><p>Valid until: ${prettyDate(p.valid_until)}</p></div></div><div class="doc-title"><p class="eyebrow">PROJECT QUOTATION</p><h1>${esc(p.name)}</h1></div><div class="project-status-strip"><span>PROJECT STATUS</span><b class="status ${statusClass(p.status)}">${esc(p.status)}</b></div><div class="doc-grid"><div class="doc-box"><small>PREPARED FOR</small><b>${esc(party.name||'')}</b><div>${esc(party.phone||'')}</div><div>${esc(party.address||'')}</div></div></div><div class="doc-grid schedule-grid"><div class="doc-box"><small>PROJECT START DATE</small><b>${prettyDate(p.start_date)}</b></div><div class="doc-box"><small>PROJECT COMPLETION DATE</small><b>${prettyDate(p.expected_end_date)}</b></div><div class="doc-box"><small>DAYS TO COMPLETE</small><b>${days??'Not set'}</b></div></div><h3>Proposed scope of work</h3><div class="doc-details">${esc(p.description)}</div><div class="price-box">${priceBoxes(p)}</div>${p.status==='Approved'?`<div class="scope-summary"><div class="metric"><span>Approved amount</span><b>${money(m.original)}</b></div><div class="metric good"><span>Scope added</span><b>${money(m.increase)}</b></div><div class="metric warn"><span>Scope removed</span><b class="scope-negative">− ${money(m.decrease)}</b></div></div>${changes.length?`<h3>Approved scope changes</h3><table class="project-report-table"><thead><tr><th>Date</th><th>Change</th><th>Description</th><th>Amount</th></tr></thead><tbody>${changes.map(e=>`<tr><td>${prettyDate(e.entry_date)}</td><td>${esc(entryLabel(e.entry_type))}</td><td>${esc(e.description)}</td><td class="${e.entry_type==='scope_decrease'?'scope-negative':''}">${e.entry_type==='scope_decrease'?'− ':''}${money(e.amount)}</td></tr>`).join('')}</tbody></table>`:''}<div class="invoice-total"><span>Revised project amount</span><b>${money(m.revised)}</b></div>`:''}<div class="doc-terms"><h3>Payment terms</h3><p>${esc(p.payment_terms||'Not specified')}</p>${p.notes?`<h3>Terms and notes</h3><p>${esc(p.notes)}</p>`:''}</div>`}
function viewProject(projectId){const p=state.projects.find(x=>x.id===projectId);if(!p)return;state.activeProject=p;$('#projectDocument').innerHTML=projectDocumentHtml(p);const approved=p.status==='Approved',pending=p.status==='Pending',hasInvoice=state.invoices.some(i=>i.project_id===p.id);$('#approveProjectBtn').classList.toggle('hidden',!pending);$('#cancelProjectBtn').classList.toggle('hidden',p.status==='Cancelled'||hasInvoice);$('#scopeIncreaseBtn').classList.toggle('hidden',!approved);$('#scopeDecreaseBtn').classList.toggle('hidden',!approved);$('#assignProjectMaterialBtn').classList.toggle('hidden',!approved);$('#addProjectEntryBtn').classList.toggle('hidden',!approved);$('#generateProjectInvoiceBtn').classList.toggle('hidden',!approved||hasInvoice);$('#generateProjectInvoiceBtn').textContent=hasInvoice?'Invoice generated':'Generate invoice';closeSheets();openSheet('#projectDetailSheet')}
async function setProjectStatus(status){if(!state.activeProject)return;const row={...state.activeProject,status};try{const saved=await store.save('projects',row,true);state.projects[state.projects.findIndex(x=>x.id===saved.id)]=saved;state.activeProject=saved;render();viewProject(saved.id);toast(`Project marked ${status.toLowerCase()}.`)}catch(err){toast(err.message)}}

function openEntry(type=''){const p=state.activeProject;if(!p||p.status!=='Approved'){toast('Approve the project before recording changes or costs.');return}$('#entryForm').reset();$('#entryProjectId').value=p.id;$('#entryDate').value=today();const fixed=Boolean(type),titles={scope_increase:'Increase project scope',scope_decrease:'Decrease project scope',receipt:'Add customer receipt',material:'Assign material',labour:'Assign labour',expense:'Record project expense'};$('#entryTypeWrap').classList.toggle('hidden',fixed);$('#entryType').value=type||'receipt';$('#entrySheetTitle').textContent=titles[type]||'Add cost or receipt';closeSheets();openSheet('#entrySheet')}

function approvedInvoiceProjects(editingInvoiceId=''){return state.projects.filter(p=>p.status==='Approved'&&!state.invoices.some(i=>i.project_id===p.id&&i.id!==editingInvoiceId))}
function fillInvoiceProjects(selected='',editingInvoiceId=''){const rows=approvedInvoiceProjects(editingInvoiceId);$('#invoiceProject').innerHTML=`<option value="">Select an approved project</option>`+rows.map(p=>`<option value="${p.id}">${esc(p.name)} - ${esc(partyName(p.party_id))}</option>`).join('');if(selected)$('#invoiceProject').value=selected;return rows}
function setInvoiceAmount(){const p=state.projects.find(x=>x.id===$('#invoiceProject').value);$('#invoiceAmount').value=p?projectMetrics(p).revised:''}
function openInvoice(invoiceId='',projectId=''){const invoice=state.invoices.find(x=>x.id===invoiceId),rows=fillInvoiceProjects(invoice?.project_id||projectId,invoice?.id||'');if(!invoice&&!rows.length){toast('No approved project is available for invoicing.');return}$('#invoiceForm').reset();$('#invoiceId').value=invoice?.id||'';fillInvoiceProjects(invoice?.project_id||projectId,invoice?.id||'');$('#invoiceProject').disabled=Boolean(invoice);$('#invoiceDate').value=invoice?.invoice_date||today();$('#invoiceDueDate').value=invoice?.due_date||plusDays(7);$('#invoiceAmount').value=invoice?.amount??'';$('#invoiceStatus').value=invoice?.status||'Draft';$('#invoiceNotes').value=invoice?.notes||'';$('#invoiceSheetTitle').textContent=invoice?'Edit invoice':'Generate invoice';if(!invoice)setInvoiceAmount();closeSheets();openSheet('#invoiceSheet')}
function invoiceFromForm(){const existing=state.invoices.find(x=>x.id===$('#invoiceId').value);return {id:existing?.id||id('inv'),project_id:existing?.project_id||$('#invoiceProject').value,invoice_number:existing?.invoice_number||`MII-${new Date().getFullYear()}-${String(state.invoices.length+1).padStart(4,'0')}`,invoice_date:$('#invoiceDate').value,due_date:$('#invoiceDueDate').value||null,amount:Number($('#invoiceAmount').value||0),notes:$('#invoiceNotes').value.trim(),status:$('#invoiceStatus').value,created_at:existing?.created_at||new Date().toISOString()}}
function invoiceDocumentHtml(i){const p=state.projects.find(x=>x.id===i.project_id)||{},party=state.parties.find(x=>x.id===p.party_id)||{};return `<div class="doc-head"><div class="doc-brand"><img class="doc-logo" src="assets/mughal-logo.png?v=2" alt="Mughal Interior"><p>Crafted woodwork for homes and businesses</p></div><div class="doc-meta"><b>${esc(i.invoice_number)}</b><p>Invoice date: ${prettyDate(i.invoice_date)}</p><p>Due date: ${prettyDate(i.due_date)}</p></div></div><div class="doc-title"><p class="eyebrow">INVOICE</p><h1>${esc(p.name||'Project invoice')}</h1></div><div class="project-status-strip"><span>INVOICE STATUS</span><b class="status ${statusClass(i.status)}">${esc(i.status)}</b></div><div class="doc-grid"><div class="doc-box"><small>BILL TO</small><b>${esc(party.name||'')}</b><div>${esc(party.phone||'')}</div><div>${esc(party.address||'')}</div></div><div class="doc-box"><small>PROJECT</small><b>${esc(p.name||'')}</b><div>${esc(p.project_number||'')}</div><div>${p.contract_type==='without_material'?'Labour only':'With material'}</div></div></div><table class="invoice-line"><thead><tr><th>Description</th><th>Amount</th></tr></thead><tbody><tr><td>Approved project contract and scope changes</td><td>${money(i.amount)}</td></tr></tbody></table><div class="invoice-total"><span>Total invoice</span><b>${money(i.amount)}</b></div>${i.notes?`<div class="doc-terms"><h3>Notes</h3><p>${esc(i.notes)}</p></div>`:''}`}
function viewInvoice(invoiceId){const i=state.invoices.find(x=>x.id===invoiceId);if(!i)return;state.activeInvoice=i;$('#invoiceDocument').innerHTML=invoiceDocumentHtml(i);closeSheets();openSheet('#invoiceDetailSheet')}

async function boot(){if(isCloud){const session=JSON.parse(localStorage.getItem('mi_session')||'null');if(!session){$('#loginScreen').classList.remove('hidden');return}state.token=session.token;state.userId=session.userId}try{await store.load();$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');render();if(!isCloud)toast('Demo mode — connect Supabase to save online.')}catch(e){$('#loginScreen').classList.remove('hidden');$('#loginError').textContent=e.message;$('#loginError').classList.remove('hidden')}}
function logout(show=true){localStorage.removeItem('mi_session');state.token=null;state.userId=null;$('#app').classList.add('hidden');$('#loginScreen').classList.remove('hidden');if(show)toast('Signed out.')}
function printSheet(sel){const sheet=$(sel);sheet.classList.add('printing');window.print();setTimeout(()=>sheet.classList.remove('printing'),400)}

document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)navigate(nav.dataset.nav);const action=e.target.closest('[data-action]')?.dataset.action;if(action==='new-party')openParty();if(action==='new-project')openProject();if(action==='new-invoice')openInvoice();if(action==='new-material')openMaterial();if(action==='new-purchase')openPurchaseBill();if(e.target.closest('[data-close]')||e.target.id==='sheetBackdrop')closeSheets();const ep=e.target.closest('[data-edit-party]');if(ep)openParty(ep.dataset.editParty);const pp=e.target.closest('[data-party-project]');if(pp)openProject('',pp.dataset.partyProject);const vp=e.target.closest('[data-view-project]');if(vp)viewProject(vp.dataset.viewProject);const cardEntry=e.target.closest('[data-card-entry]');if(cardEntry){state.activeProject=state.projects.find(p=>p.id===cardEntry.dataset.projectId)||null;openEntry(cardEntry.dataset.cardEntry)}const cardMaterial=e.target.closest('[data-card-material]');if(cardMaterial)openMovement('project_issue','',cardMaterial.dataset.projectId);const vm=e.target.closest('[data-view-material]');if(vm)viewMaterial(vm.dataset.viewMaterial);const pm=e.target.closest('[data-purchase-material]');if(pm)openPurchaseBill(pm.dataset.purchaseMaterial);const im=e.target.closest('[data-issue-material]');if(im)openMovement('project_issue',im.dataset.issueMaterial);const vi=e.target.closest('[data-view-invoice]');if(vi)viewInvoice(vi.dataset.viewInvoice)});
$('#partySearch').addEventListener('input',renderParties);$('#projectSearch').addEventListener('input',renderProjects);$('#projectStatusFilter').addEventListener('change',renderProjects);$('#invoiceSearch').addEventListener('input',renderInvoices);$('#invoiceStatusFilter').addEventListener('change',renderInvoices);$('#materialSearch').addEventListener('input',renderInventory);$('#movementMaterial').addEventListener('change',updateMovementMaterial);
$$('input[name="projectPricingMode"]').forEach(x=>x.addEventListener('change',updateProjectPricing));bindDuration('#projectStart','#projectEnd','#projectDays');
$('#partyForm').addEventListener('submit',async e=>{e.preventDefault();const existing=state.parties.find(x=>x.id===$('#partyId').value),row={id:existing?.id||id('p'),name:$('#partyName').value.trim(),phone:$('#partyPhone').value.trim(),party_type:$('#partyType').value,address:$('#partyAddress').value.trim(),notes:$('#partyNotes').value.trim()};try{const saved=await store.save('parties',row,Boolean(existing)),i=state.parties.findIndex(x=>x.id===saved.id);i>=0?state.parties[i]=saved:state.parties.push(saved);closeSheets();render();toast(existing?'Party updated.':'Party added.')}catch(err){toast(err.message)}});
$('#projectNext').addEventListener('click',()=>{if(validProjectStep())setProjectStep(state.projectStep+1)});$('#projectBack').addEventListener('click',()=>setProjectStep(state.projectStep-1));
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();const row=projectFromForm(),existing=state.projects.some(x=>x.id===row.id);try{const saved=await store.save('projects',row,existing),i=state.projects.findIndex(x=>x.id===saved.id);i>=0?state.projects[i]=saved:state.projects.unshift(saved);closeSheets();render();toast(existing?'Project updated.':'Project created as a quotation.');viewProject(saved.id)}catch(err){toast(err.message)}});
$('#editProjectBtn').addEventListener('click',()=>openProject(state.activeProject?.id));$('#approveProjectBtn').addEventListener('click',()=>setProjectStatus('Approved'));$('#cancelProjectBtn').addEventListener('click',()=>setProjectStatus('Cancelled'));$('#scopeIncreaseBtn').addEventListener('click',()=>openEntry('scope_increase'));$('#scopeDecreaseBtn').addEventListener('click',()=>openEntry('scope_decrease'));$('#assignProjectMaterialBtn').addEventListener('click',()=>openMovement('project_issue','',state.activeProject?.id));$('#addProjectEntryBtn').addEventListener('click',()=>openEntry());$('#generateProjectInvoiceBtn').addEventListener('click',()=>openInvoice('',state.activeProject?.id));$('#printProjectBtn').addEventListener('click',()=>printSheet('#projectDetailSheet'));
$('#entryForm').addEventListener('submit',async e=>{e.preventDefault();const row={id:id('pe'),project_id:$('#entryProjectId').value,entry_type:$('#entryType').value,entry_date:$('#entryDate').value,description:$('#entryDescription').value.trim(),amount:Number($('#entryAmount').value),notes:$('#entryNotes').value.trim(),created_at:new Date().toISOString()};try{const saved=await store.save('project_entries',row,false);state.projectEntries.unshift(saved);closeSheets();render();toast(`${entryLabel(saved.entry_type)} saved.`);viewProject(row.project_id)}catch(err){toast(err.message)}});
$('#materialForm').addEventListener('submit',async e=>{e.preventDefault();const existing=state.materials.find(m=>m.id===$('#materialId').value),row={id:existing?.id||id('mat'),name:$('#materialName').value.trim(),category:$('#materialCategory').value.trim(),sku:$('#materialSku').value.trim(),unit:$('#materialUnit').value,reorder_level:Number($('#materialReorder').value||0),default_unit_cost:Number($('#materialDefaultCost').value||0),active:true,created_at:existing?.created_at||new Date().toISOString()};try{const saved=await store.save('materials',row,Boolean(existing)),i=state.materials.findIndex(m=>m.id===saved.id);i>=0?state.materials[i]=saved:state.materials.push(saved);closeSheets();render();toast(existing?'Material updated.':'Material added.')}catch(err){toast(err.message)}});
$('#movementForm').addEventListener('submit',async e=>{e.preventDefault();const material=state.materials.find(m=>m.id===$('#movementMaterial').value),type=$('#movementType').value,quantity=Number($('#movementQuantity').value),unitCost=Number($('#movementUnitCost').value),projectId=type==='project_issue'?$('#movementProject').value:null;if(type==='project_issue'&&quantity>materialMetrics(material).stock){toast(`Only ${qty(materialMetrics(material).stock)} ${material.unit} available.`);return}const row={id:id('mm'),material_id:material.id,project_id:projectId,movement_type:type,movement_date:$('#movementDate').value,quantity,unit_cost:unitCost,supplier_name:type==='purchase'?$('#movementSupplier').value.trim():null,reference:$('#movementReference').value.trim(),notes:$('#movementNotes').value.trim(),created_at:new Date().toISOString()};try{const saved=await store.save('material_movements',row,false);if(isCloud){await store.load()}else{state.materialMovements.unshift(saved);if(type==='project_issue')state.projectEntries.unshift({id:id('pe'),project_id:projectId,entry_type:'material',entry_date:row.movement_date,description:`Material: ${material.name} (${qty(quantity)} ${material.unit})`,amount:quantity*unitCost,notes:[row.reference,row.notes].filter(Boolean).join(' · '),created_at:new Date().toISOString()})}closeSheets();render();toast(type==='purchase'?'Material purchase recorded.':'Material assigned to project.')}catch(err){toast(err.message)}});
$('#editMaterialBtn').addEventListener('click',()=>openMaterial(state.activeMaterial?.id));$('#purchaseMaterialBtn').addEventListener('click',()=>openPurchaseBill(state.activeMaterial?.id));$('#issueMaterialBtn').addEventListener('click',()=>openMovement('project_issue',state.activeMaterial?.id));
$('#invoiceProject').addEventListener('change',setInvoiceAmount);$('#invoiceForm').addEventListener('submit',async e=>{e.preventDefault();const row=invoiceFromForm(),existing=state.invoices.some(x=>x.id===row.id),project=state.projects.find(x=>x.id===row.project_id);if(project?.status!=='Approved'){toast('Only approved projects can be invoiced.');return}try{const saved=await store.save('invoices',row,existing),i=state.invoices.findIndex(x=>x.id===saved.id);i>=0?state.invoices[i]=saved:state.invoices.unshift(saved);closeSheets();render();toast(existing?'Invoice updated.':'Invoice generated.');viewInvoice(saved.id)}catch(err){toast(err.message)}});$('#editInvoiceBtn').addEventListener('click',()=>openInvoice(state.activeInvoice?.id));$('#printInvoiceBtn').addEventListener('click',()=>printSheet('#invoiceDetailSheet'));
$('#profileBtn').addEventListener('click',()=>{if(isCloud&&confirm('Sign out of Mughal Interior Accounts?'))logout();else toast('Demo user · Supabase not connected')});$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').classList.add('hidden');try{await store.signIn($('#loginEmail').value,$('#loginPassword').value);await boot()}catch(err){$('#loginError').textContent=err.message;$('#loginError').classList.remove('hidden')}});
