// Dedicated daily recording workspace: receipts, expenses, labour and materials.
let operationTab='receipts';

const activeProjects=()=>state.projects.filter(p=>p.status==='Approved');
const activeOrders=()=>state.walkInOrders.filter(o=>o.status!=='Cancelled');
const activeAccounts=()=>state.paymentAccounts.filter(a=>a.active!==false);
const labourerName=id=>state.labourers.find(l=>l.id===id)?.name||'Unknown labour person';
const operationTargetName=(type,id)=>type==='project'?(state.projects.find(p=>p.id===id)?.name||'Unknown project'):(state.walkInOrders.find(o=>o.id===id)?.title||'Unknown order');
const operationAccountOptions=selected=>activeAccounts().map(a=>`<option value="${a.id}" ${a.id===selected?'selected':''}>${esc(a.name)}</option>`).join('');

function projectCard(p){
  const m=projectMetrics(p),approved=p.status==='Approved',schedule=p.start_date||p.expected_end_date?`${prettyDate(p.start_date)} – ${prettyDate(p.expected_end_date)}`:'Not scheduled';
  return `<article class="item-card project-card"><div class="project-card-head"><div><div class="project-card-number">${esc(p.project_number)}</div><h3>${esc(p.name)}</h3></div><span class="status ${statusClass(p.status)}">${esc(p.status)}</span></div><div class="project-card-info"><div><span>Party</span><b>${esc(partyName(p.party_id))}</b></div><div><span>Schedule</span><b>${schedule}</b></div><div><span>${approved?'Approved amount':'Quoted amount'}</span><b>${approved?money(m.revised):projectPriceText(p)}</b></div><div><span>Days</span><b>${p.days_to_complete??'Not set'}</b></div></div><div class="project-card-actions clean-actions"><button class="quick-btn view" data-view-project="${p.id}">View details</button><button class="quick-btn edit" data-edit-project-card="${p.id}">Edit project</button></div></article>`;
}

function walkInOrderCard(order){
  const m=walkInMetrics(order);
  return `<article class="item-card project-card walk-in-card"><div class="project-card-head"><div><div class="project-card-number">${esc(order.order_number)}</div><h3>${esc(order.title)}</h3><div class="walk-in-customer"><span>${esc(order.customer_name)}</span>${order.customer_phone?`<span>${esc(order.customer_phone)}</span>`:''}<span>Promised ${prettyDate(order.promised_date)}</span></div></div><span class="status ${statusClass(order.status)}">${esc(order.status)}</span></div><div class="project-card-info"><div><span>Order amount</span><b>${money(order.amount)}</b></div><div><span>Received</span><b>${money(m.receipts)}</b></div><div><span>Balance</span><b class="${m.balance>0?'order-balance':''}">${money(m.balance)}</b></div><div><span>Estimated profit</span><b>${money(m.profit)}</b></div></div><div class="project-card-actions clean-actions"><button class="quick-btn view" data-view-walk-in="${order.id}">View details</button><button class="quick-btn edit" data-edit-order-card="${order.id}">Edit order</button></div></article>`;
}

function materialCard(material){
  const m=materialMetrics(material);
  return `<article class="material-card ${m.low?'low':''}"><div class="material-head"><div><h3>${esc(material.name)}</h3><small>${esc(material.category||'Uncategorized')}${material.sku?` · ${esc(material.sku)}`:''}</small></div><span class="stock-pill">${m.low?'Low stock':'In stock'}</span></div><div class="material-stats"><div><span>Available</span><b>${qty(m.stock)} ${esc(material.unit)}</b></div><div><span>Avg. cost</span><b>${money(m.average)}</b></div><div><span>Stock value</span><b>${money(m.value)}</b></div></div><div class="material-actions clean-actions"><button class="quick-btn view" data-view-material="${material.id}">View ledger</button><button class="quick-btn edit" data-edit-material-card="${material.id}">Edit material</button><button class="quick-btn receipt" data-purchase-material="${material.id}">+ Purchase</button></div></article>`;
}

function operationPaymentRow(payment){
  const target=payment.project_id?operationTargetName('project',payment.project_id):payment.walk_in_order_id?operationTargetName('order',payment.walk_in_order_id):'General business';
  return `<article class="operation-row"><span class="operation-icon ${payment.payment_type}">${payment.payment_type==='customer_receipt'?'↓':'↑'}</span><div><b>${esc(payment.description)}</b><small>${esc(target)} · ${prettyDate(payment.payment_date)} · ${esc(paymentAccountName(payment.to_account_id||payment.from_account_id))}</small></div><strong class="${payment.payment_type==='expense'?'negative':''}">${money(payment.amount)}</strong></article>`;
}

function materialAssignmentRow(row){
  const material=state.materials.find(m=>m.id===row.material_id),type=row.project_id?'project':'order',target=operationTargetName(type,row.project_id||row.walk_in_order_id);
  return `<article class="operation-row"><span class="operation-icon material">▦</span><div><b>${esc(material?.name||'Material')}</b><small>${esc(target)} · ${prettyDate(row.movement_date)} · ${qty(row.quantity)} ${esc(material?.unit||'')}</small></div><strong>${money(Number(row.quantity)*Number(row.unit_cost))}</strong></article>`;
}

function renderOperations(){
  if(!$('#operationsView'))return;
  $$('[data-operation-tab]').forEach(b=>b.classList.toggle('active',b.dataset.operationTab===operationTab));$$('.operation-panel').forEach(p=>p.classList.toggle('active',p.id===`operation${operationTab[0].toUpperCase()+operationTab.slice(1)}Panel`));
  const receipts=state.payments.filter(p=>p.payment_type==='customer_receipt'),receiptTotal=receipts.reduce((s,p)=>s+Number(p.amount||0),0),projectDue=activeProjects().reduce((s,p)=>s+Math.max(0,projectMetrics(p).balance),0),orderDue=activeOrders().reduce((s,o)=>s+Math.max(0,walkInMetrics(o).balance),0);
  $('#operationReceiptSummary').innerHTML=`<article><span>Total receipts</span><b>${money(receiptTotal)}</b></article><article><span>Project balances</span><b>${money(projectDue)}</b></article><article><span>Order balances</span><b>${money(orderDue)}</b></article>`;
  $('#operationReceiptList').innerHTML=receipts.length?receipts.slice(0,50).map(operationPaymentRow).join(''):reportEmpty('No receipts recorded','Use Record receipt and choose a project or order.');
  const expenses=state.payments.filter(p=>p.payment_type==='expense'),expenseTotal=expenses.reduce((s,p)=>s+Number(p.amount||0),0),general=expenses.filter(p=>!p.project_id&&!p.walk_in_order_id).reduce((s,p)=>s+Number(p.amount||0),0),assigned=expenseTotal-general;
  $('#operationExpenseSummary').innerHTML=`<article><span>Total expenses</span><b>${money(expenseTotal)}</b></article><article><span>General</span><b>${money(general)}</b></article><article><span>Assigned to jobs</span><b>${money(assigned)}</b></article>`;
  $('#operationExpenseList').innerHTML=expenses.length?expenses.slice(0,50).map(operationPaymentRow).join(''):reportEmpty('No expenses recorded','Record a general expense or assign it to a project or order.');
  $('#labourerList').innerHTML=state.labourers.length?state.labourers.map(l=>`<article class="labourer-card"><div><b>${esc(l.name)}</b><small>${esc(l.mobile||'No mobile')}${l.cnic?` · ${esc(l.cnic)}`:''}</small><span>${esc(l.home_address||'Address not entered')}</span></div><div><strong>${money(l.daily_wage_rate)}/day</strong><button class="mini-btn" data-edit-labourer="${l.id}">Edit</button></div></article>`).join(''):reportEmpty('No labour persons','Add names and wage rates before assigning labour.');
  $('#labourAssignmentList').innerHTML=state.labourAssignments.length?state.labourAssignments.slice(0,50).map(a=>{const type=a.project_id?'project':'order';return `<article class="operation-row"><span class="operation-icon labour">L</span><div><b>${esc(labourerName(a.labourer_id))}</b><small>${esc(operationTargetName(type,a.project_id||a.walk_in_order_id))} · ${prettyDate(a.assignment_date)} · ${qty(a.days)} days</small></div><strong>${money(a.amount??Number(a.days)*Number(a.daily_rate))}</strong></article>`}).join(''):reportEmpty('No wages assigned','Assign full or half days to a project or order.');
  const assignments=state.materialMovements.filter(m=>['project_issue','walk_in_issue'].includes(m.movement_type)),assignedValue=assignments.reduce((s,m)=>s+Number(m.quantity)*Number(m.unit_cost),0);
  $('#operationMaterialSummary').innerHTML=`<article><span>Assignments</span><b>${assignments.length}</b></article><article><span>Assigned value</span><b>${money(assignedValue)}</b></article><article><span>Materials in stock</span><b>${state.materials.length}</b></article>`;
  $('#operationMaterialList').innerHTML=assignments.length?assignments.slice(0,50).map(materialAssignmentRow).join(''):reportEmpty('No materials assigned','Assign inventory to an approved project or active order.');
}

function showOperationTab(tab){operationTab=tab;navigate('operations');renderOperations()}
function fillJobTarget(select,type,selected=''){
  const rows=type==='project'?activeProjects():activeOrders();select.innerHTML=`<option value="">Select ${type}</option>`+rows.map(row=>`<option value="${row.id}">${esc(type==='project'?`${row.name} — ${partyName(row.party_id)}`:`${row.title} — ${row.customer_name}`)}</option>`).join('');if(selected)select.value=selected;return rows;
}
function targetBalance(type,id){const row=type==='project'?state.projects.find(p=>p.id===id):state.walkInOrders.find(o=>o.id===id);return row?Math.max(0,type==='project'?projectMetrics(row).balance:walkInMetrics(row).balance):0}

function openReceiptEntry(){
  if(!activeAccounts().length){toast('Add a cash or bank account first.');return}if(!activeProjects().length&&!activeOrders().length){toast('Approve a project or create an order first.');return}
  $('#receiptEntryForm').reset();$('#receiptEntryDate').value=today();$('#receiptTargetType').value=activeProjects().length?'project':'order';$('#receiptAccount').innerHTML=operationAccountOptions();updateReceiptTargets();closeSheets();openSheet('#receiptEntrySheet');
}
function updateReceiptTargets(){const type=$('#receiptTargetType').value;fillJobTarget($('#receiptTarget'),type);updateReceiptBalance()}
function updateReceiptBalance(){const balance=targetBalance($('#receiptTargetType').value,$('#receiptTarget').value);$('#receiptBalanceText').textContent=`Balance: ${money(balance)}`;$('#receiptAmount').max=String(balance||'')}

function openExpenseEntry(){if(!activeAccounts().length){toast('Add a cash or bank account first.');return}$('#expenseEntryForm').reset();$('#expenseEntryDate').value=today();$('#expenseAccount').innerHTML=operationAccountOptions();updateExpenseTarget();closeSheets();openSheet('#expenseEntrySheet')}
function updateExpenseTarget(){const scope=$('#expenseScope').value,assigned=scope!=='general';$('#expenseTargetWrap').classList.toggle('hidden',!assigned);$('#expenseTarget').required=assigned;if(assigned)fillJobTarget($('#expenseTarget'),scope)}

async function recordOperationPayment(input){
  if(isCloud){const paymentId=await store.request('/rest/v1/rpc/record_payment',{method:'POST',body:JSON.stringify({p_business_id:state.businessId,p_payment_type:input.payment_type,p_payment_date:input.payment_date,p_from_account_id:input.from_account_id||null,p_to_account_id:input.to_account_id||null,p_party_id:input.party_id||null,p_supplier_id:null,p_project_id:input.project_id||null,p_walk_in_order_id:input.walk_in_order_id||null,p_purchase_bill_id:null,p_invoice_id:input.invoice_id||null,p_description:input.description,p_amount:input.amount,p_reference:input.reference||null,p_notes:input.notes||null})});await store.load();return paymentId}
  const paymentId=await recordPaymentLocal(input);if(input.payment_type==='customer_receipt'){const base={id:id('entry'),entry_type:'receipt',entry_date:input.payment_date,description:input.description,amount:input.amount,notes:input.notes||'',created_at:new Date().toISOString()};if(input.project_id)state.projectEntries.unshift({...base,project_id:input.project_id});else state.walkInOrderEntries.unshift({...base,walk_in_order_id:input.walk_in_order_id})}return paymentId;
}

function openLabourer(labourerId=''){const l=state.labourers.find(x=>x.id===labourerId);$('#labourerForm').reset();$('#labourerId').value=l?.id||'';$('#labourerName').value=l?.name||'';$('#labourerCnic').value=l?.cnic||'';$('#labourerMobile').value=l?.mobile||'';$('#labourerAddress').value=l?.home_address||'';$('#labourerRate').value=l?.daily_wage_rate??'';$('#labourerSheetTitle').textContent=l?'Edit labour person':'Add labour person';closeSheets();openSheet('#labourerSheet')}
function openLabourAssignment(){if(!state.labourers.length){toast('Add a labour person first.');openLabourer();return}if(!activeProjects().length&&!activeOrders().length){toast('Approve a project or create an order first.');return}$('#labourAssignmentForm').reset();$('#labourAssignmentPerson').innerHTML=state.labourers.map(l=>`<option value="${l.id}">${esc(l.name)} — ${money(l.daily_wage_rate)}/day</option>`).join('');$('#labourAssignmentDate').value=today();$('#labourTargetType').value=activeProjects().length?'project':'order';updateLabourTarget();updateLabourRate();closeSheets();openSheet('#labourAssignmentSheet')}
function updateLabourTarget(){fillJobTarget($('#labourTarget'),$('#labourTargetType').value)}
function updateLabourRate(){const l=state.labourers.find(x=>x.id===$('#labourAssignmentPerson').value);$('#labourDailyRate').value=l?.daily_wage_rate??0;updateLabourTotal()}
function updateLabourTotal(){$('#labourTotal').textContent=money(Number($('#labourDays').value||0)*Number($('#labourDailyRate').value||0))}

function openOperationMaterial(){if(!state.materials.length){toast('Add inventory materials first.');return}if(!activeProjects().length&&!activeOrders().length){toast('Approve a project or create an order first.');return}$('#operationMaterialForm').reset();$('#operationMaterial').innerHTML=state.materials.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('');$('#operationMaterialDate').value=today();$('#materialTargetType').value=activeProjects().length?'project':'order';updateMaterialTarget();updateOperationMaterial();closeSheets();openSheet('#operationMaterialSheet')}
function updateMaterialTarget(){fillJobTarget($('#materialTarget'),$('#materialTargetType').value)}
function updateOperationMaterial(){const m=state.materials.find(x=>x.id===$('#operationMaterial').value),metrics=m?materialMetrics(m):{stock:0,average:0};$('#operationMaterialStock').textContent=`Available stock: ${qty(metrics.stock)} ${m?.unit||''}`;$('#operationMaterialRate').value=(metrics.average||m?.default_unit_cost||0).toFixed(2)}

function openProjectApproval(){
  const p=state.activeProject;if(!p)return;const choices=[];
  if(p.pricing_mode!=='without_material'&&Number(p.price_with_material)>0)choices.push({value:'with_material',label:'With material',amount:p.price_with_material,note:'Material and labour included'});
  if(p.pricing_mode!=='with_material'&&Number(p.price_without_material)>0)choices.push({value:'without_material',label:'Without material',amount:p.price_without_material,note:'Labour only; customer supplies material'});
  if(!choices.length){toast('Add a valid quotation amount before approval.');return}
  $('#projectApprovalChoices').innerHTML=choices.map((c,i)=>`<label class="approval-choice"><input type="radio" name="approvalContractType" value="${c.value}" ${i===0?'checked':''}><span><b>${c.label}</b><small>${c.note}</small></span><strong>${money(c.amount)}</strong></label>`).join('');closeSheets();openSheet('#projectApprovalSheet');
}
async function setProjectStatus(status){if(!state.activeProject)return;if(status==='Approved'){openProjectApproval();return}const row={...state.activeProject,status};try{const saved=await store.save('projects',row,true);state.projects[state.projects.findIndex(x=>x.id===saved.id)]=saved;state.activeProject=saved;render();viewProject(saved.id);toast(`Project marked ${status.toLowerCase()}.`)}catch(err){toast(err.message)}}

$$('[data-operation-tab]').forEach(b=>b.addEventListener('click',()=>{operationTab=b.dataset.operationTab;renderOperations()}));
document.addEventListener('click',event=>{const opener=event.target.closest('[data-open-operation]');if(opener)showOperationTab(opener.dataset.openOperation);const action=event.target.closest('[data-action]')?.dataset.action;if(action==='record-receipt')openReceiptEntry();if(action==='record-expense')openExpenseEntry();if(action==='add-labourer')openLabourer();if(action==='assign-labour')openLabourAssignment();if(action==='assign-operation-material')openOperationMaterial();const ep=event.target.closest('[data-edit-project-card]');if(ep)openProject(ep.dataset.editProjectCard);const eo=event.target.closest('[data-edit-order-card]');if(eo)openWalkInOrder(eo.dataset.editOrderCard);const em=event.target.closest('[data-edit-material-card]');if(em)openMaterial(em.dataset.editMaterialCard);const el=event.target.closest('[data-edit-labourer]');if(el)openLabourer(el.dataset.editLabourer)});

$('#receiptTargetType').addEventListener('change',updateReceiptTargets);$('#receiptTarget').addEventListener('change',updateReceiptBalance);$('#expenseScope').addEventListener('change',updateExpenseTarget);$('#labourTargetType').addEventListener('change',updateLabourTarget);$('#labourAssignmentPerson').addEventListener('change',updateLabourRate);$('#labourDays').addEventListener('input',updateLabourTotal);$('#labourDailyRate').addEventListener('input',updateLabourTotal);$('#materialTargetType').addEventListener('change',updateMaterialTarget);$('#operationMaterial').addEventListener('change',updateOperationMaterial);

$('#receiptEntryForm').addEventListener('submit',async event=>{event.preventDefault();const type=$('#receiptTargetType').value,targetId=$('#receiptTarget').value,balance=targetBalance(type,targetId),amount=Number($('#receiptAmount').value);if(amount>balance){toast(`Receipt cannot exceed the ${money(balance)} balance.`);return}const project=type==='project'?state.projects.find(p=>p.id===targetId):null,order=type==='order'?state.walkInOrders.find(o=>o.id===targetId):null;try{await recordOperationPayment({payment_type:'customer_receipt',payment_date:$('#receiptEntryDate').value,to_account_id:$('#receiptAccount').value,party_id:project?.party_id||order?.party_id||null,project_id:project?.id||null,walk_in_order_id:order?.id||null,invoice_id:project?state.invoices.find(i=>i.project_id===project.id)?.id||null:null,description:$('#receiptDescription').value.trim(),amount,reference:$('#receiptReference').value.trim(),notes:$('#receiptNotes').value.trim()});closeSheets();render();showOperationTab('receipts');toast('Customer receipt recorded.')}catch(err){toast(err.message)}});

$('#expenseEntryForm').addEventListener('submit',async event=>{event.preventDefault();const scope=$('#expenseScope').value,targetId=$('#expenseTarget').value;try{await recordOperationPayment({payment_type:'expense',payment_date:$('#expenseEntryDate').value,from_account_id:$('#expenseAccount').value,project_id:scope==='project'?targetId:null,walk_in_order_id:scope==='order'?targetId:null,description:$('#expenseDescription').value.trim(),amount:Number($('#expenseAmount').value),reference:$('#expenseReference').value.trim(),notes:$('#expenseNotes').value.trim()});closeSheets();render();showOperationTab('expenses');toast('Expense recorded.')}catch(err){toast(err.message)}});

$('#labourerForm').addEventListener('submit',async event=>{event.preventDefault();const existing=state.labourers.find(l=>l.id===$('#labourerId').value),row={id:existing?.id||id('lab'),name:$('#labourerName').value.trim(),cnic:$('#labourerCnic').value.trim()||null,mobile:$('#labourerMobile').value.trim()||null,home_address:$('#labourerAddress').value.trim()||null,daily_wage_rate:Number($('#labourerRate').value),active:true,created_at:existing?.created_at||new Date().toISOString(),updated_at:new Date().toISOString()};try{const saved=await store.save('labourers',row,Boolean(existing)),i=state.labourers.findIndex(l=>l.id===saved.id);i>=0?state.labourers[i]=saved:state.labourers.push(saved);closeSheets();render();showOperationTab('labour');toast(existing?'Labour person updated.':'Labour person added.')}catch(err){toast(err.message)}});

$('#labourAssignmentForm').addEventListener('submit',async event=>{event.preventDefault();const type=$('#labourTargetType').value,days=Number($('#labourDays').value),rate=Number($('#labourDailyRate').value),row={id:id('la'),labourer_id:$('#labourAssignmentPerson').value,project_id:type==='project'?$('#labourTarget').value:null,walk_in_order_id:type==='order'?$('#labourTarget').value:null,assignment_date:$('#labourAssignmentDate').value,days,daily_rate:rate,notes:$('#labourAssignmentNotes').value.trim()||null,created_at:new Date().toISOString()};try{const saved=await store.save('labour_assignments',row,false);if(isCloud)await store.load();else{saved.amount=days*rate;state.labourAssignments.unshift(saved);const l=state.labourers.find(x=>x.id===row.labourer_id),entry={id:id('entry'),entry_type:'labour',entry_date:row.assignment_date,description:`Labour: ${l?.name} (${qty(days)} days × ${money(rate)})`,amount:days*rate,notes:row.notes||'',created_at:new Date().toISOString()};if(row.project_id)state.projectEntries.unshift({...entry,project_id:row.project_id});else state.walkInOrderEntries.unshift({...entry,walk_in_order_id:row.walk_in_order_id})}closeSheets();render();showOperationTab('labour');toast('Labour wages assigned.')}catch(err){toast(err.message)}});

$('#operationMaterialForm').addEventListener('submit',async event=>{event.preventDefault();const type=$('#materialTargetType').value,material=state.materials.find(m=>m.id===$('#operationMaterial').value),quantity=Number($('#operationMaterialQty').value),unitCost=Number($('#operationMaterialRate').value),available=materialMetrics(material).stock;if(quantity>available){toast(`Only ${qty(available)} ${material.unit} available.`);return}const row={id:id('mm'),material_id:material.id,project_id:type==='project'?$('#materialTarget').value:null,walk_in_order_id:type==='order'?$('#materialTarget').value:null,movement_type:type==='project'?'project_issue':'walk_in_issue',movement_date:$('#operationMaterialDate').value,quantity,unit_cost:unitCost,supplier_name:null,reference:$('#operationMaterialReference').value.trim()||null,notes:$('#operationMaterialNotes').value.trim()||null,created_at:new Date().toISOString()};try{const saved=await store.save('material_movements',row,false);if(isCloud)await store.load();else{state.materialMovements.unshift(saved);const entry={id:id('entry'),entry_type:'material',entry_date:row.movement_date,description:`Material: ${material.name} (${qty(quantity)} ${material.unit})`,amount:quantity*unitCost,notes:[row.reference,row.notes].filter(Boolean).join(' · '),created_at:new Date().toISOString()};if(row.project_id)state.projectEntries.unshift({...entry,project_id:row.project_id});else state.walkInOrderEntries.unshift({...entry,walk_in_order_id:row.walk_in_order_id})}closeSheets();render();showOperationTab('materials');toast('Material assigned and stock reduced.')}catch(err){toast(err.message)}});

$('#projectApprovalForm').addEventListener('submit',async event=>{event.preventDefault();const p=state.activeProject,type=$('input[name="approvalContractType"]:checked')?.value;if(!p||!type)return;const amount=type==='with_material'?Number(p.price_with_material):Number(p.price_without_material),row={...p,status:'Approved',contract_type:type,original_contract_amount:amount};try{const saved=await store.save('projects',row,true);state.projects[state.projects.findIndex(x=>x.id===saved.id)]=saved;state.activeProject=saved;closeSheets();render();viewProject(saved.id);toast(`Project approved ${type==='with_material'?'with material':'without material'}.`)}catch(err){toast(err.message)}});
