(() => {
  const reportState={type:null,scope:'overall',csv:[]};
  const scopedReports=new Set(['profit','receivables','expenses','labourAssigned','materialCost']);
  const definitions={
    profit:{title:'Profit report',filters:['date']},receivables:{title:'Receivable report',filters:['date']},expenses:{title:'Expenses report',filters:['date']},
    labourAssigned:{title:'Labour assigned',filters:['date']},materialCost:{title:'Material Cost',filters:['date']},supplierPayables:{title:'Supplier payables report',filters:['supplier']},
    purchases:{title:'Overall Purchases report',filters:['date','supplier']},materialMovement:{title:'Material movement report',filters:['date','material']},
    materialQuantity:{title:'Material quantity',filters:['material']},labourStatement:{title:'Labour statement',filters:['date','labour']},bankStatement:{title:'Bank Statement',filters:['date','account']}
  };
  const num=value=>Number(value||0);
  const sum=(rows,pick)=>rows.reduce((total,row)=>total+num(pick(row)),0);
  const inRange=value=>{const day=String(value||'').slice(0,10),from=$('#reportFrom').value,to=$('#reportTo').value;return(!from||day>=from)&&(!to||day<=to)};
  const beforeFrom=value=>{const from=$('#reportFrom').value;return Boolean(from&&String(value||'').slice(0,10)<from)};
  const reportEmpty=(title,message)=>`<div class="report-empty"><b>${esc(title)}</b><span>${esc(message)}</span></div>`;
  const table=(headers,rows,classes='')=>`<div class="report-table-wrap"><table class="report-table ${classes}"><thead><tr>${headers.map(label=>`<th>${esc(label)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
  const projectName=id=>{const row=project(id);return row?`${row.name} - ${party(row.party_id)?.name||''}`:''};
  const orderName=id=>{const row=walkInOrder(id);return row?`${row.order_number} - ${row.customer_name}`:''};
  const targetName=row=>row.project_id?projectName(row.project_id):row.walk_in_order_id?orderName(row.walk_in_order_id):row.supplier_id?supplier(row.supplier_id)?.name||'Supplier':row.labourer_id?labourer(row.labourer_id)?.name||'Labour':row.party_id?party(row.party_id)?.name||'Party':'Overall business';
  const movementIn=row=>['purchase','adjustment_in','project_return','walk_in_return'].includes(row.movement_type);
  const movementOut=row=>['project_issue','walk_in_issue','adjustment_out'].includes(row.movement_type);
  const movementName=type=>({purchase:'Purchase',adjustment_in:'Stock adjustment in',adjustment_out:'Stock adjustment out',project_issue:'Assigned to project',project_return:'Returned from project',walk_in_issue:'Assigned to order',walk_in_return:'Returned from order'}[type]||type);
  const jobMaterialCost=(kind,id)=>state.materialMovements.filter(row=>(kind==='project'?row.project_id===id:row.walk_in_order_id===id)).reduce((total,row)=>total+(movementOut(row)?1:movementIn(row)?-1:0)*num(row.quantity)*num(row.unit_cost),0);
  const jobLabourCost=(kind,id)=>sum(state.labourAssignments.filter(row=>kind==='project'?row.project_id===id:row.walk_in_order_id===id),assignmentAmount);
  function allExpenseRows(){
    const paymentIds=new Set(state.payments.filter(row=>row.payment_type==='expense').map(row=>row.id));
    return [
      ...state.payments.filter(row=>row.payment_type==='expense').map(row=>({...row,expense_date:row.payment_date,source:'payment'})),
      ...state.entries.filter(row=>row.entry_type==='expense'&&(!row.payment_id||!paymentIds.has(row.payment_id))).map(row=>({...row,expense_date:row.entry_date,source:'project'})),
      ...state.walkInEntries.filter(row=>row.entry_type==='expense'&&(!row.payment_id||!paymentIds.has(row.payment_id))).map(row=>({...row,expense_date:row.entry_date,source:'order'}))
    ];
  }
  const jobExpenseCost=(kind,id)=>sum(allExpenseRows().filter(row=>kind==='project'?row.project_id===id:row.walk_in_order_id===id),row=>row.amount);
  const jobReceipts=(kind,id)=>sum(state.payments.filter(row=>row.payment_type==='customer_receipt'&&(kind==='project'?row.project_id===id:row.walk_in_order_id===id)),row=>row.amount);
  function jobRows(){
    const projects=state.projects.filter(row=>row.status==='Approved').map(row=>{const revenue=projectMetrics(row).revised,materials=jobMaterialCost('project',row.id),labour=jobLabourCost('project',row.id),expenses=jobExpenseCost('project',row.id),received=jobReceipts('project',row.id);return{kind:'project',id:row.id,number:row.project_number,name:row.name,customer:party(row.party_id)?.name||'',day:row.quote_date,revenue,materials,labour,expenses,cost:materials+labour+expenses,received,balance:revenue-received}});
    const orders=state.walkInOrders.filter(row=>row.status!=='Cancelled').map(row=>{const revenue=num(row.amount),materials=jobMaterialCost('order',row.id),labour=jobLabourCost('order',row.id),expenses=jobExpenseCost('order',row.id),received=jobReceipts('order',row.id);return{kind:'order',id:row.id,number:row.order_number,name:row.title||'Order invoice',customer:row.customer_name||'',day:row.order_date,revenue,materials,labour,expenses,cost:materials+labour+expenses,received,balance:revenue-received}});
    return [...projects,...orders].filter(row=>reportState.scope==='overall'||reportState.scope===`${row.kind}s`).filter(row=>inRange(row.day)).filter(row=>row.kind!=='project'||$('#reportProject').value==='all'||row.id===$('#reportProject').value).filter(row=>row.kind!=='order'||$('#reportOrder').value==='all'||row.id===$('#reportOrder').value);
  }
  function setOutput(content,csv){$('#reportContent').innerHTML=content;reportState.csv=csv;}
  const statementProject=()=>reportState.type==='receivables'&&reportState.scope==='projects'&&$('#reportProject').value!=='all'?project($('#reportProject').value):null;
  const reportPeriod=()=>!definitions[reportState.type]?.filters.includes('date')||!$('#reportFrom').value&&!$('#reportTo').value?'All Dates':`${date($('#reportFrom').value)||'Beginning'} to ${date($('#reportTo').value)||'Latest entry'}`;
  const validReportDates=()=>!definitions[reportState.type]?.filters.includes('date')||!$('#reportFrom').value||!$('#reportTo').value||$('#reportFrom').value<=$('#reportTo').value;
  function clearReportDates(){['#reportFrom','#reportTo'].forEach(selector=>$(selector).value='');renderCurrent();}
  function projectStatementRows(job){
    const invoice=state.invoices.find(row=>row.project_id===job.id),metric=projectMetrics(job);
    // Use the invoice date, not the quotation date, when the invoice exists.
    const invoiceDay=invoice?.invoice_date||job.quote_date||String(job.created_at||'').slice(0,10);
    const events=[{day:invoiceDay,id:invoice?.id||job.id,rank:0,created:'',description:'Original project amount',reference:invoice?.invoice_number||job.project_number||'',charge:metric.original,receipt:0},
      ...metric.entries.filter(row=>['scope_increase','scope_decrease'].includes(row.entry_type)).map(row=>({day:row.entry_date,id:row.id,rank:1,created:row.created_at||'',description:row.entry_type==='scope_decrease'?'Scope deduction':'Scope addition',details:row.description||'',reference:'',charge:(row.entry_type==='scope_decrease'?-1:1)*num(row.amount),receipt:0})),
      // Project-entry receipts mirror payments; read payments only to avoid double counting.
      ...state.payments.filter(row=>row.project_id===job.id&&row.payment_type==='customer_receipt').map(row=>({day:row.payment_date,id:row.id,rank:2,created:row.created_at||'',description:'Payment received',details:row.description||'',reference:row.payment_number||'',charge:0,receipt:num(row.amount)}))
    ].sort((a,b)=>String(a.day||'').localeCompare(String(b.day||''))||a.rank-b.rank||a.created.localeCompare(b.created)||String(a.id||'').localeCompare(String(b.id||'')));
    const cents=value=>Math.round(num(value)*100);
    let balance=events.filter(row=>beforeFrom(row.day)).reduce((total,row)=>total+cents(row.charge)-cents(row.receipt),0);
    const opening=balance/100,rows=[];
    if($('#reportFrom').value)rows.push({day:$('#reportFrom').value,description:'Opening balance brought forward',reference:'',charge:opening,receipt:null,balance:opening,opening:true});
    let charges=0,receipts=0;
    events.filter(row=>inRange(row.day)).forEach(row=>{const charge=cents(row.charge),receipt=cents(row.receipt);balance+=charge-receipt;charges+=charge;receipts+=receipt;rows.push({...row,balance:balance/100})});
    return{rows,opening,charges:charges/100,receipts:receipts/100,closing:balance/100};
  }
  function renderProjectStatement(job){
    if(job.status!=='Approved'){setOutput(reportEmpty('No approved project invoice','This project is still a quotation and has no invoiced receivable.'),[]);return;}
    const customer=party(job.party_id),ledger=projectStatementRows(job);
    const body=ledger.rows.map(row=>`<tr class="${row.opening?'statement-opening':''}"><td>${date(row.day)}</td><td><b>${esc(row.description)}</b>${row.reference?`<small>${esc(row.reference)}</small>`:''}${row.details?`<small>${esc(row.details)}</small>`:''}</td><td class="number ${row.charge<0?'report-negative':''}">${row.charge||row.opening?money(row.charge):''}</td><td class="number report-positive">${row.receipt?money(row.receipt):''}</td><td class="number report-balance ${row.balance<0?'report-positive':''}">${money(row.balance)}</td></tr>`);
    body.push(`<tr class="statement-total"><td></td><td><b>Period totals / closing balance</b></td><td class="number">${money(ledger.charges)}</td><td class="number report-positive">${money(ledger.receipts)}</td><td class="number ${ledger.closing<0?'report-positive':''}">${money(ledger.closing)}</td></tr>`);
    const html=`<article class="project-statement"><header class="statement-heading"><div><p>PROJECT RECEIVABLE STATEMENT</p><h2>${esc(state.business?.name||'Mughal Interior')}</h2><span>${esc(reportPeriod())}</span></div><img src="assets/mughal-logo.png" alt="Company logo"></header><div class="statement-parties"><div><small>CUSTOMER</small><b>${esc(customer?.name||'')}</b><span>${esc(customer?.phone||'')}</span><span>${esc(customer?.address||'')}</span></div><div><small>PROJECT</small><b>${esc(job.name)}</b><span>${esc(job.project_number||'')}</span><span>${esc(job.location||'')}</span></div></div>${table(['Date','Description / reference','Project amount / opening','Receipts','Balance'],body,'statement-table')}<p class="statement-note">${ledger.closing<0?'Negative balance represents customer credit.':'Balance represents the amount receivable from the customer.'} Period totals exclude the opening balance. Generated ${esc(date(today()))}.</p></article>`;
    setOutput(html,[['Project receivable statement'],['Business',state.business?.name||'Mughal Interior'],['Customer',customer?.name||''],['Project',job.name],['Project ID',job.project_number||''],['Period',reportPeriod()],[],['Date','Description','Reference','Details','Project amount / opening','Receipts','Balance'],...ledger.rows.map(row=>[row.day,row.description,row.reference,row.details||'',row.charge,row.receipt??'',row.balance]),['','Period totals / closing balance','','',ledger.charges,ledger.receipts,ledger.closing]]);
  }
  function renderProfit(){
    const rows=jobRows(),revenue=sum(rows,row=>row.revenue),direct=sum(rows,row=>row.cost),overheads=reportState.scope==='overall'?sum(state.payments.filter(row=>row.payment_type==='expense'&&!row.project_id&&!row.walk_in_order_id&&inRange(row.payment_date)),row=>row.amount):0,profit=revenue-direct-overheads,margin=revenue?profit/revenue*100:0;
    const body=rows.map(row=>`<tr><td><b>${esc(row.name)}</b><small>${esc(row.number)} · ${esc(row.customer)}</small></td><td class="number">${money(row.revenue)}</td><td class="number">${money(row.materials)}</td><td class="number">${money(row.labour)}</td><td class="number">${money(row.expenses)}</td><td class="number">${money(row.revenue-row.cost)}</td></tr>`);
    const csv=[['Number','Type','Project / order','Customer','Date','Sales','Material','Labour','Expenses','Profit'],...rows.map(row=>[row.number,row.kind,row.name,row.customer,row.day,row.revenue,row.materials,row.labour,row.expenses,row.revenue-row.cost])];
    if(overheads){body.push(`<tr><td><b>Business overheads</b></td><td class="number">${money(0)}</td><td class="number">${money(0)}</td><td class="number">${money(0)}</td><td class="number">${money(overheads)}</td><td class="number report-negative">${money(-overheads)}</td></tr>`);csv.push(['','business','Business overheads','','',0,0,0,overheads,-overheads]);}
    if(rows.length||overheads){body.push(`<tr class="statement-total"><td><b>Net profit / loss</b></td><td class="number">${money(revenue)}</td><td class="number">${money(sum(rows,row=>row.materials))}</td><td class="number">${money(sum(rows,row=>row.labour))}</td><td class="number">${money(sum(rows,row=>row.expenses)+overheads)}</td><td class="number ${profit<0?'report-negative':'report-positive'}">${money(profit)}</td></tr>`);csv.push(['','','Net profit / loss','','',revenue,sum(rows,row=>row.materials),sum(rows,row=>row.labour),sum(rows,row=>row.expenses)+overheads,profit]);}
    setOutput(body.length?table(['Project / order','Sales','Material','Labour','Expenses','Profit'],body):reportEmpty('No profit data','No matching approved projects or orders.'),csv);
  }
  function renderReceivables(){
    const selectedProject=statementProject();if(selectedProject){renderProjectStatement(selectedProject);return;}
    const rows=jobRows(),sales=sum(rows,row=>row.revenue),received=sum(rows,row=>row.received),balance=sales-received;
    const body=rows.map(row=>`<tr><td><b>${esc(row.name)}</b><small>${esc(row.number)} · ${esc(row.customer)}</small></td><td class="number">${money(row.revenue)}</td><td class="number report-positive">${money(row.received)}</td><td class="number ${row.balance<0?'report-positive':row.balance>0?'report-negative':''}">${money(row.balance)}</td></tr>`);
    setOutput(rows.length?table(['Project / order','Invoice','Received','Balance'],body,'compact'):reportEmpty('No receivables','No matching projects or orders.'),[['Number','Type','Project / order','Customer','Invoice','Received','Balance'],...rows.map(row=>[row.number,row.kind,row.name,row.customer,row.revenue,row.received,row.balance])]);
  }
  function expenseRows(){return allExpenseRows().filter(row=>inRange(row.expense_date)).filter(row=>reportState.scope==='overall'||reportState.scope==='projects'&&row.project_id||reportState.scope==='orders'&&row.walk_in_order_id).filter(row=>reportState.scope!=='projects'||$('#reportProject').value==='all'||row.project_id===$('#reportProject').value).filter(row=>reportState.scope!=='orders'||$('#reportOrder').value==='all'||row.walk_in_order_id===$('#reportOrder').value)}
  function renderExpenses(){
    const rows=expenseRows(),general=sum(rows.filter(row=>!row.project_id&&!row.walk_in_order_id),row=>row.amount),projects=sum(rows.filter(row=>row.project_id),row=>row.amount),orders=sum(rows.filter(row=>row.walk_in_order_id),row=>row.amount);
    const body=rows.map(row=>`<tr><td>${date(row.expense_date)}</td><td><b>${esc(expenseCategory(row.expense_category_id)?.name||row.description||'Expense')}</b><small>${esc(row.notes||'')}</small></td><td>${esc(targetName(row))}</td><td>${esc(account(row.from_account_id)?.name||'Charged')}</td><td class="number">${money(row.amount)}</td></tr>`);
    setOutput(rows.length?table(['Date','Expense','Charged to','Account','Amount'],body):reportEmpty('No expenses','No matching expense entries.'),[['Date','Expense','Details','Charged to','Account','Amount'],...rows.map(row=>[row.expense_date,expenseCategory(row.expense_category_id)?.name||row.description,row.notes,targetName(row),account(row.from_account_id)?.name||'Charged',row.amount])]);
  }
  function assignedRows(){return state.labourAssignments.filter(row=>inRange(row.assignment_date)).filter(row=>reportState.scope==='overall'||reportState.scope==='projects'&&row.project_id||reportState.scope==='orders'&&row.walk_in_order_id).filter(row=>reportState.scope!=='projects'||$('#reportProject').value==='all'||row.project_id===$('#reportProject').value).filter(row=>reportState.scope!=='orders'||$('#reportOrder').value==='all'||row.walk_in_order_id===$('#reportOrder').value)}
  function renderLabourAssigned(){
    const rows=assignedRows(),days=sum(rows,row=>row.days),wages=sum(rows,assignmentAmount);
    const body=rows.map(row=>`<tr><td>${date(row.assignment_date)}</td><td><b>${esc(labourer(row.labourer_id)?.name||'Labour')}</b><small>${esc(row.notes||'')}</small></td><td>${esc(targetName(row))}</td><td class="number">${qty(row.days)}</td><td class="number">${money(row.daily_rate)}</td><td class="number">${money(assignmentAmount(row))}</td></tr>`);
    setOutput(rows.length?table(['Date','Labour','Project / order','Days','Rate','Cost'],body):reportEmpty('No labour assigned','No matching labour assignments.'),[['Date','Labour','Project / order','Days','Daily rate','Cost','Details'],...rows.map(row=>[row.assignment_date,labourer(row.labourer_id)?.name,targetName(row),row.days,row.daily_rate,assignmentAmount(row),row.notes])]);
  }
  function materialCostRows(){return state.materialMovements.filter(row=>inRange(row.movement_date)&&(movementOut(row)||['project_return','walk_in_return'].includes(row.movement_type))).filter(row=>reportState.scope==='overall'||reportState.scope==='projects'&&row.project_id||reportState.scope==='orders'&&row.walk_in_order_id).filter(row=>reportState.scope!=='projects'||$('#reportProject').value==='all'||row.project_id===$('#reportProject').value).filter(row=>reportState.scope!=='orders'||$('#reportOrder').value==='all'||row.walk_in_order_id===$('#reportOrder').value)}
  function renderMaterialCost(){
    const rows=materialCostRows(),net=sum(rows,row=>(movementOut(row)?1:-1)*num(row.quantity)*num(row.unit_cost));
    const body=rows.map(row=>{const returned=['project_return','walk_in_return'].includes(row.movement_type),value=num(row.quantity)*num(row.unit_cost);return`<tr><td>${date(row.movement_date)}</td><td><b>${esc(material(row.material_id)?.name||'Material')}</b><small>${returned?'Returned':'Assigned'}</small></td><td>${esc(targetName(row))}</td><td class="number">${returned?'−':''}${qty(row.quantity)} ${esc(material(row.material_id)?.unit||'')}</td><td class="number ${returned?'report-positive':''}">${returned?'−':''}${money(value)}</td></tr>`});
    setOutput(rows.length?table(['Date','Material','Project / order','Quantity','Cost'],body):reportEmpty('No material cost','No matching assignments or returns.'),[['Date','Material','Movement','Project / order','Quantity','Unit','Unit cost','Net cost'],...rows.map(row=>[row.movement_date,material(row.material_id)?.name,movementName(row.movement_type),targetName(row),row.quantity,material(row.material_id)?.unit,row.unit_cost,(movementOut(row)?1:-1)*num(row.quantity)*num(row.unit_cost)])]);
  }
  function renderSupplierPayables(){
    const supplierId=$('#reportSupplier').value,rows=state.purchaseBills.filter(row=>row.status!=='Cancelled'&&(supplierId==='all'||row.supplier_id===supplierId)),billed=sum(rows,row=>row.total_amount),paid=sum(rows,row=>row.amount_paid),balance=billed-paid;
    const body=rows.map(row=>{const due=purchaseBalance(row);return`<tr><td><b>${esc(row.bill_number)}</b><small>${date(row.bill_date)}</small></td><td>${esc(supplier(row.supplier_id)?.name||'Supplier')}</td><td class="number">${money(row.total_amount)}</td><td class="number report-positive">${money(row.amount_paid)}</td><td class="number ${due>0?'report-negative':due<0?'report-positive':''}">${money(due)}</td></tr>`});
    setOutput(rows.length?table(['Purchase','Supplier','Bill amount','Paid','Balance'],body,'compact'):reportEmpty('No supplier bills','No bills match this supplier.'),[['Bill number','Date','Supplier','Bill amount','Paid','Balance'],...rows.map(row=>[row.bill_number,row.bill_date,supplier(row.supplier_id)?.name,row.total_amount,row.amount_paid,purchaseBalance(row)])]);
  }
  function renderPurchases(){
    const supplierId=$('#reportSupplier').value,rows=state.purchaseBills.filter(row=>row.status!=='Cancelled'&&inRange(row.bill_date)&&(supplierId==='all'||row.supplier_id===supplierId)),subtotal=sum(rows,row=>row.subtotal??row.total_amount),discount=sum(rows,row=>row.discount),total=sum(rows,row=>row.total_amount);
    const body=rows.map(row=>`<tr><td><b>${esc(row.bill_number)}</b><small>${date(row.bill_date)}</small></td><td>${esc(supplier(row.supplier_id)?.name||'Supplier')}</td><td class="number">${purchaseLines(row.id).length}</td><td class="number">${money(row.subtotal??row.total_amount)}</td><td class="number">${money(row.discount)}</td><td class="number">${money(row.total_amount)}</td></tr>`);
    setOutput(rows.length?table(['Purchase','Supplier','Items','Subtotal','Discount','Total'],body):reportEmpty('No purchases','No purchases match these filters.'),[['Bill number','Date','Supplier','Items','Subtotal','Discount','Grand total'],...rows.map(row=>[row.bill_number,row.bill_date,supplier(row.supplier_id)?.name,purchaseLines(row.id).length,row.subtotal??row.total_amount,row.discount,row.total_amount])]);
  }
  function renderMaterialMovement(){
    const materialId=$('#reportMaterial').value,materials=state.materials.filter(row=>materialId==='all'||row.id===materialId),all=[];
    materials.forEach(item=>{let balance=state.materialMovements.filter(row=>row.material_id===item.id&&beforeFrom(row.movement_date)).reduce((total,row)=>total+(movementIn(row)?num(row.quantity):movementOut(row)?-num(row.quantity):0),0);state.materialMovements.filter(row=>row.material_id===item.id&&inRange(row.movement_date)).sort((a,b)=>`${a.movement_date}${a.created_at}`.localeCompare(`${b.movement_date}${b.created_at}`)).forEach(row=>{const incoming=movementIn(row),outgoing=movementOut(row);if(incoming)balance+=num(row.quantity);if(outgoing)balance-=num(row.quantity);all.push({row,item,incoming:incoming?num(row.quantity):0,outgoing:outgoing?num(row.quantity):0,balance})})});
    const totalIn=sum(all,row=>row.incoming),totalOut=sum(all,row=>row.outgoing),closing=sum(materials,row=>materialMetrics(row).stock);
    const body=all.map(({row,item,incoming,outgoing,balance})=>`<tr><td>${date(row.movement_date)}</td><td><b>${esc(item.name)}</b><small>${esc(movementName(row.movement_type))}</small></td><td>${esc(targetName(row))}</td><td class="number report-positive">${incoming?`${qty(incoming)} ${esc(item.unit)}`:''}</td><td class="number report-negative">${outgoing?`${qty(outgoing)} ${esc(item.unit)}`:''}</td><td class="number report-balance">${qty(balance)} ${esc(item.unit)}</td></tr>`);
    setOutput(all.length?table(['Date','Material / movement','Project / order','In','Out','Balance'],body,'report-ledger'):reportEmpty('No material movements','No movement matches these filters.'),[['Date','Material','Movement','Project / order','In','Out','Balance','Unit','Unit cost'],...all.map(({row,item,incoming,outgoing,balance})=>[row.movement_date,item.name,movementName(row.movement_type),targetName(row),incoming,outgoing,balance,item.unit,row.unit_cost])]);
  }
  function renderMaterialQuantity(){
    const materialId=$('#reportMaterial').value,rows=state.materials.filter(row=>materialId==='all'||row.id===materialId).map(row=>({row,...materialMetrics(row)})),stockValue=sum(rows,item=>item.stock*item.unitCost);
    const body=rows.map(item=>`<tr><td><b>${esc(item.row.name)}</b><small>${esc(item.row.sku||'')}</small></td><td>${esc(item.row.unit)}</td><td class="number ${item.stock<0?'report-negative':''}">${qty(item.stock)}</td><td class="number">${money(item.unitCost)}</td><td class="number">${money(item.stock*item.unitCost)}</td></tr>`);
    setOutput(rows.length?table(['Material','Unit','Closing stock','Latest cost','Stock value'],body,'compact'):reportEmpty('No materials','Add materials in Purchasing.'),[['Material ID','Material','Unit','Closing stock','Latest cost','Stock value'],...rows.map(item=>[item.row.sku,item.row.name,item.row.unit,item.stock,item.unitCost,item.stock*item.unitCost])]);
  }
  function labourLedgerRows(){
    const labourId=$('#reportLabour').value,workers=state.labourers.filter(row=>labourId==='all'||row.id===labourId),rows=[];
    workers.forEach(worker=>{let balance=0;const events=[...state.labourAssignments.filter(row=>row.labourer_id===worker.id).map(row=>({day:row.assignment_date,created:row.created_at,type:'Assigned wages',details:targetName(row),assigned:assignmentAmount(row),paid:0,advance:0})),...state.labourWageSettlements.filter(row=>row.labourer_id===worker.id&&num(row.cash_paid)>0).map(row=>({day:row.settlement_date,created:row.created_at,type:'Wages paid',details:row.notes||'',assigned:0,paid:num(row.cash_paid),advance:0})),...state.payments.filter(row=>row.labourer_id===worker.id&&row.payment_type==='labour_advance').map(row=>({day:row.payment_date,created:row.created_at,type:'Advance',details:row.description||'',assigned:0,paid:0,advance:num(row.amount)}))].sort((a,b)=>`${a.day}${a.created}`.localeCompare(`${b.day}${b.created}`));events.forEach(event=>{balance+=event.assigned-event.paid-event.advance;if(inRange(event.day))rows.push({...event,worker,balance})})});return rows;
  }
  function renderLabourStatement(){
    const rows=labourLedgerRows(),assigned=sum(rows,row=>row.assigned),paid=sum(rows,row=>row.paid),advance=sum(rows,row=>row.advance),labourId=$('#reportLabour').value,to=$('#reportTo').value,workerIds=new Set(state.labourers.filter(row=>labourId==='all'||row.id===labourId).map(row=>row.id)),closing=sum(state.labourAssignments.filter(row=>workerIds.has(row.labourer_id)&&(!to||row.assignment_date<=to)),assignmentAmount)-sum(state.labourWageSettlements.filter(row=>workerIds.has(row.labourer_id)&&(!to||row.settlement_date<=to)),row=>row.cash_paid)-sum(state.payments.filter(row=>workerIds.has(row.labourer_id)&&row.payment_type==='labour_advance'&&(!to||row.payment_date<=to)),row=>row.amount);
    const body=rows.map(row=>`<tr><td>${date(row.day)}</td><td><b>${esc(row.worker.name)}</b><small>${esc(row.type)} · ${esc(row.details)}</small></td><td class="number">${row.assigned?money(row.assigned):''}</td><td class="number report-positive">${row.paid?money(row.paid):''}</td><td class="number report-positive">${row.advance?money(row.advance):''}</td><td class="number report-balance ${row.balance<0?'report-positive':''}">${money(row.balance)}</td></tr>`);
    setOutput(rows.length?table(['Date','Labour / entry','Assigned','Paid','Advance','Balance'],body,'report-ledger'):reportEmpty('No labour statement','No matching labour activity.'),[['Date','Labour','Entry','Details','Wages assigned','Wages paid','Advance','Balance'],...rows.map(row=>[row.day,row.worker.name,row.type,row.details,row.assigned,row.paid,row.advance,row.balance])]);
  }
  function renderBankStatement(){
    const accountId=$('#reportAccount').value;if(!accountId){setOutput(reportEmpty('Select an account','Choose a bank or cash account to view its statement.'),[]);return}const selected=account(accountId),opening=num(selected.opening_balance)+state.payments.filter(row=>beforeFrom(row.payment_date)).reduce((total,row)=>total+(row.to_account_id===accountId?num(row.amount):0)-(row.from_account_id===accountId?num(row.amount):0),0);let balance=opening;const rows=state.payments.filter(row=>(row.from_account_id===accountId||row.to_account_id===accountId)&&inRange(row.payment_date)).sort((a,b)=>`${a.payment_date}${a.created_at}`.localeCompare(`${b.payment_date}${b.created_at}`)).map(row=>{const incoming=row.to_account_id===accountId?num(row.amount):0,outgoing=row.from_account_id===accountId?num(row.amount):0;balance+=incoming-outgoing;return{row,incoming,outgoing,balance}}),moneyIn=sum(rows,row=>row.incoming),moneyOut=sum(rows,row=>row.outgoing);
    const body=rows.map(({row,incoming,outgoing,balance:running})=>`<tr><td>${date(row.payment_date)}</td><td><b>${esc(row.description||row.payment_type)}</b><small>${esc(row.payment_number||'')} · ${esc(targetName(row))}</small></td><td class="number report-positive">${incoming?money(incoming):''}</td><td class="number report-negative">${outgoing?money(outgoing):''}</td><td class="number report-balance">${money(running)}</td></tr>`);
    setOutput(rows.length?table(['Date','Transaction','Money in','Money out','Balance'],body,'report-ledger'):reportEmpty('No bank transactions','No transactions match this date range.'),[['Date','Number','Description','Target','Money in','Money out','Balance'],...rows.map(({row,incoming,outgoing,balance:running})=>[row.payment_date,row.payment_number,row.description,targetName(row),incoming,outgoing,running])]);
  }
  function fillSelect(selector,rows,label,allLabel='All') {const el=$(selector),old=el.value||'all';el.innerHTML=`<option value="all">${esc(allLabel)}</option>${rows.map(row=>`<option value="${row.id}">${esc(label(row))}</option>`).join('')}`;el.value=[...el.options].some(option=>option.value===old)?old:'all'}
  function configureFilters(){
    fillSelect('#reportProject',state.projects,row=>projectLabel(row),'All projects');fillSelect('#reportOrder',state.walkInOrders,row=>orderLabel(row),'All orders');fillSelect('#reportSupplier',state.suppliers,row=>row.name,'All suppliers');fillSelect('#reportMaterial',state.materials,row=>row.name,'All materials');fillSelect('#reportLabour',state.labourers,row=>row.name,'All labour persons');
    const account=$('#reportAccount'),old=account.value;account.innerHTML='<option value="">Select account</option>'+state.paymentAccounts.map(row=>`<option value="${row.id}">${esc(row.name)}${row.bank_name?` - ${esc(row.bank_name)}`:''}</option>`).join('');account.value=[...account.options].some(option=>option.value===old)?old:'';
    const filters=definitions[reportState.type]?.filters||[],scope=scopedReports.has(reportState.type);$('#reportDateTools').classList.toggle('hidden',!filters.includes('date'));$('#reportAllDatesBtn').setAttribute('aria-pressed',String(!$('#reportFrom').value&&!$('#reportTo').value));$('#reportTitle').textContent=statementProject()?'Project receivable statement':definitions[reportState.type].title;$('#reportScope').classList.toggle('hidden',!scope);$$('[data-report-scope]').forEach(button=>button.classList.toggle('active',button.dataset.reportScope===reportState.scope));
    const visible={From:filters.includes('date'),To:filters.includes('date'),Project:scope&&reportState.scope==='projects',Order:scope&&reportState.scope==='orders',Supplier:filters.includes('supplier'),Material:filters.includes('material'),Labour:filters.includes('labour'),Account:filters.includes('account')};Object.entries(visible).forEach(([name,show])=>$(`#report${name}Wrap`).classList.toggle('hidden',!show));
  }
  function renderCurrent(){if(!reportState.type)return;configureFilters();const valid=validReportDates();$('#reportPdfBtn').disabled=!valid;if(!valid){setOutput(reportEmpty('Check the date range','From date must be on or before To date.'),[]);return;}({profit:renderProfit,receivables:renderReceivables,expenses:renderExpenses,labourAssigned:renderLabourAssigned,materialCost:renderMaterialCost,supplierPayables:renderSupplierPayables,purchases:renderPurchases,materialMovement:renderMaterialMovement,materialQuantity:renderMaterialQuantity,labourStatement:renderLabourStatement,bankStatement:renderBankStatement}[reportState.type])()}
  function setDefaultReportDates(now=new Date()){
    // Use the device's calendar date, including around local midnight/month rollover.
    const month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
    $('#reportFrom').value=`${month}-01`;
    $('#reportTo').value=`${month}-${String(now.getDate()).padStart(2,'0')}`;
  }
  function openReport(type){setDefaultReportDates();reportState.type=type;reportState.scope='overall';$('#reportsHubPanel').classList.add('hidden');$('#reportViewerPanel').classList.remove('hidden');$('#reportTitle').textContent=definitions[type].title;renderCurrent();window.scrollTo({top:0,behavior:'instant'})}
  function showHub(){$('#reportViewerPanel').classList.add('hidden');$('#reportsHubPanel').classList.remove('hidden');reportState.type=null;$('#screenTitle').textContent='Reports';window.scrollTo({top:0,behavior:'instant'})}
  function reportFileName(){const job=statementProject();return job?`project-statement-${safeName(job.project_number||job.name)}-${$('#reportFrom').value||'all'}-${$('#reportTo').value||'dates'}`:`mughal-${reportState.type}-${today()}`;}
  async function downloadPdf(button){
    if(!validReportDates())return;
    if(!window.html2pdf){toast('PDF generator is still loading. Try again.');return;}
    const statement=Boolean(statementProject());
    if(statement&&!reportState.csv.length){toast('This project has no approved invoice to download.');return;}
    const node=document.createElement('div');node.className='report-print-document'+(statement?' statement-print':'');
    const header=statement?'':`<div class="report-print-head"><div><h1>${esc(definitions[reportState.type].title)}</h1><p>${esc(state.business?.name||'Mughal Interior')}</p><p>Period: ${esc(reportPeriod())} · Generated ${date(today())}</p></div><img src="assets/mughal-logo.png" alt="Mughal Interior"></div>`;
    node.innerHTML=header+$('#reportContent').innerHTML+businessContact();document.body.append(node);
    try{await working('Preparing report PDF…',button,()=>html2pdf().set({margin:8,filename:`${reportFileName()}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:statement?'portrait':'landscape'},pagebreak:{mode:['css','legacy'],avoid:statement?['tr','.statement-heading','.statement-parties']:[]}}).from(node).save());}finally{node.remove();}
  }
  document.addEventListener('click',event=>{const open=event.target.closest('[data-open-report]');if(open)openReport(open.dataset.openReport);const scope=event.target.closest('[data-report-scope]');if(scope){reportState.scope=scope.dataset.reportScope;renderCurrent()}if(event.target.id==='reportAllDatesBtn')clearReportDates();if(event.target.id==='reportBackBtn')showHub();if(event.target.id==='reportPdfBtn')downloadPdf(event.target);if(event.target.closest('[data-tab="reports"]'))showHub()});
  ['reportFrom','reportTo','reportProject','reportOrder','reportSupplier','reportMaterial','reportLabour','reportAccount'].forEach(id=>$('#'+id).addEventListener('change',renderCurrent));
  window.renderMobileReports=()=>{if(reportState.type)renderCurrent()};
})();
